import type { News } from "../types";

/**
 * Noticias del entorno (PESTEL). Cada noticia afecta a todo el mercado
 * durante 1 a 3 trimestres. 14 noticias por dimensión, 84 en total.
 */
const data: News[] = [
  // ───────────────────────── POLÍTICO ─────────────────────────
  {
    id: "news-politico-crisis-vacancia",
    title: "Vacancia presidencial y protestas frenan decisiones de inversión",
    pestel: "politico",
    text: "El Congreso aprobó la vacancia presidencial y el país tuvo tres mandatarios en pocos días. Las protestas en las principales ciudades y la incertidumbre llevaron a las empresas a postergar compras y contrataciones, mientras los bancos se vuelven más cautos al prestar.",
    industries: "all",
    effects: { demandPct: -8, ratePts: 1 },
    rounds: 2,
    severity: 2,
    hint: "Analistas políticos advierten que una nueva moción de vacancia ya tendría los votos necesarios en el Congreso.",
    lesson:
      "El ruido político enfría el consumo y el crédito aunque tu negocio no tenga nada que ver con la política. Cuando sube la tensión, cuida tu caja, evita endeudarte de más y no comprometas inversiones grandes hasta que el panorama se aclare.",
    basedOn: "Crisis política de noviembre de 2020 en Perú",
  },
  {
    id: "news-politico-elecciones-polarizadas",
    title: "Segunda vuelta polarizada dispara el dólar y congela proyectos",
    pestel: "politico",
    text: "A pocas semanas de la segunda vuelta, el tipo de cambio alcanzó máximos históricos y varias empresas pusieron en pausa sus planes de expansión. Los importadores ajustan sus listas de precios y las familias postergan las compras grandes hasta conocer el resultado.",
    industries: "all",
    effects: { demandPct: -7, costPct: 8, ratePts: 1.5 },
    rounds: 2,
    severity: 2,
    hint: "Las encuestas muestran un empate técnico entre dos candidatos con planes económicos opuestos y las casas de cambio reportan mayor demanda de dólares.",
    lesson:
      "Los años electorales son previsibles porque están en el calendario. Si tienes costos en dólares, adelanta parte de tus compras antes de la campaña y evita deudas en moneda extranjera cuando tus ventas son en soles.",
    basedOn: "Elecciones generales de Perú de 2021",
  },
  {
    id: "news-politico-bloqueos-sur",
    title: "Bloqueos de carreteras paralizan el comercio en el sur del país",
    pestel: "politico",
    text: "Las protestas mantienen bloqueados tramos de la Panamericana Sur y de las vías hacia Puno y Cusco. Los mercados reportan desabastecimiento, los camiones quedan varados durante días y muchos negocios de Arequipa, Juliaca y Cusco atienden a media máquina.",
    industries: "all",
    effects: { demandPct: -5, costPct: 6, regions: { sur: -28 } },
    rounds: 2,
    severity: 3,
    hint: "Gremios y frentes de defensa del sur anuncian una huelga indefinida y los transportistas empiezan a evitar las rutas hacia Puno.",
    lesson:
      "La concentración geográfica es un riesgo. Si todas tus ventas o tus proveedores dependen de una sola región o carretera, un bloqueo te deja sin ingresos. Diversifica regiones y arma inventario de seguridad apenas se anuncie el conflicto.",
    basedOn: "Protestas y bloqueos en el sur del Perú entre diciembre de 2022 e inicios de 2023",
  },
  {
    id: "news-politico-paro-nacional",
    title: "Ola de protestas masivas obliga a cerrar comercios en las grandes ciudades",
    pestel: "politico",
    text: "Semanas de marchas, saqueos aislados y toques de queda redujeron los horarios de atención de centros comerciales, restaurantes y oficinas. El transporte público opera de forma parcial y las ventas caen con fuerza en las zonas céntricas.",
    industries: "all",
    effects: { demandPct: -18, costPct: 4 },
    rounds: 2,
    severity: 3,
    hint: "Un alza en las tarifas de un servicio público genera protestas estudiantiles que crecen cada semana y suman el respaldo de los sindicatos.",
    lesson:
      "El malestar social acumulado puede estallar por un detonante pequeño. Revisa tus seguros, ten un plan de continuidad (ventas en línea, reparto, turnos flexibles) y una reserva de caja que cubra al menos un trimestre flojo.",
    basedOn: "Estallido social de Chile en 2019 y paro nacional de Colombia en 2021",
  },
  {
    id: "news-politico-tlc-asia",
    title: "Entra en vigencia acuerdo comercial que abre mercados de Asia",
    pestel: "politico",
    text: "El nuevo tratado elimina aranceles para frutas, café y prendas de algodón y alpaca, y reduce el costo de importar insumos. Los gremios exportadores esperan nuevos pedidos desde la próxima campaña y los operadores logísticos alistan más capacidad.",
    industries: ["agroexport", "moda", "logistica"],
    effects: { demandPct: 10, costPct: -3 },
    rounds: 3,
    severity: 2,
    hint: "Las cancillerías anuncian el cierre de las negociaciones y el tratado pasa al Congreso para su ratificación.",
    lesson:
      "Un tratado comercial se negocia durante años, así que da tiempo para prepararse. Quien llega primero con certificaciones, capacidad y contactos captura los pedidos. Invierte en calidad antes de la entrada en vigencia, no después.",
    basedOn: "Tratados de libre comercio de Perú con China y otros países de Asia",
  },
  {
    id: "news-politico-credito-garantia-estatal",
    title: "Gobierno lanza créditos con garantía estatal a tasas muy bajas",
    pestel: "politico",
    text: "El programa permite a las empresas formales acceder a préstamos de capital de trabajo con garantía del Estado, canalizados por bancos y cajas municipales. Las subastas adjudican los fondos a tasas muy por debajo de las habituales del mercado.",
    industries: "all",
    effects: { ratePts: -3 },
    rounds: 2,
    severity: 2,
    hint: "El Ministerio de Economía y el BCRP coordinan un programa de garantías para evitar que se rompa la cadena de pagos.",
    lesson:
      "Los programas de apoyo solo llegan a empresas formales y con buen historial crediticio. Mantener tus declaraciones al día y una buena calificación en el sistema financiero te permite aprovechar el crédito barato cuando aparece.",
    basedOn: "Programa Reactiva Perú de 2020",
  },
  {
    id: "news-politico-aranceles-destino",
    title: "Principal socio comercial impone aranceles a las importaciones",
    pestel: "politico",
    text: "El gobierno del mayor mercado de destino anunció un arancel general a los productos importados, que alcanza a los envíos peruanos de frutas, hortalizas y confecciones. Los compradores piden renegociar precios para compartir el sobrecosto.",
    industries: ["agroexport", "moda"],
    effects: { demandPct: -10 },
    rounds: 2,
    severity: 2,
    hint: "En la campaña electoral del país de destino, el candidato favorito promete aranceles para proteger a su industria local.",
    lesson:
      "Depender de un solo país comprador te expone a decisiones políticas ajenas. Diversifica tus mercados de destino y revisa en tus contratos quién asume los cambios arancelarios.",
    basedOn: "Aranceles generales aplicados por Estados Unidos a sus importaciones en 2025",
  },
  {
    id: "news-politico-paro-agrario",
    title: "Paro agrario bloquea la Panamericana en plena campaña de exportación",
    pestel: "politico",
    text: "Trabajadores del campo reclaman mejores jornales y bloquean la carretera durante varios días. Los contenedores con fruta fresca no llegan al puerto y las empresas evalúan pérdidas por el producto que se malogra en el camino.",
    industries: ["agroexport", "logistica"],
    effects: { demandPct: -8, costPct: 7 },
    rounds: 1,
    severity: 2,
    hint: "Dirigentes de trabajadores agrarios advierten que tomarán medidas si no se revisa el régimen laboral del sector.",
    lesson:
      "Un clima laboral deteriorado en tu sector es una señal de alerta, aunque tu empresa cumpla la ley. Invierte en condiciones de trabajo y ten rutas y fechas alternativas de despacho durante la campaña.",
    basedOn: "Paro agrario de Ica y La Libertad de diciembre de 2020",
  },
  {
    id: "news-politico-cumbre-lima",
    title: "Cumbre internacional llena hoteles y restaurantes de Lima",
    pestel: "politico",
    text: "Miles de delegados, empresarios y periodistas llegan a la capital para la cumbre de líderes. Los hoteles reportan ocupación casi total y los servicios de traslado, catering y turismo corto trabajan a plena capacidad.",
    industries: ["turismo", "restaurante", "cafeteria", "logistica"],
    effects: { demandPct: 2, regions: { lima: 4 } },
    rounds: 1,
    severity: 1,
    hint: "La cancillería confirma el calendario de reuniones de la cumbre y el Gobierno evalúa declarar días no laborables en Lima.",
    lesson:
      "Los grandes eventos se anuncian con meses de anticipación. Prepara oferta, personal y stock para la demanda extra, pero recuerda que es un pico temporal y no justifica gastos fijos permanentes.",
    basedOn: "Cumbres APEC realizadas en Lima en 2016 y 2024",
  },
  {
    id: "news-politico-visa-schengen",
    title: "Europa elimina la visa de turista para viajeros peruanos",
    pestel: "politico",
    text: "Desde este trimestre los peruanos pueden ingresar como turistas al espacio Schengen sin tramitar visa. Las agencias de viaje reportan más consultas por paquetes a Europa y las aerolíneas anuncian nuevas frecuencias.",
    industries: ["turismo"],
    effects: { demandPct: 6 },
    rounds: 2,
    severity: 1,
    hint: "El Parlamento Europeo aprueba la exención de visa y solo falta la firma del acuerdo con Perú.",
    lesson:
      "Un cambio de política exterior puede abrir un mercado de un día para otro. Quien ya tiene armados los paquetes, los proveedores y la publicidad captura la primera ola de demanda.",
    basedOn: "Exención de la visa Schengen para peruanos desde 2016",
  },
  {
    id: "news-politico-perspectiva-crediticia",
    title: "Calificadora mejora la perspectiva crediticia del país",
    pestel: "politico",
    text: "Una de las principales agencias de riesgo elevó la perspectiva de la deuda soberana por el manejo fiscal ordenado. El menor riesgo país abarata el financiamiento para los bancos y las empresas locales.",
    industries: "all",
    effects: { demandPct: 2, ratePts: -0.5 },
    rounds: 2,
    severity: 1,
    hint: "El déficit fiscal se reduce por segundo trimestre consecutivo y el riesgo país cae a su menor nivel del año.",
    lesson:
      "El costo de tu préstamo depende también del riesgo del país. Cuando ese riesgo baja, es buen momento para refinanciar deudas caras o negociar mejores tasas con tu banco o tu caja.",
  },
  {
    id: "news-politico-cambio-autoridades",
    title: "Nuevas autoridades regionales y municipales frenan las compras públicas",
    pestel: "politico",
    text: "Con el cambio de gestión, los gobiernos regionales y las municipalidades revisan contratos y demoran las convocatorias. La ejecución del presupuesto arranca lenta y los proveedores del Estado ven postergadas sus órdenes de servicio.",
    industries: ["limpieza", "consultoria", "maquinaria", "software"],
    effects: { demandPct: -6 },
    rounds: 1,
    severity: 1,
    hint: "Las autoridades electas anuncian que auditarán los contratos heredados antes de firmar nuevos.",
    lesson:
      "Si le vendes al Estado, el primer trimestre de cada nueva gestión suele ser lento. Equilibra tu cartera con clientes privados y no cuentes con cobrar rápido en los meses de transición.",
    basedOn: "Baja ejecución presupuestal en el primer año de nuevas gestiones regionales y municipales",
  },
  {
    id: "news-politico-obras-norte",
    title: "Ejecutivo destraba paquete de obras públicas en el norte",
    pestel: "politico",
    text: "El Gobierno aprobó recursos para carreteras, colegios, hospitales y defensas ribereñas en Piura, Lambayeque y La Libertad. Las contratistas empiezan a demandar equipos, transporte, consultorías y servicios de mantenimiento.",
    industries: ["maquinaria", "logistica", "consultoria", "limpieza"],
    effects: { demandPct: 3, regions: { norte: 3 } },
    rounds: 3,
    severity: 1,
    hint: "El Ministerio de Economía anuncia transferencias a los gobiernos regionales del norte para obras de prevención y reconstrucción.",
    lesson:
      "El presupuesto público es una señal de demanda futura. Revisa qué regiones y sectores recibirán inversión y posiciona tu empresa allí antes de que salgan las licitaciones.",
    basedOn: "Reconstrucción con Cambios tras el Niño costero de 2017",
  },
  {
    id: "news-politico-disolucion-congreso",
    title: "Presidente disuelve el Congreso y convoca a nuevas elecciones",
    pestel: "politico",
    text: "El Ejecutivo disolvió el Congreso tras considerar denegada la confianza. Los mercados reaccionaron con relativa calma, pero varias empresas prefieren esperar antes de cerrar contratos e inversiones.",
    industries: "all",
    effects: { demandPct: -4 },
    rounds: 1,
    severity: 1,
    hint: "El gabinete plantea una cuestión de confianza y los voceros del Congreso adelantan que no la aprobarán.",
    lesson:
      "No toda crisis política termina en crisis económica. Una macroeconomía sólida amortigua el golpe. Aprende a distinguir el ruido del riesgo real antes de frenar todo tu plan.",
    basedOn: "Disolución del Congreso peruano en setiembre de 2019",
  },

  // ───────────────────────── ECONÓMICO ─────────────────────────
  {
    id: "news-economico-bcrp-baja-tasa",
    title: "BCRP recorta su tasa de referencia y abarata el crédito",
    pestel: "economico",
    text: "Con la inflación de regreso al rango meta, el Banco Central redujo otra vez su tasa de referencia. Bancos y cajas municipales empiezan a trasladar la rebaja a los préstamos para empresas y a los créditos de consumo.",
    industries: "all",
    effects: { demandPct: 3, ratePts: -1 },
    rounds: 2,
    severity: 1,
    hint: "La inflación anual cede por varios meses seguidos y el directorio del BCRP señala que evalúa flexibilizar su política monetaria.",
    lesson:
      "La tasa de referencia del BCRP marca el rumbo del costo del dinero. Si lees sus comunicados mensuales, puedes anticipar cuándo conviene tomar deuda, refinanciar o esperar.",
    basedOn: "Ciclo de recortes de la tasa de referencia del BCRP iniciado en 2023",
  },
  {
    id: "news-economico-bcrp-sube-tasa",
    title: "BCRP eleva su tasa de referencia para frenar la inflación",
    pestel: "economico",
    text: "El Banco Central volvió a subir su tasa de referencia ante una inflación que se mantiene fuera del rango meta. Los créditos de capital de trabajo, hipotecarios y vehiculares se encarecen y los bancos piden más garantías.",
    industries: "all",
    effects: { demandPct: -5, ratePts: 3 },
    rounds: 3,
    severity: 2,
    hint: "La inflación supera el rango meta del BCRP por varios meses y otros bancos centrales de la región ya están subiendo sus tasas.",
    lesson:
      "Cuando la inflación sube, las tasas la siguen. Una empresa muy endeudada sufre doble: vende menos y paga más intereses. Mantén un nivel de deuda que puedas pagar aun con tasas altas.",
    basedOn: "Alzas de la tasa de referencia del BCRP entre 2021 y 2023",
  },
  {
    id: "news-economico-inflacion-alimentos",
    title: "Aceite, harina y azúcar encabezan el alza de precios de alimentos",
    pestel: "economico",
    text: "El encarecimiento internacional de granos y aceites se traslada a los mercados mayoristas. Panaderías, restaurantes y bodegas pagan más por sus insumos, y las familias reducen las salidas a comer y los antojos.",
    industries: ["restaurante", "pasteleria", "cafeteria", "minimarket", "bebidas"],
    effects: { demandPct: -4, costPct: 10 },
    rounds: 2,
    severity: 2,
    hint: "Los precios internacionales del trigo, el maíz y el aceite de soya suben con fuerza en las bolsas de materias primas.",
    lesson:
      "Cuando sube el costo de tus insumos debes decidir cuánto trasladas al precio y cuánto absorbes. Conoce tu margen por producto, negocia compras por volumen y ajusta porciones o recetas antes de perder dinero en cada venta.",
    basedOn: "Inflación de alimentos de 2022 en Perú y el mundo",
  },
  {
    id: "news-economico-dolar-sube",
    title: "El dólar marca nuevo máximo y encarece los productos importados",
    pestel: "economico",
    text: "El tipo de cambio cerró al alza por la salida de capitales y la mayor demanda de dólares. Los importadores de vehículos, equipos, medicinas y tecnología actualizan sus listas de precios para proteger sus márgenes.",
    industries: ["autos", "maquinaria", "farmacia", "ecommerce", "telecom", "software"],
    effects: { demandPct: -4, costPct: 12 },
    rounds: 2,
    severity: 2,
    hint: "El tipo de cambio sube varias semanas seguidas y el BCRP interviene vendiendo dólares para moderar la volatilidad.",
    lesson:
      "Si compras en dólares y vendes en soles tienes riesgo cambiario. Puedes reducirlo con compras adelantadas, contratos a futuro (forwards), precios indexados o proveedores locales. Lo que no debes hacer es ignorarlo.",
    basedOn: "Alza del tipo de cambio en Perú durante 2021",
  },
  {
    id: "news-economico-dolar-baja",
    title: "El dólar retrocede y da respiro a los importadores",
    pestel: "economico",
    text: "El ingreso de dólares por las exportaciones mineras y el menor riesgo país llevaron al tipo de cambio a su nivel más bajo en meses. Los importadores reponen inventario a menor costo y algunos anuncian rebajas.",
    industries: ["autos", "maquinaria", "farmacia", "ecommerce", "telecom"],
    effects: { costPct: -5 },
    rounds: 2,
    severity: 1,
    hint: "Los precios de los metales suben y los analistas proyectan un sol más fuerte en los próximos meses.",
    lesson:
      "Un dólar barato es una oportunidad para reponer inventario, comprar equipos o prepagar deuda en dólares. Decide si trasladas el ahorro al precio para ganar cuota o lo conservas como margen.",
  },
  {
    id: "news-economico-retiro-afp",
    title: "Congreso aprueba nuevo retiro de fondos de AFP",
    pestel: "economico",
    text: "Los afiliados podrán retirar parte de su fondo de pensiones en los próximos meses. Los bancos estiman que una porción importante se destinará a pagar deudas y al consumo de electrodomésticos, ropa, viajes y mejoras del hogar.",
    industries: "all",
    effects: { demandPct: 10 },
    rounds: 2,
    severity: 2,
    hint: "La Comisión de Economía del Congreso aprueba el dictamen de retiro de fondos y el tema pasa al Pleno.",
    lesson:
      "Un retiro de fondos es un impulso temporal al consumo, no un cambio permanente. Prepara stock y campañas para capturarlo, pero no asumas gastos fijos pensando que la demanda se quedará en ese nivel.",
    basedOn: "Retiros extraordinarios de fondos de AFP aprobados en Perú desde 2020",
  },
  {
    id: "news-economico-cts-disponible",
    title: "Trabajadores podrán disponer del total de su CTS",
    pestel: "economico",
    text: "La norma autoriza el retiro libre de la compensación por tiempo de servicios. Las entidades financieras reportan movimientos desde los primeros días y el comercio espera un repunte en las compras de las familias.",
    industries: "all",
    effects: { demandPct: 4 },
    rounds: 1,
    severity: 1,
    hint: "El Congreso debate ampliar la libre disponibilidad de la CTS y los gremios de comercio respaldan la medida.",
    lesson:
      "Parte de la liquidez extra se va al consumo y parte a pagar deudas. Los depósitos de CTS de mayo y noviembre, igual que las gratificaciones de julio y diciembre, marcan fechas en las que tus clientes tienen más dinero disponible.",
    basedOn: "Libre disponibilidad de la CTS aprobada en Perú en varios periodos desde 2021",
  },
  {
    id: "news-economico-cobre-alto",
    title: "Precio del cobre sube y dinamiza las regiones mineras",
    pestel: "economico",
    text: "La cotización del cobre alcanzó niveles altos por la demanda mundial de electrificación. Las mineras aceleran compras y contrataciones, y el mayor canon eleva el gasto en Arequipa, Moquegua, Apurímac y Cusco.",
    industries: "all",
    effects: { demandPct: 2, regions: { sur: 4 } },
    rounds: 3,
    severity: 1,
    hint: "Los inventarios mundiales de cobre caen y los bancos de inversión elevan sus proyecciones de precio.",
    lesson:
      "La minería arrastra a proveedores, transportistas, hoteles y comercio local. Si el ciclo de los metales es favorable, las regiones mineras crecen más rápido que el promedio. Considera dónde estará la demanda al decidir tu expansión.",
    basedOn: "Ciclos de precios altos del cobre en 2021 y 2024",
  },
  {
    id: "news-economico-recesion",
    title: "La economía entra en recesión y el consumo se contrae",
    pestel: "economico",
    text: "El PBI acumula trimestres de caída por el golpe del clima, la menor inversión privada y la conflictividad social. Las familias priorizan lo básico, crece la búsqueda de marcas económicas y las empresas recortan presupuestos.",
    industries: "all",
    effects: { demandPct: -9 },
    rounds: 3,
    severity: 2,
    hint: "La inversión privada cae por varios trimestres y los indicadores adelantados (consumo de cemento, importación de bienes de capital) retroceden.",
    lesson:
      "En recesión el cliente no desaparece, se vuelve más sensible al precio. Protege tu caja, reduce gastos que no generan ventas y ofrece presentaciones o planes más accesibles sin destruir tu marca.",
    basedOn: "Recesión de la economía peruana en 2023",
  },
  {
    id: "news-economico-fletes-contenedores",
    title: "Fletes marítimos se multiplican por la crisis de contenedores",
    pestel: "economico",
    text: "La escasez de contenedores y la congestión de los puertos elevaron con fuerza las tarifas de las navieras. Los embarques llegan con semanas de retraso y tanto importadores como exportadores ven cómo el costo logístico se come su margen.",
    industries: ["moda", "ecommerce", "autos", "maquinaria", "agroexport", "farmacia"],
    effects: { costPct: 18 },
    rounds: 3,
    severity: 3,
    hint: "Las navieras reportan puertos congestionados en Asia y Norteamérica y anuncian recargos para los próximos embarques.",
    lesson:
      "Tu cadena de suministro es tan fuerte como su eslabón más débil. Evalúa proveedores más cercanos, pedidos adelantados e inventario de seguridad. Lo barato que llega tarde puede salir más caro que lo local.",
    basedOn: "Crisis mundial de contenedores y fletes marítimos de 2021",
  },
  {
    id: "news-economico-precio-pollo",
    title: "El precio del pollo sube en los mercados por el alza del maíz",
    pestel: "economico",
    text: "El maíz amarillo y la soya, principales insumos de la crianza, se encarecieron en el mercado internacional. El kilo de pollo sube en los centros de acopio y las pollerías evalúan ajustar sus cartas.",
    industries: ["restaurante"],
    effects: { costPct: 12 },
    rounds: 2,
    severity: 2,
    hint: "El precio internacional del maíz amarillo duro sube por varias semanas y los avicultores advierten mayores costos.",
    lesson:
      "Cuando un solo insumo pesa mucho en tu costo, su precio define tu margen. Sigue el precio de las materias primas que usa tu proveedor, no solo el precio que él te cobra, y ten lista una carta alternativa.",
    basedOn: "Alza del precio del pollo y del maíz amarillo en 2022",
  },
  {
    id: "news-economico-tasas-hipotecarias",
    title: "Bancos bajan tasas hipotecarias y reactivan la venta de viviendas",
    pestel: "economico",
    text: "La competencia entre bancos y el menor costo de fondeo llevaron las tasas hipotecarias a su nivel más bajo en años. Las inmobiliarias reportan más visitas a sus casetas de venta y más separaciones de departamentos y lotes.",
    industries: ["inmobiliaria", "lotes"],
    effects: { demandPct: 6, ratePts: -1 },
    rounds: 2,
    severity: 1,
    hint: "El BCRP acumula recortes en su tasa de referencia y los bancos anuncian campañas hipotecarias.",
    lesson:
      "En bienes de alto valor el cliente compra una cuota mensual, no un precio total. Una baja pequeña en la tasa cambia cuántas familias califican al crédito. Vigila las tasas para decidir cuándo lanzar tus proyectos.",
  },
  {
    id: "news-economico-rebote-reapertura",
    title: "Reapertura de la economía dispara el consumo reprimido",
    pestel: "economico",
    text: "Con el fin de las restricciones, las familias vuelven a gastar en todo lo que postergaron. Los centros comerciales recuperan su afluencia, las empresas retoman proyectos y el PBI registra una de sus mayores tasas de crecimiento en décadas.",
    industries: "all",
    effects: { demandPct: 16 },
    rounds: 2,
    severity: 3,
    hint: "El Gobierno anuncia el cronograma de reapertura por fases y los indicadores de movilidad muestran más gente en las calles.",
    lesson:
      "Después de una crisis fuerte suele venir un rebote. Las empresas que conservaron a su equipo, a sus proveedores y algo de caja son las que pueden atender la demanda cuando regresa.",
    basedOn: "Rebote de la economía peruana en 2021 tras la pandemia",
  },
  {
    id: "news-economico-megapuerto",
    title: "Nuevo megapuerto acorta el viaje de la carga hacia Asia",
    pestel: "economico",
    text: "El terminal portuario inició operaciones con rutas directas a Asia que reducen los días de tránsito. Los exportadores de fruta y los importadores de mercadería proyectan menores costos logísticos.",
    industries: ["agroexport", "logistica", "ecommerce", "maquinaria"],
    effects: { demandPct: 3, costPct: -4 },
    rounds: 3,
    severity: 1,
    hint: "Las obras del megapuerto entran en su fase final y las navieras anuncian las primeras rutas directas.",
    lesson:
      "La infraestructura cambia el mapa de la competencia. Un puerto, una carretera o un aeropuerto nuevo abarata unas rutas y vuelve menos atractivas otras. Ubica tu operación pensando en la infraestructura que viene.",
    basedOn: "Inauguración del puerto de Chancay en noviembre de 2024",
  },

  // ───────────────────────── SOCIAL ─────────────────────────
  {
    id: "news-social-pandemia",
    title: "Emergencia sanitaria obliga a cerrar locales de atención al público",
    pestel: "social",
    text: "El Gobierno declaró la emergencia sanitaria y dispuso una cuarentena nacional. Restaurantes, gimnasios, academias, tiendas y agencias de viaje suspenden la atención presencial, y las familias concentran su gasto en alimentos y medicinas.",
    industries: [
      "restaurante",
      "cafeteria",
      "pasteleria",
      "moda",
      "gimnasio",
      "turismo",
      "educacion",
      "autos",
      "inmobiliaria",
      "lotes",
    ],
    effects: { demandPct: -30 },
    rounds: 2,
    severity: 3,
    hint: "La Organización Mundial de la Salud alerta sobre un nuevo virus respiratorio que ya llegó a varios países de la región.",
    lesson:
      "Los eventos extremos son poco probables, pero ocurren. Una reserva de caja, costos fijos livianos y un canal digital listo marcan la diferencia entre sobrevivir y cerrar. Pregúntate cuántos meses aguanta tu empresa sin vender.",
    basedOn: "Paralización por la pandemia de 2020",
  },
  {
    id: "news-social-retorno-presencialidad",
    title: "Fin de los aforos: el público regresa a locales y aulas",
    pestel: "social",
    text: "Con el levantamiento de las últimas restricciones sanitarias, los consumidores retoman sus rutinas. Restaurantes, cafeterías, gimnasios e institutos reportan locales llenos y listas de espera en las horas punta.",
    industries: ["restaurante", "cafeteria", "gimnasio", "educacion", "turismo", "moda"],
    effects: { demandPct: 12 },
    rounds: 2,
    severity: 2,
    hint: "El Ministerio de Salud anuncia que evalúa eliminar los límites de aforo ante el avance de la vacunación.",
    lesson:
      "La demanda reprimida regresa de golpe. Si no tienes personal capacitado y capacidad lista, el cliente se va con el competidor que sí abrió a tiempo. Planifica la contratación con un trimestre de anticipación.",
    basedOn: "Levantamiento de aforos y restricciones sanitarias en 2022",
  },
  {
    id: "news-social-clasificacion-mundial",
    title: "La selección clasifica al Mundial y el consumo se viste de rojo y blanco",
    pestel: "social",
    text: "La clasificación desata la venta de camisetas, televisores, paquetes de viaje y reuniones para ver los partidos. Pollerías, bodegas y marcas de bebidas preparan promociones para los días de partido.",
    industries: ["restaurante", "bebidas", "minimarket", "moda", "turismo", "telecom"],
    effects: { demandPct: 9 },
    rounds: 2,
    severity: 2,
    hint: "La selección llega a las últimas fechas de las eliminatorias con opciones reales de clasificar.",
    lesson:
      "Las emociones colectivas mueven el consumo. Un evento deportivo tiene fecha conocida: prepara stock, promociones y personal, y cuida de no usar marcas o símbolos registrados sin autorización.",
    basedOn: "Clasificación de Perú al Mundial de Rusia 2018",
  },
  {
    id: "news-social-juegos-lima",
    title: "Juegos continentales traen miles de visitantes a Lima",
    pestel: "social",
    text: "La capital recibe a deportistas, delegaciones y turistas por uno de los mayores eventos deportivos de su historia. La ciudad estrena sedes, la ocupación hotelera sube y el comercio alrededor de las villas deportivas se dinamiza.",
    industries: "all",
    effects: { demandPct: 1, regions: { lima: 5 } },
    rounds: 1,
    severity: 1,
    hint: "El comité organizador confirma el calendario de competencias y empieza la venta de entradas.",
    lesson:
      "Un evento grande concentra su efecto en una ciudad y en pocas semanas. Evalúa si tu negocio está cerca del flujo de visitantes antes de invertir, porque no todos los rubros se benefician igual.",
    basedOn: "Juegos Panamericanos y Parapanamericanos Lima 2019",
  },
  {
    id: "news-social-extorsion",
    title: "Ola de extorsiones golpea a comercios y transportistas",
    pestel: "social",
    text: "Los gremios reportan cierres de bodegas, restaurantes y talleres por amenazas de bandas criminales. Las empresas elevan su gasto en vigilancia, cámaras y seguros, y muchos clientes evitan salir de noche.",
    industries: "all",
    effects: { demandPct: -7, costPct: 4 },
    rounds: 3,
    severity: 2,
    hint: "Las denuncias por extorsión crecen trimestre a trimestre y los gremios de bodegueros piden declarar el estado de emergencia.",
    lesson:
      "La inseguridad es un costo del entorno que debes presupuestar. Invierte en prevención, seguros y canales de venta que reduzcan el manejo de efectivo, como las billeteras digitales.",
    basedOn: "Aumento de las extorsiones a negocios en Perú entre 2023 y 2025",
  },
  {
    id: "news-social-migracion",
    title: "Llegada de migrantes amplía la oferta laboral y el consumo básico",
    pestel: "social",
    text: "El ingreso sostenido de migrantes aumenta la disponibilidad de trabajadores en comercio y servicios. También crece la demanda de alimentos, alquileres, telefonía y envíos de dinero.",
    industries: "all",
    effects: { demandPct: 2, wagePct: -2 },
    rounds: 3,
    severity: 1,
    hint: "Migraciones reporta un aumento sostenido de ingresos por la frontera norte.",
    lesson:
      "Los cambios demográficos mueven a la vez el mercado laboral y el de consumo. Un nuevo grupo de población es también un segmento de clientes con necesidades propias. Contrata siempre con todos los derechos y evita sanciones de SUNAFIL.",
    basedOn: "Migración venezolana hacia Perú y otros países de la región desde 2017",
  },
  {
    id: "news-social-vida-saludable",
    title: "Crece la preferencia por alimentos saludables y actividad física",
    pestel: "social",
    text: "Los estudios de consumo muestran más personas que leen etiquetas, reducen el azúcar y pagan por entrenar. Ganan espacio las bebidas naturales, los suplementos y las opciones sin azúcar añadida.",
    industries: ["bebidas", "gimnasio", "cafeteria", "farmacia"],
    effects: { demandPct: 5 },
    rounds: 3,
    severity: 1,
    hint: "Las consultoras de consumo reportan que más hogares declaran revisar el contenido de azúcar y grasas antes de comprar.",
    lesson:
      "Las tendencias sociales avanzan lento, pero duran años. Un estudio del consumidor te permite detectarlas a tiempo y ajustar tu portafolio antes que el resto.",
  },
  {
    id: "news-social-boom-gastronomico",
    title: "Restaurantes peruanos lideran rankings mundiales y atraen turistas",
    pestel: "social",
    text: "Los reconocimientos internacionales a la cocina peruana impulsan las reservas de viajeros que llegan a comer. El turismo gastronómico crece en Lima, Arequipa y Cusco, y eleva el interés por el café, el cacao y los insumos locales.",
    industries: ["restaurante", "cafeteria", "turismo", "pasteleria"],
    effects: { demandPct: 5 },
    rounds: 2,
    severity: 1,
    hint: "Medios internacionales especializados adelantan que varios restaurantes peruanos figuran entre los nominados de este año.",
    lesson:
      "La reputación de un país o de un sector beneficia a todos sus miembros, incluso a los pequeños. Aprovecha la ola con calidad constante e insumos de origen, porque el visitante compara.",
    basedOn: "Reconocimientos internacionales a la gastronomía peruana",
  },
  {
    id: "news-social-paro-transportistas",
    title: "Paro de transportistas deja a Lima con menos buses y locales vacíos",
    pestel: "social",
    text: "Los gremios de transporte urbano acataron una paralización en protesta por la inseguridad. Miles de trabajadores no llegaron a sus centros de labores, varios colegios pasaron a clases virtuales y el comercio atendió con poco público.",
    industries: "all",
    effects: { regions: { lima: -6 } },
    rounds: 1,
    severity: 1,
    hint: "Gremios de transporte urbano anuncian una paralización si no hay medidas contra las extorsiones a sus conductores.",
    lesson:
      "Un paro de un día también cuesta. Ten un protocolo: trabajo remoto para quien pueda, turnos flexibles, movilidad para el personal clave y ventas por canales digitales.",
    basedOn: "Paros de transportistas de Lima y Callao de 2024",
  },
  {
    id: "news-social-conflicto-minero",
    title: "Conflicto con comunidades paraliza corredor minero del sur",
    pestel: "social",
    text: "Las comunidades bloquean la vía por la que sale el mineral y la operación suspende actividades. Los proveedores de equipos, transporte, mantenimiento y consultoría ven congeladas sus órdenes de compra.",
    industries: ["maquinaria", "logistica", "consultoria", "limpieza"],
    effects: { demandPct: -6, regions: { sur: -8 } },
    rounds: 2,
    severity: 2,
    hint: "La Defensoría del Pueblo reporta que las mesas de diálogo en el corredor minero se rompieron sin acuerdos.",
    lesson:
      "Si tu principal cliente opera en una zona de conflicto, su riesgo es tu riesgo. Revisa los reportes de conflictos sociales y evita que un solo cliente concentre la mayor parte de tus ventas.",
    basedOn: "Bloqueos recurrentes en el corredor minero del sur del Perú",
  },
  {
    id: "news-social-dengue",
    title: "Epidemia de dengue satura hospitales en el norte",
    pestel: "social",
    text: "Piura, Lambayeque y La Libertad concentran la mayoría de los casos tras las lluvias. Las empresas reportan ausentismo, los colegios suspenden actividades y las familias reducen salidas y gastos no esenciales.",
    industries: "all",
    effects: { wagePct: 2, regions: { norte: -10 } },
    rounds: 1,
    severity: 2,
    hint: "El Ministerio de Salud declara alerta epidemiológica por el aumento de casos de dengue después de las lluvias.",
    lesson:
      "La salud pública afecta la productividad y las ventas. Un plan simple (fumigación del local, reemplazos, turnos) reduce el ausentismo. Las alertas sanitarias son públicas y llegan semanas antes del pico.",
    basedOn: "Epidemias de dengue de 2023 y 2024 en el norte del Perú",
  },
  {
    id: "news-social-confianza-consumidor",
    title: "Confianza del consumidor cae a terreno pesimista",
    pestel: "social",
    text: "El índice de confianza retrocede por el temor a perder el empleo y por el alza del costo de vida. Las familias postergan la compra de bienes durables y comparan más precios antes de decidir.",
    industries: "all",
    effects: { demandPct: -4 },
    rounds: 2,
    severity: 1,
    hint: "Las encuestas mensuales de expectativas muestran que más familias creen que su situación económica empeorará.",
    lesson:
      "La demanda depende tanto del bolsillo como del ánimo. Los índices de confianza son un indicador adelantado: cuando caen, las ventas suelen seguirlos uno o dos trimestres después.",
  },
  {
    id: "news-social-clase-media",
    title: "La clase media se expande y estrena hábitos de consumo",
    pestel: "social",
    text: "Más familias acceden a crédito, educación superior, salidas a comer y a su primer auto o departamento. Los centros comerciales llegan a ciudades como Huancayo, Piura, Juliaca y Pucallpa.",
    industries: "all",
    effects: { demandPct: 5 },
    rounds: 3,
    severity: 1,
    hint: "Los estudios de niveles socioeconómicos muestran que el empleo formal y los ingresos crecen en las ciudades intermedias.",
    lesson:
      "Cuando los ingresos suben, el cliente busca mejor calidad y experiencia, no solo precio bajo. Es el momento de invertir en marca y de mirar las ciudades intermedias.",
    basedOn: "Expansión de la clase media peruana durante el auge económico de 2010 a 2013",
  },
  {
    id: "news-social-machu-picchu",
    title: "Protestas cortan el acceso a Machu Picchu en temporada alta",
    pestel: "social",
    text: "Un paro en el distrito de Machu Picchu suspendió el servicio de trenes y dejó turistas varados. Las agencias enfrentan cancelaciones masivas, devoluciones y reprogramaciones de paquetes al Cusco.",
    industries: ["turismo"],
    effects: { demandPct: -18, regions: { sur: -10 } },
    rounds: 1,
    severity: 3,
    hint: "Gremios de Machu Picchu Pueblo anuncian un paro indefinido por el nuevo sistema de venta de entradas.",
    lesson:
      "Un destino estrella concentra ingresos y también riesgo. Diversifica tu oferta con otros destinos, incluye cláusulas de reprogramación y responde rápido al cliente, que recordará cómo lo trataste en la crisis.",
    basedOn: "Paro en Machu Picchu de enero de 2024 por la venta de entradas",
  },

  // ───────────────────────── TECNOLÓGICO ─────────────────────────
  {
    id: "news-tecnologico-ecommerce-boom",
    title: "Las compras en línea se disparan y saturan el reparto a domicilio",
    pestel: "tecnologico",
    text: "Millones de consumidores compran por internet por primera vez. Las tiendas virtuales multiplican sus pedidos, los couriers amplían su flota y las empresas aceleran la contratación de software, conectividad y pasarelas de pago.",
    industries: ["ecommerce", "logistica", "software", "telecom"],
    effects: { demandPct: 20 },
    rounds: 2,
    severity: 3,
    hint: "Las pasarelas de pago reportan un crecimiento acelerado de compradores nuevos y los comercios tradicionales empiezan a abrir tiendas virtuales.",
    lesson:
      "Un salto de demanda también puede quebrar a una empresa que no cumple lo que promete. Crece cuidando tu capacidad de entrega y la satisfacción del cliente, porque los reclamos en redes y ante Indecopi destruyen marca.",
    basedOn: "Auge del comercio electrónico en Latinoamérica durante 2020",
  },
  {
    id: "news-tecnologico-billeteras",
    title: "Billeteras digitales ya operan entre sí y desplazan al efectivo",
    pestel: "tecnologico",
    text: "Los usuarios de distintas billeteras pueden enviarse dinero sin importar el banco. Bodegas, mercados, taxis y emprendedores aceptan pagos con código QR y reducen el manejo de efectivo.",
    industries: "all",
    effects: { demandPct: 3, costPct: -1 },
    rounds: 3,
    severity: 1,
    hint: "El BCRP publica el reglamento que obliga a las billeteras digitales a ser interoperables.",
    lesson:
      "Facilitar el pago aumenta las ventas. Cada medio de pago que no aceptas es un cliente que puede irse. Además, las ventas por billetera dejan registro y te ayudan a construir historial para acceder a crédito.",
    basedOn: "Interoperabilidad entre Yape y Plin iniciada en 2023",
  },
  {
    id: "news-tecnologico-ia-generativa",
    title: "Empresas adoptan inteligencia artificial y elevan su productividad",
    pestel: "tecnologico",
    text: "Las herramientas de inteligencia artificial generativa se masifican en empresas de todo tamaño. Se usan para redactar, analizar datos, atender consultas y programar, con ahorros de tiempo en las tareas repetitivas.",
    industries: "all",
    effects: { costPct: -4 },
    rounds: 3,
    severity: 1,
    hint: "Las grandes tecnológicas lanzan asistentes de inteligencia artificial de uso gratuito y las consultoras locales empiezan a ofrecer capacitación.",
    lesson:
      "La tecnología no reemplaza a la empresa, reemplaza a la empresa que no la usa. Capacitar a tu personal en nuevas herramientas es una inversión en eficiencia que tu competencia también está evaluando.",
    basedOn: "Masificación de la inteligencia artificial generativa desde 2023",
  },
  {
    id: "news-tecnologico-ransomware",
    title: "Ataques de secuestro de datos paralizan a empresas y entidades",
    pestel: "tecnologico",
    text: "Una ola de ataques informáticos cifra los sistemas de empresas y organismos públicos, que quedan varios días sin facturar ni atender. Las compañías aceleran el gasto en respaldos, seguros y seguridad informática.",
    industries: "all",
    effects: { demandPct: -3, costPct: 7 },
    rounds: 2,
    severity: 2,
    hint: "Los equipos de respuesta a incidentes informáticos de la región alertan sobre una banda que ataca a empresas medianas con sistemas sin actualizar.",
    lesson:
      "La ciberseguridad es gestión de riesgos, no un tema exclusivo del área de sistemas. Copias de respaldo probadas, accesos con doble factor y personal capacitado cuestan mucho menos que una semana sin operar.",
    basedOn: "Ataques de ransomware a entidades públicas de Costa Rica en 2022",
  },
  {
    id: "news-tecnologico-internet-regiones",
    title: "Internet de alta velocidad llega a más ciudades de la sierra y la selva",
    pestel: "tecnologico",
    text: "El despliegue de fibra óptica y la llegada del internet satelital mejoran la conexión en zonas antes aisladas. Negocios de Tarapoto, Pucallpa, Iquitos y Huancayo empiezan a vender en línea y a cobrar con medios digitales.",
    industries: "all",
    effects: { regions: { oriente: 5, centro: 3 } },
    rounds: 3,
    severity: 1,
    hint: "Los operadores anuncian inversiones en fibra óptica para ciudades intermedias y se autoriza el servicio de internet satelital.",
    lesson:
      "La conectividad abre mercados que antes eran caros de atender. Cuando una región se conecta, el costo de vender allí baja. Usa esa información al evaluar tu expansión regional.",
    basedOn: "Expansión de la fibra óptica y del internet satelital en Perú",
  },
  {
    id: "news-tecnologico-fraude-digital",
    title: "Fraudes digitales y suplantaciones crecen con los pagos en línea",
    pestel: "tecnologico",
    text: "Aumentan las denuncias por páginas falsas, comprobantes de pago adulterados y suplantación de marcas en redes sociales. Los consumidores desconfían de las tiendas poco conocidas y los comercios asumen contracargos.",
    industries: "all",
    effects: { demandPct: -2, costPct: 3 },
    rounds: 2,
    severity: 1,
    hint: "La policía y los gremios bancarios alertan sobre nuevas modalidades de estafa con comprobantes falsos de transferencia.",
    lesson:
      "La confianza es un activo. Verifica cada pago antes de entregar, protege tus cuentas oficiales y comunica con claridad tus canales de venta. Un cliente estafado con tu nombre también te culpa a ti.",
  },
  {
    id: "news-tecnologico-falla-global",
    title: "Falla informática mundial detiene vuelos, bancos y cajas registradoras",
    pestel: "tecnologico",
    text: "Una actualización defectuosa de un programa de seguridad dejó fuera de servicio millones de computadoras en el mundo. En la región se retrasaron vuelos, fallaron sistemas de cobro y varias empresas operaron a mano durante horas.",
    industries: "all",
    effects: { demandPct: -3 },
    rounds: 1,
    severity: 1,
    hint: "Especialistas advierten que muchas empresas dependen de un solo proveedor de software para toda su operación.",
    lesson:
      "Depender de un único proveedor tecnológico crea un punto único de falla. Ten un procedimiento manual de contingencia para vender y cobrar cuando el sistema se cae.",
    basedOn: "Falla informática global de julio de 2024",
  },
  {
    id: "news-tecnologico-tramites-digitales",
    title: "El Estado digitaliza trámites y reduce tiempos para las empresas",
    pestel: "tecnologico",
    text: "La constitución de empresas, la inscripción en registros públicos y varias licencias ya se gestionan en línea con firma electrónica. Las empresas ahorran horas de colas, mensajería y gestores.",
    industries: "all",
    effects: { costPct: -2 },
    rounds: 3,
    severity: 1,
    hint: "La Secretaría de Gobierno Digital anuncia nuevas plataformas para trámites en línea con firma electrónica.",
    lesson:
      "Menos trámites significa menos costo de ser formal. Aprovecha las herramientas digitales de SUNAT, SUNARP y las municipalidades, y dedica el tiempo ahorrado a vender.",
    basedOn: "Digitalización de trámites públicos acelerada desde 2020",
  },
  {
    id: "news-tecnologico-plataformas-asiaticas",
    title: "Plataformas asiáticas de venta directa inundan el mercado de ropa barata",
    pestel: "tecnologico",
    text: "Aplicaciones extranjeras envían prendas y accesorios desde la fábrica hasta la casa del cliente a precios muy bajos. Los comerciantes de Gamarra y las tiendas en línea locales reportan una fuerte caída de ventas.",
    industries: ["moda", "ecommerce"],
    effects: { demandPct: -16 },
    rounds: 3,
    severity: 3,
    hint: "Las aplicaciones asiáticas de compras encabezan los rankings de descargas en la región.",
    lesson:
      "No puedes ganar una guerra de precios contra quien tiene escala global. Compite donde el rival es débil: entrega inmediata, cambios y devoluciones, tallas locales, diseño propio y atención cercana.",
    basedOn: "Expansión de plataformas asiáticas de comercio electrónico en Latinoamérica desde 2023",
  },
  {
    id: "news-tecnologico-autos-electrificados",
    title: "Nuevas marcas de autos híbridos y eléctricos llegan con precios bajos",
    pestel: "tecnologico",
    text: "Fabricantes asiáticos ingresan al mercado con modelos híbridos y eléctricos bien equipados y a precios competitivos. Los compradores vuelven a las salas de exhibición y las concesionarias amplían su portafolio.",
    industries: ["autos"],
    effects: { demandPct: 8, costPct: -4 },
    rounds: 3,
    severity: 2,
    hint: "Varias marcas asiáticas anuncian su llegada al país y se discuten incentivos para los vehículos electrificados.",
    lesson:
      "Un cambio tecnológico reordena el mercado y quien se aferra al portafolio antiguo pierde cuota. Evalúa nuevas líneas con la matriz BCG: los productos estrella de mañana hoy parecen una apuesta.",
    basedOn: "Ingreso de marcas chinas de autos a Perú y Latinoamérica",
  },
  {
    id: "news-tecnologico-escasez-chips",
    title: "Escasez mundial de chips deja sin stock a concesionarias y tiendas",
    pestel: "tecnologico",
    text: "Las fábricas de semiconductores no alcanzan a cubrir la demanda global. Los autos, celulares y equipos industriales llegan con meses de retraso y a mayor precio, y los clientes entran en listas de espera.",
    industries: ["autos", "telecom", "maquinaria"],
    effects: { demandPct: -5, costPct: 9 },
    rounds: 3,
    severity: 2,
    hint: "Los fabricantes de autos anuncian recortes de producción por falta de semiconductores.",
    lesson:
      "Un componente pequeño puede detener toda una industria. Conoce los insumos críticos de tus proveedores y, cuando veas señales de escasez, asegura inventario antes que tus competidores.",
    basedOn: "Escasez mundial de semiconductores de 2021",
  },
  {
    id: "news-tecnologico-delivery-apps",
    title: "Aplicaciones de reparto amplían cobertura a más distritos y ciudades",
    pestel: "tecnologico",
    text: "Las plataformas de delivery suman repartidores y llegan a nuevas zonas de Lima, Arequipa, Trujillo y Piura. Restaurantes, pastelerías, boticas y minimarkets reciben pedidos de clientes que antes no los conocían.",
    industries: ["restaurante", "pasteleria", "cafeteria", "farmacia", "minimarket"],
    effects: { demandPct: 8, costPct: 2 },
    rounds: 2,
    severity: 2,
    hint: "Las aplicaciones de reparto anuncian su expansión a nuevas ciudades y campañas de envío gratis.",
    lesson:
      "Un canal nuevo trae ventas, pero también comisiones. Calcula tu margen por pedido con la comisión incluida y decide qué productos ofreces por aplicación y cuáles por tu canal propio.",
  },
  {
    id: "news-tecnologico-privacidad-anuncios",
    title: "Cambios de privacidad en celulares encarecen la publicidad digital",
    pestel: "tecnologico",
    text: "Los sistemas operativos móviles ahora piden permiso al usuario antes de rastrear su actividad. Las campañas en redes sociales pierden precisión, el costo por cada venta atribuida sube y los anunciantes revisan sus presupuestos.",
    industries: ["agencia", "ecommerce"],
    effects: { costPct: 8 },
    rounds: 2,
    severity: 2,
    hint: "Un fabricante de celulares anuncia que su próxima actualización limitará el seguimiento publicitario entre aplicaciones.",
    lesson:
      "No construyas tu negocio sobre una plataforma que no controlas. Desarrolla tus propios datos (lista de clientes, correo, WhatsApp con permiso del usuario) y diversifica tus canales de marketing.",
    basedOn: "Cambios de privacidad en sistemas operativos móviles de 2021",
  },
  {
    id: "news-tecnologico-agrotech",
    title: "Riego tecnificado y sensores reducen costos en el agro",
    pestel: "tecnologico",
    text: "Las agroexportadoras adoptan riego por goteo automatizado, drones e imágenes satelitales para decidir cuándo regar y fertilizar. Los fundos reportan menor consumo de agua y de fertilizantes por hectárea.",
    industries: ["agroexport"],
    effects: { costPct: -5 },
    rounds: 3,
    severity: 1,
    hint: "Proveedores de tecnología agrícola presentan en las ferias del sector equipos de monitoreo a precios más accesibles.",
    lesson:
      "La inversión en eficiencia de procesos baja el costo unitario de forma duradera y te protege cuando los precios caen. Evalúala comparando el ahorro con su costo y su periodo de recuperación.",
  },

  // ───────────────────────── AMBIENTAL ─────────────────────────
  {
    id: "news-ambiental-nino-costero",
    title: "Niño costero: lluvias y huaicos destruyen carreteras en el norte",
    pestel: "ambiental",
    text: "Las lluvias extremas desbordan ríos en Piura, Lambayeque y La Libertad, y los huaicos cortan la Panamericana Norte. Hay desabastecimiento, locales inundados y el precio de los alimentos sube en todo el país.",
    industries: "all",
    effects: { demandPct: -5, costPct: 8, regions: { norte: -28 } },
    rounds: 2,
    severity: 3,
    hint: "El Senamhi eleva la alerta por calentamiento del mar frente a Piura.",
    lesson:
      "El Fenómeno del Niño es recurrente y se anuncia con meses de anticipación. Revisa el estado de alerta oficial, asegura tus locales e inventario, y no concentres tu stock en zonas inundables.",
    basedOn: "Fenómeno del Niño costero de 2017",
  },
  {
    id: "news-ambiental-racionamiento",
    title: "Sequía reduce la generación hidroeléctrica y obliga a cortes de luz",
    pestel: "ambiental",
    text: "Los embalses están en mínimos y el sistema eléctrico programa cortes de varias horas al día. Fábricas, comercios y oficinas paran o recurren a grupos electrógenos, con un fuerte aumento de sus costos.",
    industries: "all",
    effects: { demandPct: -16, costPct: 12 },
    rounds: 2,
    severity: 3,
    hint: "El operador del sistema eléctrico advierte que el nivel de los embalses está muy por debajo de su promedio histórico.",
    lesson:
      "La energía es un insumo que se da por sentado hasta que falta. Identifica tus procesos críticos, evalúa un respaldo eléctrico y calcula cuánto te cuesta cada hora sin operar.",
    basedOn: "Crisis eléctrica de Ecuador de 2024 por la sequía",
  },
  {
    id: "news-ambiental-sequia-sur",
    title: "Sequía en el altiplano reduce cosechas y golpea el comercio del sur",
    pestel: "ambiental",
    text: "La falta de lluvias afecta los cultivos de papa y quinua y los pastos en Puno, Cusco y Arequipa. Las familias del campo pierden ingresos, compran menos en las ciudades y algunos alimentos suben de precio.",
    industries: "all",
    effects: { costPct: 4, regions: { sur: -10 } },
    rounds: 2,
    severity: 2,
    hint: "El Senamhi reporta un déficit de lluvias en la sierra sur al inicio de la campaña agrícola.",
    lesson:
      "En las regiones donde el agro sostiene el ingreso de las familias, el clima define el consumo. Antes de expandirte a una región, entiende de qué vive su gente.",
    basedOn: "Sequía en la sierra sur del Perú entre 2022 y 2023",
  },
  {
    id: "news-ambiental-friaje",
    title: "Heladas y friaje bajan la afluencia a comercios del sur",
    pestel: "ambiental",
    text: "Las temperaturas bajo cero en las zonas altas de Puno, Cusco y Arequipa afectan la salud, el ganado y el tránsito. Los colegios modifican horarios y los negocios registran menos público en las primeras y últimas horas del día.",
    industries: "all",
    effects: { regions: { sur: -5 } },
    rounds: 1,
    severity: 1,
    hint: "El Senamhi emite un aviso por descenso de la temperatura nocturna en la sierra sur.",
    lesson:
      "Las heladas llegan todos los años en los meses de invierno. Un evento estacional no es sorpresa: ajusta horarios, surtido y personal según la temporada de cada región.",
    basedOn: "Temporadas de heladas y friaje en la sierra sur del Perú",
  },
  {
    id: "news-ambiental-incendios",
    title: "Incendios forestales afectan a regiones de la sierra y la selva",
    pestel: "ambiental",
    text: "El fuego, avivado por la sequía y las quemas agrícolas, arrasa cultivos y bosques. El humo obliga a suspender vuelos y actividades en varias ciudades de la Amazonía y de la sierra central.",
    industries: "all",
    effects: { regions: { oriente: -5, centro: -4 } },
    rounds: 1,
    severity: 1,
    hint: "Las autoridades reportan un número inusual de focos de calor en la Amazonía al final de la temporada seca.",
    lesson:
      "Los riesgos ambientales también afectan a empresas que no son del agro, porque cortan rutas, vuelos y ventas. Incluye los eventos climáticos en el análisis PESTEL de cada región donde operas.",
    basedOn: "Incendios forestales de 2024 en la sierra y selva del Perú",
  },
  {
    id: "news-ambiental-renovables",
    title: "Centrales solares y eólicas abaratan el precio de la energía",
    pestel: "ambiental",
    text: "La entrada en operación de parques solares y eólicos aumenta la oferta de electricidad. Las empresas que negocian su suministro consiguen mejores tarifas y algunas instalan paneles propios.",
    industries: "all",
    effects: { costPct: -3 },
    rounds: 3,
    severity: 1,
    hint: "Se adjudican nuevos proyectos de energía solar y eólica que entrarán en operación en los próximos meses.",
    lesson:
      "La sostenibilidad también es una decisión de costos. Medir tu consumo de energía y buscar fuentes más eficientes mejora tu margen y tu imagen ante clientes que ya lo exigen.",
    basedOn: "Ingreso de centrales solares y eólicas en Perú",
  },
  {
    id: "news-ambiental-vaciante",
    title: "Vaciante histórica de los ríos amazónicos encarece el abastecimiento",
    pestel: "ambiental",
    text: "El bajo nivel de los ríos impide la navegación de embarcaciones de carga hacia Iquitos, Pucallpa y otras ciudades. Los productos tardan más en llegar, suben los fletes fluviales y el comercio local se resiente.",
    industries: "all",
    effects: { costPct: 3, regions: { oriente: -10 } },
    rounds: 2,
    severity: 2,
    hint: "El servicio de hidrografía reporta que los ríos amazónicos descienden más rápido de lo normal para la época.",
    lesson:
      "En la Amazonía el río es la carretera. Conocer la temporada de creciente y vaciante permite adelantar compras y evitar quedarse sin mercadería o pagar fletes de emergencia.",
    basedOn: "Vaciante histórica de los ríos amazónicos en 2023 y 2024",
  },
  {
    id: "news-ambiental-buen-anio-agricola",
    title: "Lluvias normales aseguran una buena campaña agrícola",
    pestel: "ambiental",
    text: "Los reservorios están llenos y el clima acompaña las siembras. Los mercados mayoristas reciben más papa, verduras, frutas y granos, y los precios de los alimentos retroceden.",
    industries: ["restaurante", "pasteleria", "cafeteria", "minimarket", "bebidas", "agroexport"],
    effects: { costPct: -8 },
    rounds: 2,
    severity: 2,
    hint: "El Senamhi descarta el Fenómeno del Niño para este verano y los reservorios del norte y del sur alcanzan niveles altos.",
    lesson:
      "Un costo que baja exige una decisión estratégica: puedes mejorar tu margen, bajar precios para ganar cuota o invertir la diferencia en calidad y marca. Decide con un plan, no por inercia.",
  },
  {
    id: "news-ambiental-verano-caluroso",
    title: "Verano con temperaturas récord eleva la venta de bebidas y helados",
    pestel: "ambiental",
    text: "La costa registra las temperaturas más altas en años. Las bodegas agotan agua, jugos y hielo, las cafeterías venden más bebidas frías y las agencias reportan mayor demanda de paquetes a playas.",
    industries: ["bebidas", "minimarket", "cafeteria", "turismo"],
    effects: { demandPct: 10 },
    rounds: 1,
    severity: 2,
    hint: "El Senamhi pronostica un verano con temperaturas por encima de lo normal en toda la costa.",
    lesson:
      "La estacionalidad se planifica. Si sabes que viene un verano fuerte, asegura producción, frío y distribución antes de diciembre. El que se queda sin stock en el pico le regala clientes a la competencia.",
  },
  {
    id: "news-ambiental-gripe-aviar",
    title: "Brote de gripe aviar reduce la oferta de pollo y huevos",
    pestel: "ambiental",
    text: "Senasa declaró la alerta sanitaria tras detectar casos en granjas. El sacrificio de aves y las restricciones de traslado reducen la oferta, y los precios del pollo y del huevo suben en los mercados.",
    industries: ["restaurante", "pasteleria", "minimarket"],
    effects: { costPct: 9 },
    rounds: 2,
    severity: 2,
    hint: "Senasa confirma casos de influenza aviar en aves silvestres del litoral y refuerza la vigilancia en las granjas.",
    lesson:
      "Las alertas sanitarias de Senasa son señales tempranas para quien compra alimentos. Ten proveedores alternativos y piensa qué productos de tu carta pueden reemplazar al insumo escaso.",
    basedOn: "Brotes de influenza aviar en Perú entre 2022 y 2023",
  },
  {
    id: "news-ambiental-campana-frutas",
    title: "Clima favorable impulsa una campaña récord de frutas de exportación",
    pestel: "ambiental",
    text: "Las temperaturas adecuadas permiten una floración abundante de arándano, uva y palta. Los envíos superan los de la campaña anterior y los compradores del exterior cierran contratos por mayores volúmenes.",
    industries: ["agroexport", "logistica"],
    effects: { demandPct: 12 },
    rounds: 2,
    severity: 2,
    hint: "Los gremios agroexportadores proyectan mayores volúmenes por las buenas condiciones de floración.",
    lesson:
      "En un buen año todos producen más y el precio internacional puede caer. Cierra contratos con anticipación, cuida la calidad y asegura frío y fletes antes del pico de cosecha.",
    basedOn: "Crecimiento de las exportaciones peruanas de arándano, uva y palta",
  },
  {
    id: "news-ambiental-bono-verde",
    title: "Compradores prefieren viviendas sostenibles con bono y mejor tasa",
    pestel: "ambiental",
    text: "Los proyectos certificados por su ahorro de agua y energía acceden a un bono adicional y a tasas preferenciales. Las inmobiliarias reportan que los departamentos sostenibles se venden más rápido.",
    industries: ["inmobiliaria"],
    effects: { demandPct: 5, ratePts: -0.5 },
    rounds: 3,
    severity: 1,
    hint: "El Fondo Mivivienda anuncia más recursos para el bono a viviendas sostenibles.",
    lesson:
      "La sostenibilidad puede ser una ventaja competitiva que el cliente valora y el Estado premia. Invertir en calidad y certificaciones abre acceso a incentivos que tu competencia no tiene.",
    basedOn: "Bono Mivivienda Verde para viviendas sostenibles",
  },
  {
    id: "news-ambiental-invierno-frio",
    title: "Invierno más frío de lo habitual adelanta la compra de abrigo",
    pestel: "ambiental",
    text: "Lima y la costa registran temperaturas por debajo de su promedio. Las tiendas de ropa venden casacas y chompas desde el inicio de la temporada, y las boticas reportan mayor demanda de antigripales.",
    industries: ["moda", "farmacia"],
    effects: { demandPct: 6 },
    rounds: 1,
    severity: 1,
    hint: "El Senamhi pronostica un invierno con temperaturas por debajo de lo normal en la costa central.",
    lesson:
      "El pronóstico del clima es un insumo para tus compras. En moda, acertar la temporada evita rematar inventario. Compra con información y no solo con la experiencia del año pasado.",
  },
  {
    id: "news-ambiental-derrame",
    title: "Derrame de petróleo cierra playas y golpea al turismo costero",
    pestel: "ambiental",
    text: "Un derrame de crudo contamina varias playas del litoral en plena temporada de verano. Se prohíbe el ingreso de bañistas y la pesca artesanal, y los restaurantes y operadores turísticos de la zona pierden a sus clientes.",
    industries: ["turismo", "restaurante"],
    effects: { demandPct: -2, regions: { lima: -4 } },
    rounds: 2,
    severity: 1,
    hint: "Pescadores artesanales reportan manchas de hidrocarburo cerca de una zona de descarga de buques.",
    lesson:
      "Un desastre ambiental causado por terceros también puede dejarte sin ventas. Conoce los riesgos de tu zona y evita depender de un solo local o de una sola temporada.",
    basedOn: "Derrame de petróleo en el mar de Ventanilla de enero de 2022",
  },

  // ───────────────────────── LEGAL ─────────────────────────
  {
    id: "news-legal-rmv",
    title: "Gobierno eleva la remuneración mínima vital",
    pestel: "legal",
    text: "El Ejecutivo oficializó el aumento del sueldo mínimo tras el diálogo con gremios y sindicatos. El alza se traslada a gratificaciones, CTS y aportes a EsSalud, y presiona las escalas salariales cercanas al mínimo.",
    industries: "all",
    effects: { demandPct: 2, wagePct: 7 },
    rounds: 3,
    severity: 2,
    hint: "El Consejo Nacional de Trabajo retoma el debate sobre el aumento de la remuneración mínima.",
    lesson:
      "Un alza del sueldo mínimo sube tu planilla y sus costos asociados (EsSalud de 9 %, gratificaciones, CTS), pero también pone más dinero en el bolsillo de tus clientes. Calcula el costo total de cada trabajador, no solo su sueldo.",
    basedOn: "Aumentos de la remuneración mínima vital en Perú de 2022 y 2025",
  },
  {
    id: "news-legal-datos-personales",
    title: "Nuevo reglamento de datos personales eleva exigencias a las empresas",
    pestel: "legal",
    text: "La norma obliga a informar con claridad el uso de los datos de los clientes, a reportar incidentes de seguridad y, en ciertos casos, a designar un oficial de datos. La autoridad anuncia fiscalizaciones y multas.",
    industries: "all",
    effects: { costPct: 2 },
    rounds: 2,
    severity: 1,
    hint: "El Ministerio de Justicia prepublica el nuevo reglamento de la Ley de Protección de Datos Personales.",
    lesson:
      "Las bases de datos de clientes son un activo y una responsabilidad. Pide consentimiento, guarda solo lo necesario y protege la información. Las normas se prepublican y quien las lee se adapta antes.",
    basedOn: "Nuevo reglamento de la Ley de Protección de Datos Personales en Perú",
  },
  {
    id: "news-legal-mype-tributario",
    title: "Nuevo régimen tributario alivia la carga de las pequeñas empresas",
    pestel: "legal",
    text: "El régimen permite a las micro y pequeñas empresas pagar una tasa reducida de impuesto a la renta sobre el primer tramo de sus utilidades y llevar una contabilidad más simple. SUNAT espera que más negocios se formalicen.",
    industries: "all",
    effects: { costPct: -2 },
    rounds: 3,
    severity: 1,
    hint: "El Ejecutivo recibe facultades para legislar en materia tributaria y anuncia un régimen especial para las mypes.",
    lesson:
      "Elegir bien tu régimen tributario es una decisión financiera. En el Régimen MYPE Tributario la tasa es de 10 % hasta 15 UIT de renta neta y de 29.5 % por el exceso. Revisa cada año con tu contador cuál te conviene.",
    basedOn: "Creación del Régimen MYPE Tributario en Perú",
  },
  {
    id: "news-legal-licencias",
    title: "Municipalidades simplifican la licencia de funcionamiento",
    pestel: "legal",
    text: "La nueva norma estandariza requisitos y plazos, y agiliza la aprobación para los negocios de menor riesgo. Abrir un local nuevo toma menos tiempo y menos gasto en trámites.",
    industries: "all",
    effects: { costPct: -2 },
    rounds: 2,
    severity: 1,
    hint: "La Presidencia del Consejo de Ministros anuncia un paquete de simplificación administrativa para las municipalidades.",
    lesson:
      "Las barreras burocráticas frenan la expansión y, cuando se reducen, abrir locales es más rápido. Si una municipalidad te exige requisitos que la ley no contempla, puedes denunciarlo ante Indecopi.",
    basedOn: "Simplificación de la licencia de funcionamiento en Perú",
  },
  {
    id: "news-legal-comprobante-electronico",
    title: "SUNAT completa la obligatoriedad del comprobante electrónico",
    pestel: "legal",
    text: "Los últimos grupos de contribuyentes pasan a emitir facturas y boletas electrónicas. Las empresas dejan el papel, ahorran en imprenta y archivo, y cuentan con información de ventas al día para gestionar mejor.",
    industries: "all",
    effects: { costPct: -1.5 },
    rounds: 2,
    severity: 1,
    hint: "SUNAT publica el cronograma con los últimos grupos de contribuyentes obligados a emitir comprobantes electrónicos.",
    lesson:
      "La formalización digital hace visible cada venta ante SUNAT y también ante ti. Usa esa información para analizar tus ventas por producto y por cliente, y sustenta bien tu crédito fiscal del IGV.",
    basedOn: "Masificación de los comprobantes de pago electrónicos en Perú",
  },
  {
    id: "news-legal-nuevo-feriado",
    title: "Congreso aprueba un nuevo feriado nacional",
    pestel: "legal",
    text: "La ley agrega un día de descanso remunerado al calendario. Los gremios empresariales advierten menos días de producción y un mayor costo por el pago especial a quienes trabajen ese día.",
    industries: "all",
    effects: { wagePct: 1.5 },
    rounds: 1,
    severity: 1,
    hint: "Una comisión del Congreso aprueba el dictamen que declara feriado nacional una fecha conmemorativa.",
    lesson:
      "Trabajar en feriado tiene un costo especial para el empleador. Planifica turnos y producción con el calendario oficial, y evalúa si abrir ese día te deja margen o solo gasto.",
    basedOn: "Nuevos feriados nacionales aprobados en Perú desde 2021",
  },
  {
    id: "news-legal-tercerizacion",
    title: "Norma restringe la tercerización de actividades del negocio principal",
    pestel: "legal",
    text: "El decreto prohíbe tercerizar las actividades que forman parte del núcleo del negocio. Las empresas contratistas revisan sus contratos y varios clientes evalúan incorporar personal a su propia planilla.",
    industries: ["limpieza", "logistica", "consultoria", "maquinaria"],
    effects: { demandPct: -8, wagePct: 4 },
    rounds: 2,
    severity: 2,
    hint: "El Ministerio de Trabajo anuncia cambios al reglamento de la ley de tercerización.",
    lesson:
      "Si tu modelo de negocio depende de una figura legal, un cambio normativo puede transformarlo. Sigue las prepublicaciones, participa en tu gremio y ofrece servicios especializados que sean difíciles de reemplazar.",
    basedOn: "Restricciones a la tercerización laboral aprobadas en Perú en 2022",
  },
  {
    id: "news-legal-isc-autos",
    title: "Sube el impuesto selectivo a los vehículos nuevos",
    pestel: "legal",
    text: "El Ministerio de Economía elevó el impuesto selectivo al consumo de los autos nuevos a gasolina y diésel. Las concesionarias trasladan el alza a sus precios y las ventas se enfrían tras un adelanto de compras.",
    industries: ["autos"],
    effects: { demandPct: -12, costPct: 5 },
    rounds: 2,
    severity: 2,
    hint: "El Ministerio de Economía evalúa modificar el impuesto selectivo para desincentivar los vehículos más contaminantes.",
    lesson:
      "Un impuesto al consumo eleva el precio final y reduce la cantidad demandada, sobre todo en bienes caros. Mide la sensibilidad al precio de tu cliente antes de decidir cuánto del impuesto trasladas.",
    basedOn: "Alza del impuesto selectivo al consumo a vehículos nuevos en 2018",
  },
  {
    id: "news-legal-vivienda-social",
    title: "Disputa por normas de altura paraliza licencias de edificios",
    pestel: "legal",
    text: "Municipalidades y Gobierno central discrepan sobre las reglas para construir vivienda de interés social. Varias licencias quedan en revisión, los bancos frenan desembolsos y los compradores dudan antes de separar.",
    industries: ["inmobiliaria"],
    effects: { demandPct: -18 },
    rounds: 3,
    severity: 3,
    hint: "Alcaldes distritales anuncian que acudirán a la justicia contra las normas que permiten edificios más altos en sus distritos.",
    lesson:
      "La seguridad jurídica vale tanto como el terreno. Antes de comprar un lote para construir, verifica zonificación, parámetros y posibles disputas. Un proyecto detenido sigue pagando intereses.",
    basedOn: "Controversia por las normas de vivienda de interés social en distritos de Lima",
  },
  {
    id: "news-legal-licenciamiento",
    title: "Cierre de instituciones sin licencia traslada alumnos a las licenciadas",
    pestel: "legal",
    text: "La autoridad educativa denegó la licencia a instituciones que no cumplían las condiciones básicas de calidad. Miles de estudiantes buscan trasladarse y las instituciones licenciadas reciben más postulantes, aunque deben sostener estándares más exigentes.",
    industries: ["educacion"],
    effects: { demandPct: 16, costPct: 4 },
    rounds: 3,
    severity: 3,
    hint: "La autoridad educativa publica la lista de instituciones con licencia denegada y el plazo para su cese de actividades.",
    lesson:
      "La regulación de calidad castiga a quien no invirtió y premia a quien sí. La inversión en calidad parece un gasto hasta que se convierte en la condición para seguir operando.",
    basedOn: "Proceso de licenciamiento de universidades e institutos en Perú",
  },
  {
    id: "news-legal-contrataciones",
    title: "Nueva ley de contrataciones públicas agiliza las compras del Estado",
    pestel: "legal",
    text: "La norma introduce nuevos procedimientos de selección y busca reducir los plazos de contratación. Las entidades relanzan convocatorias de servicios, equipos y consultorías que estaban en espera.",
    industries: ["limpieza", "consultoria", "maquinaria", "software"],
    effects: { demandPct: 8 },
    rounds: 2,
    severity: 2,
    hint: "Se publica el reglamento de la nueva ley de contrataciones públicas y las entidades capacitan a sus áreas de logística.",
    lesson:
      "Venderle al Estado exige conocer las reglas. Mantén vigente tu inscripción en el registro de proveedores, evita sanciones y estudia las bases. Una propuesta descalificada por un error formal no vende.",
    basedOn: "Nueva Ley General de Contrataciones Públicas de Perú",
  },
  {
    id: "news-legal-factoring",
    title: "Norma impulsa el factoring y acorta el cobro de facturas",
    pestel: "legal",
    text: "La regulación facilita que las empresas proveedoras negocien sus facturas y reciban el dinero antes del vencimiento. Se acorta el plazo para dar conformidad a las facturas y más entidades financieras ofrecen el servicio.",
    industries: ["consultoria", "agencia", "limpieza", "logistica", "maquinaria", "software"],
    effects: { ratePts: -1 },
    rounds: 3,
    severity: 1,
    hint: "El Ministerio de la Producción anuncia medidas para que las mypes proveedoras cobren sus facturas en menos tiempo.",
    lesson:
      "Vender no es lo mismo que cobrar. En negocios B2B el plazo de cobro define tu necesidad de capital de trabajo. El factoring convierte facturas en caja a cambio de un descuento: compáralo con el costo de un préstamo.",
    basedOn: "Promoción del factoring en Perú y ley de pago a 30 días de Chile",
  },
  {
    id: "news-legal-octogonos",
    title: "Entran en vigencia los octógonos de advertencia en alimentos",
    pestel: "legal",
    text: "Los productos procesados altos en azúcar, sodio o grasas saturadas deben llevar octógonos en su etiqueta. Los fabricantes reformulan recetas y cambian empaques, y parte de los consumidores modifica su compra.",
    industries: ["bebidas", "pasteleria", "minimarket"],
    effects: { demandPct: -4, costPct: 3 },
    rounds: 2,
    severity: 1,
    hint: "El Ministerio de Salud aprueba el manual de advertencias publicitarias y fija el plazo de adecuación.",
    lesson:
      "Una regulación con plazo de adecuación da tiempo para actuar. Reformular el producto antes de la vigencia puede convertir una amenaza en ventaja frente a los competidores que esperaron.",
    basedOn: "Octógonos de advertencia en alimentos procesados desde 2019",
  },
  {
    id: "news-legal-regimen-agrario",
    title: "Nuevo régimen laboral agrario eleva el costo de la planilla",
    pestel: "legal",
    text: "Tras la derogatoria de la ley de promoción agraria, el Congreso aprobó un nuevo régimen con un bono adicional para los trabajadores del campo y una mayor participación en las utilidades.",
    industries: ["agroexport"],
    effects: { wagePct: 12 },
    rounds: 3,
    severity: 2,
    hint: "El Congreso deroga la ley de promoción agraria y se compromete a aprobar un nuevo régimen en pocas semanas.",
    lesson:
      "Los regímenes especiales no son eternos. Si tu rentabilidad depende de un beneficio legal, calcula tus números sin él e invierte en productividad para sostener mejores salarios.",
    basedOn: "Nueva ley del régimen laboral agrario aprobada en Perú a fines de 2020",
  },
];

export default data;
