import type { TriviaQ } from "../types";

/**
 * Banco B de trivia: marketing, investigación de mercados, estrategia, ventas y emprendimiento.
 * 30 preguntas por tema: 10 de nivel 1, 12 de nivel 2 y 8 de nivel 3.
 */
const data: TriviaQ[] = [
  // marketing
  {
    id: "tq-marketing-01",
    topic: "marketing",
    level: 1,
    q: "Una academia de Huancayo divide a sus posibles alumnos en escolares de quinto de secundaria, egresados y trabajadores que estudian de noche, y prepara una oferta para cada grupo. ¿Qué está haciendo?",
    options: [
      "Posicionamiento de marca",
      "Segmentación de mercado",
      "Venta cruzada",
      "Diversificación",
    ],
    answer: 1,
    explain: "Segmentar es dividir el mercado en grupos con necesidades parecidas para atender a cada uno con una oferta adecuada. El posicionamiento viene después, cuando decides cómo quieres que te perciba el grupo elegido.",
  },
  {
    id: "tq-marketing-02",
    topic: "marketing",
    level: 1,
    q: "Una pollería de Trujillo quiere que la gente la recuerde como «la que entrega en 20 minutos». ¿Qué concepto de marketing está trabajando?",
    options: [
      "Posicionamiento",
      "Segmentación",
      "Penetración de mercado",
      "Elasticidad precio",
    ],
    answer: 0,
    explain: "El posicionamiento es el lugar que ocupa la marca en la mente del cliente frente a la competencia. Aquí la pollería busca ser recordada por un atributo concreto: la rapidez.",
  },
  {
    id: "tq-marketing-03",
    topic: "marketing",
    level: 1,
    q: "Una marca de bebidas naturales de Tarapoto decide vender en bodegas y ya no solo en ferias. ¿Qué variable de la mezcla de marketing está cambiando?",
    options: [
      "Producto",
      "Precio",
      "Promoción",
      "Plaza (distribución)",
    ],
    answer: 3,
    explain: "La plaza o distribución define dónde y por qué canales llega el producto al cliente. Pasar de ferias a bodegas cambia el canal, no el producto ni el precio.",
  },
  {
    id: "tq-marketing-04",
    topic: "marketing",
    level: 1,
    q: "Una persona de Arequipa ve por primera vez el anuncio de un gimnasio nuevo que no conocía. ¿En qué etapa del embudo de marketing se encuentra?",
    options: [
      "Consideración",
      "Compra",
      "Conocimiento (descubrimiento)",
      "Fidelización",
    ],
    answer: 2,
    explain: "El embudo empieza por el conocimiento: la persona recién se entera de que la marca existe. Luego vienen la consideración, la compra y la fidelización.",
  },
  {
    id: "tq-marketing-05",
    topic: "marketing",
    level: 1,
    q: "El dueño de una botica de Chiclayo quiere saber cuánto le cuesta en promedio conseguir cada cliente nuevo con su publicidad. ¿Qué indicador debe calcular?",
    options: [
      "LTV",
      "ROAS",
      "CTR",
      "CAC",
    ],
    answer: 3,
    explain: "El CAC (costo de adquisición de cliente) divide lo invertido en marketing y ventas entre los clientes nuevos conseguidos.",
  },
  {
    id: "tq-marketing-06",
    topic: "marketing",
    level: 1,
    q: "Una cafetería de Cusco estima cuánto dinero le deja un cliente frecuente durante todo el tiempo que le sigue comprando. ¿Cómo se llama ese indicador?",
    options: [
      "Valor de vida del cliente (LTV)",
      "Costo de adquisición (CAC)",
      "Retorno de la inversión publicitaria (ROAS)",
      "Ticket promedio",
    ],
    answer: 0,
    explain: "El valor de vida del cliente (LTV) suma lo que un cliente deja a la empresa durante toda la relación. Sirve para saber cuánto puedes gastar en conseguirlo y retenerlo.",
  },
  {
    id: "tq-marketing-07",
    topic: "marketing",
    level: 1,
    q: "Las ventas de un modelo de celular crecieron varios años, se estancaron y ahora caen cada trimestre mientras salen modelos que lo reemplazan. ¿En qué etapa del ciclo de vida está?",
    options: [
      "Introducción",
      "Crecimiento",
      "Declive",
      "Madurez",
    ],
    answer: 2,
    explain: "Cuando las ventas caen de forma sostenida y el producto es reemplazado por otros, está en declive. En la madurez las ventas se estancan, pero todavía no caen.",
  },
  {
    id: "tq-marketing-08",
    topic: "marketing",
    level: 1,
    q: "Una pastelería de Piura cobra más que sus vecinas por una torta parecida y aun así vende más, porque la gente confía en su nombre. ¿Qué explica esa diferencia?",
    options: [
      "Las economías de escala",
      "El valor de marca",
      "La elasticidad precio",
      "El canal de distribución",
    ],
    answer: 1,
    explain: "El valor de marca permite cobrar más y vender más por la confianza y preferencia que genera el nombre, aunque el producto sea parecido al de otros.",
  },
  {
    id: "tq-marketing-09",
    topic: "marketing",
    level: 1,
    q: "Una bodega de Iquitos sube 10 % el precio de la sal y casi no pierde ventas. ¿Cómo es la demanda de ese producto frente al precio?",
    options: [
      "Inelástica",
      "Elástica",
      "Unitaria",
      "Estacional",
    ],
    answer: 0,
    explain: "La demanda es inelástica cuando la cantidad vendida cambia poco ante un cambio de precio. Pasa con productos básicos y sin sustitutos cercanos, como la sal.",
  },
  {
    id: "tq-marketing-10",
    topic: "marketing",
    level: 1,
    q: "De cada 100 personas que entran a la web de una agencia de turismo de Cusco, 3 compran un paquete. ¿Qué indicador describe ese 3 %?",
    options: [
      "Tasa de rebote",
      "CTR",
      "ROAS",
      "Tasa de conversión",
    ],
    answer: 3,
    explain: "La tasa de conversión es el porcentaje de visitantes que realiza la acción buscada, en este caso comprar: 3 de 100 es 3 %.",
  },
  {
    id: "tq-marketing-11",
    topic: "marketing",
    level: 2,
    q: "Una tienda de Gamarra invierte S/ 2,000 en anuncios y consigue 50 clientes nuevos. ¿Cuál es su costo de adquisición por cliente (CAC)?",
    options: [
      "S/ 25",
      "S/ 40",
      "S/ 100",
      "S/ 400",
    ],
    answer: 1,
    explain: "CAC = inversión entre clientes nuevos: 2,000 / 50 = S/ 40 por cliente.",
  },
  {
    id: "tq-marketing-12",
    topic: "marketing",
    level: 2,
    q: "Una tienda en línea de Lima gasta S/ 1,000 en anuncios durante el Cyber Wow y esos anuncios generan ventas por S/ 4,000. ¿Cuál es el ROAS?",
    options: [
      "4",
      "3",
      "0.25",
      "40 %",
    ],
    answer: 0,
    explain: "ROAS = ventas atribuidas a los anuncios entre la inversión: 4,000 / 1,000 = 4. El 3 aparece cuando restas la inversión a las ventas antes de dividir, que es otro cálculo.",
  },
  {
    id: "tq-marketing-13",
    topic: "marketing",
    level: 2,
    q: "El anuncio de una tienda de zapatillas de Lima se mostró 10,000 veces y recibió 200 clics. ¿Cuál es su CTR?",
    options: [
      "0.2 %",
      "5 %",
      "2 %",
      "20 %",
    ],
    answer: 2,
    explain: "CTR = clics entre impresiones: 200 / 10,000 = 0.02, es decir 2 %.",
  },
  {
    id: "tq-marketing-14",
    topic: "marketing",
    level: 2,
    q: "La web de un instituto de Arequipa recibió 2,000 visitas en la campaña de admisión y 100 personas se matricularon. ¿Cuál fue la tasa de conversión?",
    options: [
      "20 %",
      "0.5 %",
      "2 %",
      "5 %",
    ],
    answer: 3,
    explain: "Tasa de conversión = matrículas entre visitas: 100 / 2,000 = 0.05, es decir 5 %.",
  },
  {
    id: "tq-marketing-15",
    topic: "marketing",
    level: 2,
    q: "Un gimnasio de Trujillo cobra S/ 100 al mes y sus socios se quedan en promedio 12 meses. Sin considerar costos, ¿cuál es el valor de vida (LTV) por ingresos de un socio?",
    options: [
      "S/ 1,200",
      "S/ 100",
      "S/ 112",
      "S/ 600",
    ],
    answer: 0,
    explain: "LTV por ingresos = cuota mensual por meses de permanencia: 100 x 12 = S/ 1,200. Para decidir cuánto invertir en publicidad conviene calcularlo luego sobre el margen.",
  },
  {
    id: "tq-marketing-16",
    topic: "marketing",
    level: 2,
    q: "Una cafetería de Lima sube 10 % el precio de su capuchino y la cantidad vendida baja 20 %. ¿Cuál es la elasticidad precio de la demanda, en valor absoluto?",
    options: [
      "0.5, demanda inelástica",
      "2, demanda elástica",
      "10, demanda elástica",
      "1, elasticidad unitaria",
    ],
    answer: 1,
    explain: "Elasticidad = cambio % en cantidad entre cambio % en precio: 20 / 10 = 2. Como es mayor que 1, la demanda es elástica y subir el precio reduce el ingreso.",
  },
  {
    id: "tq-marketing-17",
    topic: "marketing",
    level: 2,
    q: "Un software de facturación de Lima gasta S/ 300 en conseguir cada cliente (CAC) y cada cliente le deja S/ 900 de margen durante su permanencia (LTV). ¿Cuál es la relación LTV/CAC?",
    options: [
      "2",
      "0.33",
      "3",
      "600",
    ],
    answer: 2,
    explain: "LTV/CAC = 900 / 300 = 3. Cada sol invertido en conseguir clientes devuelve tres soles de margen, una relación que suele considerarse sana.",
  },
  {
    id: "tq-marketing-18",
    topic: "marketing",
    level: 2,
    q: "Una florería de Arequipa paga S/ 500 por una campaña en redes por el Día de la Madre que genera 1,000 clics. ¿Cuál fue su costo por clic (CPC)?",
    options: [
      "S/ 2.00",
      "S/ 5.00",
      "S/ 0.05",
      "S/ 0.50",
    ],
    answer: 3,
    explain: "CPC = inversión entre clics: 500 / 1,000 = S/ 0.50 por clic.",
  },
  {
    id: "tq-marketing-19",
    topic: "marketing",
    level: 2,
    q: "Una juguería de Piura vende 100 jugos diarios a S/ 10. Si baja el precio a S/ 8 y pasa a vender 150 jugos diarios, ¿qué ocurre con su ingreso diario?",
    options: [
      "Sube S/ 200",
      "Baja S/ 200",
      "Se mantiene igual",
      "Sube S/ 500",
    ],
    answer: 0,
    explain: "Antes: 100 x 10 = S/ 1,000. Después: 150 x 8 = S/ 1,200. El ingreso sube S/ 200 porque la cantidad creció más de lo que bajó el precio (demanda elástica).",
  },
  {
    id: "tq-marketing-20",
    topic: "marketing",
    level: 2,
    q: "El anuncio de una inmobiliaria de Lima llega a 50,000 personas, el 2 % hace clic y el 10 % de quienes hacen clic deja sus datos. ¿Cuántos contactos obtiene?",
    options: [
      "1,000",
      "100",
      "6,000",
      "500",
    ],
    answer: 1,
    explain: "Clics: 2 % de 50,000 = 1,000. Contactos: 10 % de 1,000 = 100. En un embudo los porcentajes se aplican en cadena, no se suman.",
  },
  {
    id: "tq-marketing-21",
    topic: "marketing",
    level: 2,
    q: "En un distrito de Chiclayo se venden 20,000 pollos a la brasa al mes entre todas las pollerías. Una de ellas vende 3,000. ¿Cuál es su cuota de mercado en unidades?",
    options: [
      "6.7 %",
      "1.5 %",
      "15 %",
      "30 %",
    ],
    answer: 2,
    explain: "Cuota = ventas propias entre ventas totales del mercado: 3,000 / 20,000 = 0.15, es decir 15 %.",
  },
  {
    id: "tq-marketing-22",
    topic: "marketing",
    level: 2,
    q: "Una marca de ropa de Gamarra quiere vender S/ 30,000 por anuncios en Fiestas Patrias y su ROAS histórico es 5. ¿Cuánto debe invertir aproximadamente en anuncios?",
    options: [
      "S/ 150,000",
      "S/ 5,000",
      "S/ 25,000",
      "S/ 6,000",
    ],
    answer: 3,
    explain: "ROAS = ventas / inversión, entonces inversión = ventas / ROAS: 30,000 / 5 = S/ 6,000.",
  },
  {
    id: "tq-marketing-23",
    topic: "marketing",
    level: 3,
    q: "Una academia de Huancayo invirtió S/ 3,000 en Facebook y logró 60 matrículas, y S/ 2,000 en volanteo con 20 matrículas. Si cada alumno paga lo mismo, ¿qué conviene el próximo ciclo?",
    options: [
      "Priorizar el volanteo, porque costó menos dinero en total",
      "Priorizar Facebook, porque su CAC es S/ 50 frente a S/ 100 del volanteo",
      "Repartir por igual, porque ambos canales generaron matrículas",
      "Priorizar el volanteo, porque su CAC es S/ 50 frente a S/ 100 de Facebook",
    ],
    answer: 1,
    explain: "CAC de Facebook: 3,000 / 60 = S/ 50. CAC del volanteo: 2,000 / 20 = S/ 100. Importa el costo por matrícula, no el gasto total del canal.",
  },
  {
    id: "tq-marketing-24",
    topic: "marketing",
    level: 3,
    q: "Una tienda en línea de Lima invierte S/ 5,000 en una campaña y vende S/ 10,000 (ROAS de 2). Su margen bruto es 40 % de la venta. ¿La campaña dejó ganancia después de pagar la publicidad?",
    options: [
      "No, perdió S/ 1,000: el margen de S/ 4,000 no cubre los S/ 5,000 de publicidad",
      "Sí, ganó S/ 5,000 porque vendió el doble de lo que invirtió",
      "Sí, ganó S/ 4,000, que es su margen bruto",
      "No, perdió S/ 5,000 porque toda la publicidad es pérdida",
    ],
    answer: 0,
    explain: "Margen bruto: 40 % de 10,000 = S/ 4,000. Menos S/ 5,000 de publicidad deja una pérdida de S/ 1,000. Con margen de 40 %, el ROAS mínimo para no perder es 2.5.",
  },
  {
    id: "tq-marketing-25",
    topic: "marketing",
    level: 3,
    q: "Una marca de bebidas de Tarapoto vende 1,000 botellas al mes a S/ 5. Un estudio indica que a S/ 6 vendería 900. Su costo variable es S/ 3 por botella. ¿Qué pasa con su margen de contribución mensual si sube el precio?",
    options: [
      "Baja, porque vende 100 botellas menos",
      "Se mantiene en S/ 2,000",
      "Sube de S/ 2,000 a S/ 2,700",
      "Sube de S/ 5,000 a S/ 5,400",
    ],
    answer: 2,
    explain: "Hoy: 1,000 x (5 - 3) = S/ 2,000. Con el nuevo precio: 900 x (6 - 3) = S/ 2,700. Pierde pocas unidades y gana S/ 1 más en cada una, así que el margen sube S/ 700.",
  },
  {
    id: "tq-marketing-26",
    topic: "marketing",
    level: 3,
    q: "Un gimnasio de Arequipa paga S/ 150 en publicidad por cada socio nuevo. El socio promedio paga S/ 80 al mes, se queda 5 meses y deja un margen de 25 % sobre lo que paga. ¿Es sostenible esa adquisición?",
    options: [
      "Sí, porque el socio paga S/ 400 en total y solo cuesta S/ 150",
      "Sí, porque recupera el CAC en menos de dos meses de cuota",
      "No, porque el socio deja S/ 20 de margen y cuesta S/ 150 conseguirlo",
      "No, porque el socio deja S/ 100 de margen y cuesta S/ 150 conseguirlo",
    ],
    answer: 3,
    explain: "Ingresos por socio: 80 x 5 = S/ 400. Margen de 25 %: S/ 100. Como conseguirlo cuesta S/ 150, pierde S/ 50 por socio. El CAC se compara con el margen, no con el ingreso.",
  },
  {
    id: "tq-marketing-27",
    topic: "marketing",
    level: 3,
    q: "Una cafetería de especialidad de Cusco tiene café premiado y precios altos, pero lanza 2x1 todos los días para competir con los carritos de café. Sus clientes habituales empiezan a dudar de la calidad. ¿Cuál es el problema principal?",
    options: [
      "La promoción diaria contradice su posicionamiento premium y desgasta la marca",
      "El precio aún es alto y debe bajarlo más para ganar a los carritos",
      "El CTR de sus anuncios es muy bajo",
      "La plaza es incorrecta y debe vender también en carritos",
    ],
    answer: 0,
    explain: "Una marca premium se sostiene en la coherencia entre precio, producto y comunicación. El 2x1 diario le dice al cliente que el café no vale lo que cuesta.",
  },
  {
    id: "tq-marketing-28",
    topic: "marketing",
    level: 3,
    q: "Una tienda en línea de Trujillo recibe 10,000 visitas al mes, 2,000 agregan productos al carrito y solo 40 pagan. ¿Dónde está la mayor fuga del embudo?",
    options: [
      "En la atracción: 10,000 visitas son muy pocas, hay que invertir más en anuncios",
      "Del carrito al pago: solo paga 2 % de los carritos, hay que revisar envío y medios de pago",
      "De la visita al carrito: solo 2 % agrega productos, hay que cambiar el catálogo",
      "En la posventa: los clientes no recompran, hay que crear un programa de puntos",
    ],
    answer: 1,
    explain: "De visita a carrito pasa 20 % (2,000 / 10,000), pero de carrito a pago solo 2 % (40 / 2,000). La fuga está en el pago: envío caro, pocos medios de pago o un proceso largo.",
  },
  {
    id: "tq-marketing-29",
    topic: "marketing",
    level: 3,
    q: "Una gaseosa regional de Arequipa tiene ventas estables hace años, muchos competidores y márgenes ajustados: está en madurez. ¿Qué acción de marketing es la más coherente con esa etapa?",
    options: [
      "Explicar qué es una gaseosa, como si la categoría fuera nueva",
      "Retirar toda la publicidad, porque el producto ya se vende solo",
      "Diferenciarse y defender su cuota con fidelización y nuevas presentaciones",
      "Subir fuerte el precio, porque en la madurez no hay competencia",
    ],
    answer: 2,
    explain: "En la madurez el mercado ya conoce el producto y la competencia es fuerte. Toca defender la cuota con diferenciación, fidelización y variantes, cuidando la rentabilidad.",
  },
  {
    id: "tq-marketing-30",
    topic: "marketing",
    level: 3,
    q: "Una botica de Piura analiza sus ventas: los adultos mayores son 20 % de sus clientes pero generan 60 % de los ingresos, con compras mensuales de medicinas de uso continuo. ¿Qué decisión se sostiene mejor con ese dato?",
    options: [
      "Descuidar ese segmento, porque son pocos clientes",
      "Destinar todo el presupuesto a atraer jóvenes, porque son la mayoría",
      "Tratar a todos los clientes igual, porque segmentar no aporta",
      "Crear un programa de fidelización y recordatorios de compra para adultos mayores",
    ],
    answer: 3,
    explain: "Un segmento pequeño en número puede ser el más valioso. Si 20 % de los clientes genera 60 % de los ingresos, retenerlos con un programa a su medida protege la mayor parte de la venta.",
  },
  // investigacion
  {
    id: "tq-investigacion-01",
    topic: "investigacion",
    level: 1,
    q: "Una pastelería de Arequipa encuesta a 200 vecinos para saber qué sabores de torta prefieren. ¿Qué tipo de fuente de información está usando?",
    options: [
      "Fuente secundaria",
      "Fuente primaria",
      "Registro contable interno",
      "Estadística oficial",
    ],
    answer: 1,
    explain: "Es primaria porque la empresa recoge la información por primera vez y para su propio objetivo. Las fuentes secundarias son datos que ya existen, como los del INEI.",
  },
  {
    id: "tq-investigacion-02",
    topic: "investigacion",
    level: 1,
    q: "Un emprendedor de Chiclayo revisa los datos de población del INEI por distrito para estimar cuántas familias hay en su zona. ¿Qué tipo de fuente es?",
    options: [
      "Fuente secundaria",
      "Fuente primaria",
      "Focus group",
      "Prueba de concepto",
    ],
    answer: 0,
    explain: "Los datos del INEI ya fueron recogidos por otra entidad con otro fin, por eso son fuente secundaria. Son baratos y rápidos, y conviene revisarlos antes de hacer encuestas.",
  },
  {
    id: "tq-investigacion-03",
    topic: "investigacion",
    level: 1,
    q: "Una marca de bebidas de Pucallpa reúne a 8 consumidores con un moderador para conversar una hora sobre un nuevo sabor. ¿Qué técnica usa?",
    options: [
      "Encuesta por muestreo",
      "Censo",
      "Experimento de precios",
      "Focus group (grupo focal)",
    ],
    answer: 3,
    explain: "El focus group reúne de 6 a 10 personas con un moderador para explorar opiniones en profundidad. Es una técnica cualitativa.",
  },
  {
    id: "tq-investigacion-04",
    topic: "investigacion",
    level: 1,
    q: "Un instituto de Trujillo tiene 5,000 alumnos y encuesta a 400 elegidos al azar. ¿Cómo se llama ese grupo de 400?",
    options: [
      "Población o universo",
      "Segmento meta",
      "Muestra",
      "Panel de expertos",
    ],
    answer: 2,
    explain: "La muestra es la parte de la población que se estudia para sacar conclusiones sobre el total. La población son los 5,000 alumnos.",
  },
  {
    id: "tq-investigacion-05",
    topic: "investigacion",
    level: 1,
    q: "Una agencia de turismo de Cusco quiere entender a fondo por qué los viajeros desconfían de comprar paquetes en línea, y hace 12 entrevistas largas. ¿Qué tipo de investigación es?",
    options: [
      "Cuantitativa",
      "Cualitativa",
      "Censal",
      "Experimental",
    ],
    answer: 1,
    explain: "La investigación cualitativa busca entender motivos y percepciones con pocas personas y en profundidad. La cuantitativa mide con muchas respuestas y números.",
  },
  {
    id: "tq-investigacion-06",
    topic: "investigacion",
    level: 1,
    q: "Una botica de Tacna quiere medir su NPS. ¿Qué pregunta debe hacer a sus clientes?",
    options: [
      "Del 0 al 10, ¿qué tan probable es que nos recomiendes a un familiar o amigo?",
      "Del 1 al 5, ¿qué tan satisfecho estás con nuestros precios?",
      "¿Cuánto gastaste en tu última compra en la botica?",
      "¿Cuántas veces nos compraste en el último año?",
    ],
    answer: 0,
    explain: "El NPS se basa en la probabilidad de recomendar, medida de 0 a 10. Con esa respuesta se clasifica a los clientes en promotores, pasivos y detractores.",
  },
  {
    id: "tq-investigacion-07",
    topic: "investigacion",
    level: 1,
    q: "La encuesta de una pollería de Lima pregunta: «¿Verdad que nuestro pollo es el más rico del barrio?». ¿Qué problema tiene esa pregunta?",
    options: [
      "Es una pregunta abierta",
      "Mide dos temas a la vez",
      "Induce la respuesta, es una pregunta sesgada",
      "Usa una escala demasiado larga",
    ],
    answer: 2,
    explain: "La pregunta sugiere la respuesta deseada, por eso los resultados salen inflados. Una versión neutral sería: «¿Cómo calificas el sabor de nuestro pollo?».",
  },
  {
    id: "tq-investigacion-08",
    topic: "investigacion",
    level: 1,
    q: "Una app de delivery de Lima estima su tamaño de mercado. ¿Qué representa el TAM?",
    options: [
      "La parte del mercado que puede captar en el corto plazo",
      "Toda la demanda que existe en el mercado para ese tipo de servicio",
      "El mercado que puede atender con su cobertura actual",
      "Las ventas que la empresa logró el año pasado",
    ],
    answer: 1,
    explain: "El TAM es toda la demanda del mercado. El SAM es la parte que puedes atender con tu oferta y cobertura, y el SOM la que puedes captar de forma realista.",
  },
  {
    id: "tq-investigacion-09",
    topic: "investigacion",
    level: 1,
    q: "Antes de fabricar, una marca de snacks de Huancayo muestra la descripción y la imagen de su idea a posibles compradores para ver si les interesa. ¿Cómo se llama esa prueba?",
    options: [
      "Auditoría de tiendas",
      "Estudio de satisfacción posventa",
      "Prueba de concepto",
      "Lanzamiento nacional",
    ],
    answer: 2,
    explain: "La prueba de concepto evalúa el interés por la idea antes de invertir en producción. Permite corregir o descartar el producto con poco gasto.",
  },
  {
    id: "tq-investigacion-10",
    topic: "investigacion",
    level: 1,
    q: "Una asociación de 60 comerciantes de un mercado de Ayacucho entrevista a los 60 socios, sin excepción. ¿Qué tipo de estudio hizo?",
    options: [
      "Muestreo aleatorio",
      "Focus group",
      "Muestreo por conveniencia",
      "Censo",
    ],
    answer: 3,
    explain: "Un censo estudia a todos los integrantes de la población. Es viable cuando la población es pequeña, como 60 socios.",
  },
  {
    id: "tq-investigacion-11",
    topic: "investigacion",
    level: 2,
    q: "Una cafetería de Lima encuesta a 100 clientes: 60 son promotores (9 y 10), 25 pasivos (7 y 8) y 15 detractores (0 a 6). ¿Cuál es su NPS?",
    options: [
      "60",
      "45",
      "85",
      "35",
    ],
    answer: 1,
    explain: "NPS = % de promotores menos % de detractores: 60 - 15 = 45. Los pasivos no suman ni restan.",
  },
  {
    id: "tq-investigacion-12",
    topic: "investigacion",
    level: 2,
    q: "Una marca de ropa deportiva estima un SAM de 200,000 compradores en Lima y cree que puede captar 5 % en tres años. ¿Cuál es su SOM?",
    options: [
      "10,000 compradores",
      "1,000 compradores",
      "40,000 compradores",
      "100,000 compradores",
    ],
    answer: 0,
    explain: "SOM = 5 % del SAM: 200,000 x 0.05 = 10,000 compradores.",
  },
  {
    id: "tq-investigacion-13",
    topic: "investigacion",
    level: 2,
    q: "En una ciudad hay 50,000 hogares con mascota y cada uno gasta en promedio S/ 100 al mes en alimento. ¿Cuál es el tamaño total del mercado (TAM) al año?",
    options: [
      "S/ 5 millones",
      "S/ 6 millones",
      "S/ 60 millones",
      "S/ 600 millones",
    ],
    answer: 2,
    explain: "Gasto mensual: 50,000 x 100 = S/ 5 millones. Al año: 5 x 12 = S/ 60 millones.",
  },
  {
    id: "tq-investigacion-14",
    topic: "investigacion",
    level: 2,
    q: "Una empresa de software de Lima envía una encuesta a 2,000 clientes y responden 300. ¿Cuál fue la tasa de respuesta?",
    options: [
      "6.7 %",
      "30 %",
      "1.5 %",
      "15 %",
    ],
    answer: 3,
    explain: "Tasa de respuesta = respuestas entre encuestas enviadas: 300 / 2,000 = 0.15, es decir 15 %.",
  },
  {
    id: "tq-investigacion-15",
    topic: "investigacion",
    level: 2,
    q: "En una muestra aleatoria de 400 hogares de un distrito de Piura, 120 dicen que comprarían agua de mesa por suscripción. Si el distrito tiene 30,000 hogares, ¿cuántos interesados se estiman?",
    options: [
      "9,000 hogares",
      "120 hogares",
      "3,600 hogares",
      "12,000 hogares",
    ],
    answer: 0,
    explain: "En la muestra, 120 / 400 = 30 %. Proyectado al distrito: 30 % de 30,000 = 9,000 hogares.",
  },
  {
    id: "tq-investigacion-16",
    topic: "investigacion",
    level: 2,
    q: "Un instituto de Cusco tiene 60 % de alumnos en el turno mañana y 40 % en el turno noche. Si la muestra es de 200 alumnos y se reparte en la misma proporción, ¿cuántos deben ser del turno noche?",
    options: [
      "100",
      "80",
      "120",
      "40",
    ],
    answer: 1,
    explain: "Al turno noche le toca 40 % de la muestra: 200 x 0.40 = 80 alumnos. Así la muestra refleja la composición real del instituto.",
  },
  {
    id: "tq-investigacion-17",
    topic: "investigacion",
    level: 2,
    q: "En una encuesta a 500 personas de Trujillo, 200 dicen que «definitivamente comprarían» un nuevo yogur. La empresa asume, por prudencia, que solo la mitad cumplirá. ¿Qué porcentaje de compra estima?",
    options: [
      "40 %",
      "10 %",
      "20 %",
      "50 %",
    ],
    answer: 2,
    explain: "Intención declarada: 200 / 500 = 40 %. Con el ajuste de la mitad: 40 % x 0.5 = 20 %. Se ajusta porque no todos los que dicen que comprarán lo hacen.",
  },
  {
    id: "tq-investigacion-18",
    topic: "investigacion",
    level: 2,
    q: "Cinco clientes de una bodega de Iquitos gastaron S/ 10, S/ 20, S/ 30, S/ 40 y S/ 100. ¿Cuál es el gasto promedio y qué dato lo distorsiona?",
    options: [
      "S/ 30, y ningún dato lo distorsiona",
      "S/ 50, y lo eleva la compra de S/ 100",
      "S/ 20, y lo reduce la compra de S/ 10",
      "S/ 40, y lo eleva la compra de S/ 100",
    ],
    answer: 3,
    explain: "Suma: 10 + 20 + 30 + 40 + 100 = 200. Promedio: 200 / 5 = S/ 40. La compra de S/ 100 jala el promedio hacia arriba. La mediana, S/ 30, describe mejor al cliente típico.",
  },
  {
    id: "tq-investigacion-19",
    topic: "investigacion",
    level: 2,
    q: "Un estudio de mercado en Arequipa tiene un presupuesto de S/ 6,000 para trabajo de campo y cada encuesta presencial cuesta S/ 15. ¿Cuántas encuestas puede hacer como máximo?",
    options: [
      "400",
      "40",
      "900",
      "4,000",
    ],
    answer: 0,
    explain: "6,000 / 15 = 400 encuestas. El presupuesto limita el tamaño de la muestra, por eso se define junto con el método.",
  },
  {
    id: "tq-investigacion-20",
    topic: "investigacion",
    level: 2,
    q: "El TAM de almuerzos por delivery en Lima se estima en 1,000,000 de oficinistas. Una empresa solo reparte en distritos donde trabaja el 30 % de ellos. ¿Cuál es su SAM?",
    options: [
      "700,000 oficinistas",
      "300,000 oficinistas",
      "30,000 oficinistas",
      "1,000,000 de oficinistas",
    ],
    answer: 1,
    explain: "SAM = 30 % del TAM: 1,000,000 x 0.30 = 300,000 oficinistas que la empresa sí puede atender.",
  },
  {
    id: "tq-investigacion-21",
    topic: "investigacion",
    level: 2,
    q: "Un operador de internet de Chiclayo encuesta a 200 clientes: 50 son promotores, 60 pasivos y 90 detractores. ¿Cuál es su NPS?",
    options: [
      "-40",
      "25",
      "-20",
      "20",
    ],
    answer: 2,
    explain: "Promotores: 50 / 200 = 25 %. Detractores: 90 / 200 = 45 %. NPS = 25 - 45 = -20. Se calcula con porcentajes, no con cantidades.",
  },
  {
    id: "tq-investigacion-22",
    topic: "investigacion",
    level: 2,
    q: "Una encuesta en Huancayo indica que 40 % compraría el producto, con un margen de error de 5 puntos porcentuales. ¿En qué rango está el valor probable en la población?",
    options: [
      "Entre 40 % y 45 %",
      "Entre 38 % y 42 %",
      "Entre 5 % y 40 %",
      "Entre 35 % y 45 %",
    ],
    answer: 3,
    explain: "El margen de error se suma y se resta al resultado: 40 - 5 = 35 y 40 + 5 = 45. El valor real probablemente está entre 35 % y 45 %.",
  },
  {
    id: "tq-investigacion-23",
    topic: "investigacion",
    level: 3,
    q: "Un gimnasio de Lima quiere saber por qué la gente del distrito no se inscribe. Encuesta solo a sus socios actuales dentro del local y concluye que el precio no es un problema. ¿Cuál es la falla del estudio?",
    options: [
      "Tamaño de muestra: encuestar a socios siempre da muestras demasiado grandes",
      "Sesgo de selección: preguntó a quienes ya pagan, no a quienes no se inscriben",
      "Tipo de fuente: debió usar solo datos secundarios del INEI",
      "Indicador: debió calcular el NPS en lugar de preguntar por el precio",
    ],
    answer: 1,
    explain: "Quien ya es socio aceptó el precio. Para saber por qué otros no se inscriben hay que preguntar a los que no son clientes.",
  },
  {
    id: "tq-investigacion-24",
    topic: "investigacion",
    level: 3,
    q: "Una marca de bebidas de Lima hace dos focus groups con 16 personas en total. A 12 les encanta el sabor y el gerente afirma que «75 % del mercado peruano lo comprará». ¿Qué error comete?",
    options: [
      "Generaliza un resultado cualitativo que no es representativo del mercado",
      "Calcula mal el porcentaje, porque 12 de 16 es 60 %",
      "Debió hacer un solo focus group con las 16 personas juntas",
      "Ninguno, porque el focus group sirve para medir la cuota de mercado",
    ],
    answer: 0,
    explain: "Un focus group sirve para explorar ideas y motivos, no para medir. Con 16 personas elegidas sin azar no se puede proyectar un porcentaje al mercado.",
  },
  {
    id: "tq-investigacion-25",
    topic: "investigacion",
    level: 3,
    q: "Una academia de inglés en línea calcula: 2,000,000 de jóvenes en Perú (TAM), de los cuales 25 % tiene internet estable y puede pagar (SAM). Espera captar 2 % del SAM en dos años. ¿Cuál es su SOM?",
    options: [
      "40,000 alumnos",
      "500,000 alumnos",
      "10,000 alumnos",
      "100,000 alumnos",
    ],
    answer: 2,
    explain: "SAM = 25 % de 2,000,000 = 500,000. SOM = 2 % de 500,000 = 10,000 alumnos. El SOM se calcula sobre el SAM, no sobre el TAM.",
  },
  {
    id: "tq-investigacion-26",
    topic: "investigacion",
    level: 3,
    q: "En una encuesta, 70 % de los clientes de una pastelería de Trujillo dijo que pagaría S/ 5 más por una torta sin azúcar. Al venderla durante un mes, solo 10 % la eligió. ¿Qué enseñanza deja el caso?",
    options: [
      "La encuesta acertó y el error está en el registro de las ventas",
      "Hay que repetir la encuesta hasta que coincida con las ventas",
      "Las encuestas no sirven y no deben usarse en ningún caso",
      "La intención declarada suele superar a la compra real, conviene probar en venta",
    ],
    answer: 3,
    explain: "Decir que comprarías no cuesta nada, pagar sí. Por eso la intención declarada se ajusta a la baja y se confirma con pilotos o preventas.",
  },
  {
    id: "tq-investigacion-27",
    topic: "investigacion",
    level: 3,
    q: "La encuesta de un restaurante de Arequipa pregunta: «¿Qué tan satisfecho estás con la comida y la atención?» y el promedio sale 3 de 5. ¿Por qué el resultado es difícil de usar?",
    options: [
      "Porque mide dos temas en una sola pregunta y no se sabe cuál falla",
      "Porque la escala de 1 a 5 no es válida para restaurantes",
      "Porque un promedio de 3 significa que todo está bien",
      "Porque la satisfacción solo se mide con preguntas abiertas",
    ],
    answer: 0,
    explain: "Es una pregunta doble. Un 3 puede venir de buena comida y mala atención, o al revés. Cada pregunta debe medir un solo tema.",
  },
  {
    id: "tq-investigacion-28",
    topic: "investigacion",
    level: 3,
    q: "Una cadena de boticas compara dos sedes. Sede A: 50 % de promotores y 40 % de detractores. Sede B: 30 % de promotores y 5 % de detractores. ¿Cuál tiene mejor NPS?",
    options: [
      "La sede A, porque tiene más promotores",
      "La sede B, con NPS de 25 frente a 10 de la sede A",
      "La sede A, con NPS de 90 frente a 35 de la sede B",
      "Ninguna, porque ambas tienen el mismo NPS",
    ],
    answer: 1,
    explain: "NPS de A: 50 - 40 = 10. NPS de B: 30 - 5 = 25. B tiene menos promotores, pero casi nadie habla mal de ella.",
  },
  {
    id: "tq-investigacion-29",
    topic: "investigacion",
    level: 3,
    q: "Para estimar la demanda de un minimarket en un barrio de Piura, un estudiante encuesta por WhatsApp a 100 compañeros de su universidad, porque es rápido. ¿Cuál es la principal limitación?",
    options: [
      "Cien encuestas son insuficientes para cualquier estudio de mercado",
      "Las encuestas por WhatsApp no tienen validez estadística en ningún caso",
      "Es una muestra por conveniencia que no representa a los vecinos del barrio",
      "Debió usar un censo, porque las muestras no sirven para estimar demanda",
    ],
    answer: 2,
    explain: "Los compañeros de universidad no son necesariamente quienes compran en ese barrio. Una muestra por conveniencia es rápida, pero sus resultados no se pueden generalizar.",
  },
  {
    id: "tq-investigacion-30",
    topic: "investigacion",
    level: 3,
    q: "Una empresa de Lima evalúa lanzar un producto con una inversión de S/ 500,000 y no tiene datos de demanda. Una prueba de concepto con piloto cuesta S/ 20,000. ¿Qué criterio es el más sólido?",
    options: [
      "Lanzar sin estudio: investigar cuesta 40 % de la inversión",
      "No lanzar nunca: todo producto nuevo es demasiado riesgoso",
      "Hacer el estudio solo si cuesta más que el propio lanzamiento",
      "Hacer el estudio: cuesta 4 % de la inversión y reduce el riesgo de perderla",
    ],
    answer: 3,
    explain: "20,000 / 500,000 = 4 %. Pagar 4 % para reducir el riesgo de perder una inversión grande es razonable. La investigación vale cuando cuesta menos que el error que evita.",
  },
  // estrategia
  {
    id: "tq-estrategia-01",
    topic: "estrategia",
    level: 1,
    q: "En el FODA de una panadería de Huancayo aparece: «abrirá un supermercado con panadería propia a dos cuadras». ¿Qué es?",
    options: [
      "Una debilidad",
      "Una amenaza",
      "Una fortaleza",
      "Una oportunidad",
    ],
    answer: 1,
    explain: "Es una amenaza porque viene del entorno y puede perjudicar a la empresa. Fortalezas y debilidades son internas, oportunidades y amenazas son externas.",
  },
  {
    id: "tq-estrategia-02",
    topic: "estrategia",
    level: 1,
    q: "En el FODA de una empresa de courier de Lima aparece: «nuestros choferes rotan mucho y les falta capacitación». ¿Qué es?",
    options: [
      "Una debilidad",
      "Una amenaza",
      "Una oportunidad",
      "Una fortaleza",
    ],
    answer: 0,
    explain: "Es una debilidad porque es un problema interno que la empresa puede corregir. Las amenazas vienen de fuera.",
  },
  {
    id: "tq-estrategia-03",
    topic: "estrategia",
    level: 1,
    q: "Una empresa de bebidas de Arequipa tiene una gaseosa líder en un mercado que casi no crece y que le genera mucha caja. En la matriz BCG, ese producto es:",
    options: [
      "Estrella",
      "Interrogante",
      "Perro",
      "Vaca lechera",
    ],
    answer: 3,
    explain: "La vaca lechera tiene alta cuota en un mercado de bajo crecimiento. Genera caja con poca inversión y financia a otras líneas.",
  },
  {
    id: "tq-estrategia-04",
    topic: "estrategia",
    level: 1,
    q: "Una botica de Piura analiza su sector con las cinco fuerzas de Porter. ¿Cuál de estos elementos es una de esas fuerzas?",
    options: [
      "El tipo de cambio del dólar",
      "El clima laboral de la empresa",
      "El poder de negociación de los proveedores",
      "La misión y la visión de la empresa",
    ],
    answer: 2,
    explain: "Las cinco fuerzas son: rivalidad entre competidores, nuevos entrantes, sustitutos, poder de los proveedores y poder de los clientes. El tipo de cambio es un factor del PESTEL.",
  },
  {
    id: "tq-estrategia-05",
    topic: "estrategia",
    level: 1,
    q: "Una importadora de repuestos de Tacna ve subir el tipo de cambio. ¿A qué factor del análisis PESTEL pertenece ese hecho?",
    options: [
      "Político",
      "Social",
      "Tecnológico",
      "Económico",
    ],
    answer: 3,
    explain: "El tipo de cambio es una variable económica, igual que la inflación, las tasas de interés y el empleo.",
  },
  {
    id: "tq-estrategia-06",
    topic: "estrategia",
    level: 1,
    q: "Una cadena de cafeterías de Arequipa declara: «Ser la cadena de café de especialidad más querida del sur del Perú en 2030». Esa frase es un ejemplo de:",
    options: [
      "Visión",
      "Misión",
      "Política de calidad",
      "Propuesta de valor",
    ],
    answer: 0,
    explain: "La visión describe a dónde quiere llegar la empresa en el futuro. La misión explica qué hace hoy, para quién y por qué existe.",
  },
  {
    id: "tq-estrategia-07",
    topic: "estrategia",
    level: 1,
    q: "Una marca de snacks de Lima quiere vender más de sus mismos productos a sus clientes actuales, con promociones. Según la matriz de Ansoff, es una estrategia de:",
    options: [
      "Desarrollo de productos",
      "Desarrollo de mercados",
      "Penetración de mercado",
      "Diversificación",
    ],
    answer: 2,
    explain: "Productos actuales en mercados actuales es penetración de mercado. Es la opción de menor riesgo de la matriz de Ansoff.",
  },
  {
    id: "tq-estrategia-08",
    topic: "estrategia",
    level: 1,
    q: "Una aerolínea que opera en Perú elimina extras y busca tener el menor costo por asiento de la industria para vender pasajes baratos. ¿Qué estrategia genérica de Porter sigue?",
    options: [
      "Diferenciación",
      "Liderazgo en costos",
      "Diversificación",
      "Océano azul",
    ],
    answer: 1,
    explain: "El liderazgo en costos busca tener el costo más bajo de la industria para competir con precios bajos y aun así ganar.",
  },
  {
    id: "tq-estrategia-09",
    topic: "estrategia",
    level: 1,
    q: "Una cevichería de Chiclayo tiene un acuerdo exclusivo con pescadores que le da el pescado más fresco de la zona, y sus rivales no pueden copiarlo con facilidad. Eso es:",
    options: [
      "Una ventaja competitiva",
      "Una amenaza del entorno",
      "Un costo hundido",
      "Una barrera de salida",
    ],
    answer: 0,
    explain: "Una ventaja competitiva es algo valioso para el cliente que la empresa hace mejor que sus rivales y que es difícil de imitar.",
  },
  {
    id: "tq-estrategia-10",
    topic: "estrategia",
    level: 1,
    q: "El equipo de una tienda en línea de Lima escribe su OKR. La frase «aumentar la recompra de 20 % a 30 % en el trimestre» es:",
    options: [
      "El objetivo, porque es cualitativo e inspirador",
      "Una iniciativa, porque es una tarea",
      "La visión de la empresa",
      "Un resultado clave, porque es medible",
    ],
    answer: 3,
    explain: "El objetivo dice qué se quiere lograr en palabras inspiradoras. Los resultados clave son las metas medibles que indican si se logró, como pasar de 20 % a 30 %.",
  },
  {
    id: "tq-estrategia-11",
    topic: "estrategia",
    level: 2,
    q: "Una línea de jugos tiene 5 % de cuota en un mercado que crece 25 % al año, donde el líder tiene 40 %. ¿Dónde se ubica en la matriz BCG?",
    options: [
      "Estrella",
      "Interrogante",
      "Vaca lechera",
      "Perro",
    ],
    answer: 1,
    explain: "Baja cuota en un mercado de alto crecimiento es una interrogante. Necesita inversión para convertirse en estrella, o puede terminar como perro.",
  },
  {
    id: "tq-estrategia-12",
    topic: "estrategia",
    level: 2,
    q: "Una marca de café de Cusco tiene 10 % de cuota de mercado y su mayor competidor tiene 40 %. ¿Cuál es su participación relativa, la que usa la matriz BCG?",
    options: [
      "0.25",
      "4",
      "0.5",
      "30 %",
    ],
    answer: 0,
    explain: "Participación relativa = cuota propia entre cuota del mayor competidor: 10 / 40 = 0.25. Menos de 1 significa que no eres líder.",
  },
  {
    id: "tq-estrategia-13",
    topic: "estrategia",
    level: 2,
    q: "Una cadena de pollerías de Lima abre locales en Arequipa y Trujillo con la misma carta. Según la matriz de Ansoff, es una estrategia de:",
    options: [
      "Penetración de mercado",
      "Desarrollo de productos",
      "Desarrollo de mercados",
      "Diversificación",
    ],
    answer: 2,
    explain: "Mismos productos en mercados nuevos (otras ciudades) es desarrollo de mercados.",
  },
  {
    id: "tq-estrategia-14",
    topic: "estrategia",
    level: 2,
    q: "Una empresa de confecciones de Gamarra decide abrir un hospedaje turístico en Oxapampa. Según la matriz de Ansoff, es una estrategia de:",
    options: [
      "Desarrollo de productos",
      "Desarrollo de mercados",
      "Penetración de mercado",
      "Diversificación",
    ],
    answer: 3,
    explain: "Producto nuevo en un mercado nuevo es diversificación. Es el cuadrante de mayor riesgo porque la empresa no conoce ni el negocio ni al cliente.",
  },
  {
    id: "tq-estrategia-15",
    topic: "estrategia",
    level: 2,
    q: "Una agroexportadora de Ica tiene certificación orgánica (fortaleza) y crece la demanda europea de productos orgánicos (oportunidad). Usar la certificación para entrar a Europa es una estrategia del FODA cruzado de tipo:",
    options: [
      "FO",
      "FA",
      "DO",
      "DA",
    ],
    answer: 0,
    explain: "Las estrategias FO usan una fortaleza interna para aprovechar una oportunidad del entorno.",
  },
  {
    id: "tq-estrategia-16",
    topic: "estrategia",
    level: 2,
    q: "En la cadena de valor de una fábrica de muebles de Villa El Salvador, ¿cuál de estas es una actividad primaria?",
    options: [
      "Gestión de recursos humanos",
      "Logística de salida (despacho a clientes)",
      "Compras o abastecimiento",
      "Desarrollo de tecnología",
    ],
    answer: 1,
    explain: "Las actividades primarias son logística de entrada, operaciones, logística de salida, marketing y ventas, y servicio. Las compras son una actividad de apoyo.",
  },
  {
    id: "tq-estrategia-17",
    topic: "estrategia",
    level: 2,
    q: "En el cuadro de mando integral de un instituto de Trujillo, el indicador «horas de capacitación por docente» pertenece a la perspectiva de:",
    options: [
      "Financiera",
      "Clientes",
      "Aprendizaje y crecimiento",
      "Procesos internos",
    ],
    answer: 2,
    explain: "La perspectiva de aprendizaje y crecimiento mide las capacidades de las personas, los sistemas y la cultura que sostienen los resultados futuros.",
  },
  {
    id: "tq-estrategia-18",
    topic: "estrategia",
    level: 2,
    q: "Para una cadena de cines de Lima, el crecimiento de las plataformas de streaming representa principalmente:",
    options: [
      "Poder de negociación de los proveedores",
      "Poder de negociación de los clientes",
      "Rivalidad entre las cadenas de cines",
      "Amenaza de productos sustitutos",
    ],
    answer: 3,
    explain: "Un sustituto satisface la misma necesidad (entretenimiento) con un producto distinto. No es un competidor directo, pero limita los precios que el cine puede cobrar.",
  },
  {
    id: "tq-estrategia-19",
    topic: "estrategia",
    level: 2,
    q: "Una empresa de limpieza de Lima factura S/ 100,000 al mes y S/ 70,000 vienen de un solo cliente. ¿Qué fuerza de Porter es crítica para ella?",
    options: [
      "Poder de negociación del cliente, que concentra 70 % de las ventas",
      "Amenaza de sustitutos, que concentran 30 % de las ventas",
      "Poder de los proveedores, que concentran 70 % de las compras",
      "Amenaza de nuevos entrantes, que concentran 7 % del mercado",
    ],
    answer: 0,
    explain: "70,000 / 100,000 = 70 % de las ventas en un solo cliente. Ese cliente puede exigir rebajas o plazos y la empresa depende de él.",
  },
  {
    id: "tq-estrategia-20",
    topic: "estrategia",
    level: 2,
    q: "Una empresa de Lima crea un gimnasio para adultos mayores con fisioterapeuta incluido, un servicio que ninguna cadena ofrecía, en vez de pelear por precio con ellas. Esto ilustra la estrategia de:",
    options: [
      "Liderazgo en costos",
      "Océano azul",
      "Integración vertical",
      "Penetración de mercado",
    ],
    answer: 1,
    explain: "El océano azul crea un espacio de mercado nuevo donde la competencia pierde relevancia, en vez de pelear por precio en el mercado saturado (océano rojo).",
  },
  {
    id: "tq-estrategia-21",
    topic: "estrategia",
    level: 2,
    q: "Un resultado clave del OKR de una academia de Piura era pasar de 200 a 300 alumnos. El trimestre cerró con 250. ¿Qué avance logró en ese resultado clave?",
    options: [
      "83 %",
      "25 %",
      "50 %",
      "125 %",
    ],
    answer: 2,
    explain: "Avance = (logrado - inicio) / (meta - inicio) = (250 - 200) / (300 - 200) = 50 / 100 = 50 %.",
  },
  {
    id: "tq-estrategia-22",
    topic: "estrategia",
    level: 2,
    q: "El mercado de café de especialidad de una ciudad pasó de S/ 10 millones a S/ 12 millones en un año. ¿Cuál fue la tasa de crecimiento que usarías en la matriz BCG?",
    options: [
      "12 %",
      "2 %",
      "16.7 %",
      "20 %",
    ],
    answer: 3,
    explain: "Crecimiento = (12 - 10) / 10 = 0.20, es decir 20 %. Se divide entre el valor inicial, no entre el final.",
  },
  {
    id: "tq-estrategia-23",
    topic: "estrategia",
    level: 3,
    q: "Una empresa de Lima tiene una línea vaca lechera que genera S/ 500,000 de caja al año y una línea interrogante en un mercado que crece 30 %. La gerencia quiere repartir toda la caja en dividendos. Según la BCG, ¿qué conviene?",
    options: [
      "Invertir toda la caja en la vaca para que su mercado vuelva a crecer",
      "Usar parte de la caja de la vaca para financiar a la interrogante con futuro",
      "Cerrar la vaca lechera, porque su mercado ya no crece",
      "Vender la interrogante, porque toda interrogante termina como perro",
    ],
    answer: 1,
    explain: "La BCG propone equilibrar la cartera: la caja de las vacas financia a las estrellas e interrogantes con futuro, que serán las vacas de mañana.",
  },
  {
    id: "tq-estrategia-24",
    topic: "estrategia",
    level: 3,
    q: "Una academia de Huancayo no tiene plataforma virtual (debilidad) y aparece un fondo concursable para digitalizar pequeñas empresas (oportunidad). Postular para crear la plataforma es una estrategia del FODA cruzado de tipo:",
    options: [
      "DO: aprovecha una oportunidad para superar una debilidad",
      "FO: usa una fortaleza para aprovechar una oportunidad",
      "FA: usa una fortaleza para enfrentar una amenaza",
      "DA: reduce una debilidad para evitar una amenaza",
    ],
    answer: 0,
    explain: "Una estrategia DO corrige una debilidad interna aprovechando una oportunidad externa.",
  },
  {
    id: "tq-estrategia-25",
    topic: "estrategia",
    level: 3,
    q: "Una marca de zapatillas de Trujillo sube sus precios para parecer premium, pero mantiene materiales baratos y tampoco logra costos tan bajos como los importados. Según Porter, ¿cuál es su problema?",
    options: [
      "Aplica una estrategia de enfoque demasiado estrecha",
      "Tiene una ventaja en costos que no sabe comunicar",
      "Está atrapada en el medio: ni lidera en costos ni se diferencia",
      "Se diferencia tanto que su mercado quedó muy pequeño",
    ],
    answer: 2,
    explain: "Porter advierte que quien no elige entre costos bajos, diferenciación o enfoque queda atrapado en el medio, sin ventaja clara y con baja rentabilidad.",
  },
  {
    id: "tq-estrategia-26",
    topic: "estrategia",
    level: 3,
    q: "Abrir una bodega en un barrio de Piura requiere poca inversión y trámites sencillos, y cada año aparecen varias nuevas. Los márgenes del rubro son bajos. ¿Qué fuerza de Porter explica mejor esos márgenes?",
    options: [
      "El poder de los proveedores, porque hay pocas bodegas",
      "La amenaza de sustitutos, porque nadie compra abarrotes",
      "El poder de los clientes, porque cada uno compra en gran volumen",
      "La amenaza de nuevos entrantes, por las bajas barreras de entrada",
    ],
    answer: 3,
    explain: "Cuando entrar a un negocio es fácil y barato, cada nuevo competidor reparte la misma demanda y presiona los precios, por eso los márgenes son bajos.",
  },
  {
    id: "tq-estrategia-27",
    topic: "estrategia",
    level: 3,
    q: "Una cafetería de Lima basa su ventaja en tener el precio más bajo de la cuadra gracias a una promoción que cualquier rival puede igualar en una semana. ¿Por qué no es una ventaja competitiva sostenible?",
    options: [
      "Porque es fácil de imitar y no se apoya en un recurso propio difícil de copiar",
      "Porque el precio nunca influye en la decisión de compra del cliente",
      "Porque una cafetería pequeña no puede tener ventajas competitivas",
      "Porque las promociones están prohibidas como estrategia de precios",
    ],
    answer: 0,
    explain: "Una ventaja es sostenible cuando se apoya en recursos o capacidades valiosos y difíciles de imitar. Una promoción se copia en días.",
  },
  {
    id: "tq-estrategia-28",
    topic: "estrategia",
    level: 3,
    q: "Una empresa de logística de Lima cumple su meta de utilidad del año recortando capacitación y mantenimiento. Su cuadro de mando muestra caídas en satisfacción del cliente y en entregas a tiempo. ¿Qué lectura es correcta?",
    options: [
      "Todo va bien, porque la perspectiva financiera es la única que importa",
      "La utilidad futura está en riesgo, porque empeoran los indicadores que la anticipan",
      "Debe eliminar los indicadores no financieros, porque confunden",
      "La caída en entregas a tiempo no tiene relación con los clientes",
    ],
    answer: 1,
    explain: "El cuadro de mando integral vincula causas y efectos: clientes insatisfechos y procesos que fallan hoy anuncian menores ventas y utilidades mañana.",
  },
  {
    id: "tq-estrategia-29",
    topic: "estrategia",
    level: 3,
    q: "Una agroexportadora de Piura lee tres noticias: pronóstico de Fenómeno del Niño, caída del dólar y nueva exigencia de etiquetado en el país de destino. ¿Cómo se clasifican en el PESTEL, en ese orden?",
    options: [
      "Social, político y tecnológico",
      "Económico, ambiental y legal",
      "Ambiental, económico y legal",
      "Ambiental, político y social",
    ],
    answer: 2,
    explain: "El Fenómeno del Niño es un factor ambiental, el tipo de cambio es económico y una exigencia de etiquetado es legal.",
  },
  {
    id: "tq-estrategia-30",
    topic: "estrategia",
    level: 3,
    q: "Una pastelería de Arequipa con poca caja evalúa cuatro caminos para crecer. Según la matriz de Ansoff, ¿cuál es el de mayor riesgo?",
    options: [
      "Vender más tortas a sus clientes actuales (penetración de mercado)",
      "Llevar sus mismas tortas a Tacna (desarrollo de mercados)",
      "Ofrecer bocaditos salados a sus clientes actuales (desarrollo de productos)",
      "Abrir en Tacna una línea de helados que nunca ha producido (diversificación)",
    ],
    answer: 3,
    explain: "La diversificación combina producto nuevo y mercado nuevo, por eso acumula los dos riesgos. Con poca caja conviene empezar por penetración.",
  },
  // ventas
  {
    id: "tq-ventas-01",
    topic: "ventas",
    level: 1,
    q: "Un vendedor de una empresa de software de Lima arma una lista de 100 estudios contables que podrían necesitar su sistema y busca sus contactos. ¿Qué etapa de la venta es?",
    options: [
      "Cierre",
      "Prospección",
      "Posventa",
      "Manejo de objeciones",
    ],
    answer: 1,
    explain: "Prospectar es buscar e identificar posibles clientes antes de contactarlos. Es la primera etapa del proceso de ventas.",
  },
  {
    id: "tq-ventas-02",
    topic: "ventas",
    level: 1,
    q: "Un cliente le dice a la vendedora de una concesionaria de Arequipa: «Me gusta el auto, pero está muy caro». En ventas, eso es:",
    options: [
      "Una objeción",
      "Un cierre",
      "Una prospección",
      "Una venta cruzada",
    ],
    answer: 0,
    explain: "Una objeción es una duda o resistencia del cliente. No es un rechazo: bien atendida suele mostrar interés real en comprar.",
  },
  {
    id: "tq-ventas-03",
    topic: "ventas",
    level: 1,
    q: "En una botica de Trujillo, el cliente compra un antigripal y el vendedor le ofrece además vitamina C. ¿Qué técnica está usando?",
    options: [
      "Venta ascendente (una versión más cara)",
      "Prospección en frío",
      "Descuento por volumen",
      "Venta cruzada",
    ],
    answer: 3,
    explain: "La venta cruzada ofrece un producto complementario al que el cliente ya lleva. La venta ascendente ofrece una versión mejor o más cara del mismo producto.",
  },
  {
    id: "tq-ventas-04",
    topic: "ventas",
    level: 1,
    q: "Una inmobiliaria de Lima registra en un sistema cada contacto, llamada y visita de sus prospectos para hacerles seguimiento. Ese sistema es un:",
    options: [
      "ERP de contabilidad",
      "Sistema de planillas",
      "CRM",
      "Catálogo de productos",
    ],
    answer: 2,
    explain: "Un CRM (gestión de relaciones con clientes) guarda el historial de cada prospecto y cliente para dar seguimiento y no perder oportunidades.",
  },
  {
    id: "tq-ventas-05",
    topic: "ventas",
    level: 1,
    q: "El dueño de un minimarket de Chiclayo revisa su ticket promedio. ¿Qué mide ese indicador?",
    options: [
      "Cuántos clientes entran a la tienda por día",
      "Cuánto gasta en promedio cada cliente por compra",
      "Cuánto gana la tienda por cada producto",
      "Cuántos productos hay en el almacén",
    ],
    answer: 1,
    explain: "Ticket promedio = ventas totales entre número de compras. Indica cuánto gasta el cliente cada vez que compra.",
  },
  {
    id: "tq-ventas-06",
    topic: "ventas",
    level: 1,
    q: "Una empresa de Lima vende servicios de limpieza a clínicas y fábricas mediante contratos anuales. ¿Qué tipo de venta es?",
    options: [
      "B2B (de empresa a empresa)",
      "B2C (de empresa a consumidor)",
      "C2C (entre consumidores)",
      "Venta minorista al paso",
    ],
    answer: 0,
    explain: "B2B significa que el cliente es otra empresa. Suele tener montos mayores, varios decisores y ciclos de venta más largos.",
  },
  {
    id: "tq-ventas-07",
    topic: "ventas",
    level: 1,
    q: "A un vendedor de una distribuidora de Piura le fijan vender S/ 40,000 en el mes como meta. Ese monto es su:",
    options: [
      "Comisión",
      "Ticket promedio",
      "Cuota de ventas",
      "Margen bruto",
    ],
    answer: 2,
    explain: "La cuota es la meta de ventas asignada a un vendedor para un periodo. La comisión es lo que gana por vender.",
  },
  {
    id: "tq-ventas-08",
    topic: "ventas",
    level: 1,
    q: "Una tienda de electrodomésticos de Huancayo llama al cliente una semana después de la compra para verificar que la lavadora funciona bien. Esa acción es de:",
    options: [
      "Prospección",
      "Posventa",
      "Cierre",
      "Calificación de prospectos",
    ],
    answer: 1,
    explain: "La posventa es el seguimiento después de la compra. Genera satisfacción, recompra y recomendaciones.",
  },
  {
    id: "tq-ventas-09",
    topic: "ventas",
    level: 1,
    q: "En la venta consultiva B2B, ¿qué hace primero un buen vendedor de maquinaria industrial al visitar una fábrica de Arequipa?",
    options: [
      "Presenta todo el catálogo con sus precios",
      "Ofrece el máximo descuento para cerrar rápido",
      "Pregunta y diagnostica las necesidades del cliente",
      "Señala los defectos de la competencia",
    ],
    answer: 2,
    explain: "La venta consultiva parte de entender el problema del cliente para luego proponer una solución a su medida.",
  },
  {
    id: "tq-ventas-10",
    topic: "ventas",
    level: 1,
    q: "Después de resolver dudas, el asesor de un instituto de Cusco pregunta: «¿Prefieres matricularte en el turno mañana o en el de noche?». ¿Qué etapa de la venta está intentando?",
    options: [
      "La prospección",
      "La posventa",
      "La calificación del prospecto",
      "El cierre",
    ],
    answer: 3,
    explain: "Es un cierre por alternativa: el vendedor da por hecha la compra y pide elegir entre dos opciones.",
  },
  {
    id: "tq-ventas-11",
    topic: "ventas",
    level: 2,
    q: "Una vendedora de Gamarra gana 5 % de comisión y vende S/ 30,000 en el mes. ¿Cuánto recibe de comisión?",
    options: [
      "S/ 150",
      "S/ 1,500",
      "S/ 6,000",
      "S/ 3,000",
    ],
    answer: 1,
    explain: "Comisión = 5 % de 30,000 = 0.05 x 30,000 = S/ 1,500.",
  },
  {
    id: "tq-ventas-12",
    topic: "ventas",
    level: 2,
    q: "Una cafetería de Lima vendió S/ 6,000 en un día y emitió 300 boletas. ¿Cuál fue su ticket promedio?",
    options: [
      "S/ 20",
      "S/ 2",
      "S/ 30",
      "S/ 200",
    ],
    answer: 0,
    explain: "Ticket promedio = ventas entre número de boletas: 6,000 / 300 = S/ 20.",
  },
  {
    id: "tq-ventas-13",
    topic: "ventas",
    level: 2,
    q: "Un vendedor de seguros de Trujillo presentó 40 propuestas en el mes y cerró 10 ventas. ¿Cuál es su tasa de cierre?",
    options: [
      "4 %",
      "40 %",
      "25 %",
      "10 %",
    ],
    answer: 2,
    explain: "Tasa de cierre = ventas entre propuestas: 10 / 40 = 0.25, es decir 25 %.",
  },
  {
    id: "tq-ventas-14",
    topic: "ventas",
    level: 2,
    q: "Una vendedora B2B de Lima cierra 1 de cada 5 reuniones y necesita 8 ventas al mes para llegar a su cuota. ¿Cuántas reuniones debe conseguir?",
    options: [
      "13",
      "16",
      "80",
      "40",
    ],
    answer: 3,
    explain: "Si cierra 1 de cada 5, necesita 5 reuniones por venta: 8 x 5 = 40 reuniones.",
  },
  {
    id: "tq-ventas-15",
    topic: "ventas",
    level: 2,
    q: "La cuota mensual de un vendedor de Piura es S/ 50,000 y vendió S/ 40,000. ¿Qué porcentaje de cumplimiento logró?",
    options: [
      "80 %",
      "125 %",
      "20 %",
      "90 %",
    ],
    answer: 0,
    explain: "Cumplimiento = venta real entre cuota: 40,000 / 50,000 = 0.80, es decir 80 %.",
  },
  {
    id: "tq-ventas-16",
    topic: "ventas",
    level: 2,
    q: "Un vendedor de una concesionaria de Lima tiene sueldo fijo de S/ 1,500 más 2 % de comisión. Si vende S/ 100,000 en el mes, ¿cuánto gana en total?",
    options: [
      "S/ 2,000",
      "S/ 3,500",
      "S/ 1,700",
      "S/ 3,000",
    ],
    answer: 1,
    explain: "Comisión: 2 % de 100,000 = S/ 2,000. Total: 1,500 + 2,000 = S/ 3,500.",
  },
  {
    id: "tq-ventas-17",
    topic: "ventas",
    level: 2,
    q: "Una pollería de Chiclayo tiene un ticket promedio de S/ 50. Si logra que 1 de cada 2 clientes agregue una gaseosa de S/ 10, ¿a cuánto sube el ticket promedio?",
    options: [
      "S/ 60",
      "S/ 52",
      "S/ 55",
      "S/ 65",
    ],
    answer: 2,
    explain: "La mitad de los clientes agrega S/ 10, lo que en promedio suma S/ 5 por cliente: 50 + 5 = S/ 55.",
  },
  {
    id: "tq-ventas-18",
    topic: "ventas",
    level: 2,
    q: "Un minimarket de Arequipa atiende 200 clientes al día con un ticket promedio de S/ 15. ¿Cuánto vende en un mes de 30 días?",
    options: [
      "S/ 3,000",
      "S/ 9,000",
      "S/ 900,000",
      "S/ 90,000",
    ],
    answer: 3,
    explain: "Venta diaria: 200 x 15 = S/ 3,000. Venta mensual: 3,000 x 30 = S/ 90,000.",
  },
  {
    id: "tq-ventas-19",
    topic: "ventas",
    level: 2,
    q: "Un vendedor da 10 % de descuento en un producto de S/ 200 que a la empresa le cuesta S/ 150. Sin considerar el IGV, ¿cuánto queda de margen bruto por unidad?",
    options: [
      "S/ 30",
      "S/ 50",
      "S/ 45",
      "S/ 20",
    ],
    answer: 0,
    explain: "Precio con descuento: 200 - 20 = S/ 180. Margen: 180 - 150 = S/ 30. Un descuento de 10 % en el precio redujo el margen de S/ 50 a S/ 30, es decir 40 %.",
  },
  {
    id: "tq-ventas-20",
    topic: "ventas",
    level: 2,
    q: "De 500 prospectos contactados por una academia de Huancayo en la campaña escolar, 20 % acepta una clase de prueba y, de ellos, 30 % se matricula. ¿Cuántas matrículas se logran?",
    options: [
      "250",
      "30",
      "150",
      "100",
    ],
    answer: 1,
    explain: "Clases de prueba: 20 % de 500 = 100. Matrículas: 30 % de 100 = 30.",
  },
  {
    id: "tq-ventas-21",
    topic: "ventas",
    level: 2,
    q: "Una vendedora cobra 3 % de comisión por lo que vende hasta su cuota de S/ 20,000 y 5 % por el exceso. Si vende S/ 30,000, ¿cuánta comisión gana?",
    options: [
      "S/ 1,500",
      "S/ 900",
      "S/ 1,100",
      "S/ 2,400",
    ],
    answer: 2,
    explain: "Hasta la cuota: 3 % de 20,000 = S/ 600. Exceso: 5 % de 10,000 = S/ 500. Total: 600 + 500 = S/ 1,100.",
  },
  {
    id: "tq-ventas-22",
    topic: "ventas",
    level: 2,
    q: "Una tienda de mascotas de Lima tiene 1,000 clientes y 40 % recompra cada mes con un ticket de S/ 50. ¿Cuánto vende al mes por recompra?",
    options: [
      "S/ 50,000",
      "S/ 2,000",
      "S/ 30,000",
      "S/ 20,000",
    ],
    answer: 3,
    explain: "Clientes que recompran: 40 % de 1,000 = 400. Venta: 400 x 50 = S/ 20,000.",
  },
  {
    id: "tq-ventas-23",
    topic: "ventas",
    level: 3,
    q: "Un gerente de planta de Arequipa dice que tu compresora de S/ 80,000 es cara frente a otra de S/ 60,000. La tuya ahorra S/ 10,000 al año en energía y dura 10 años. ¿Cuál es el mejor argumento?",
    options: [
      "Igualar de inmediato el precio de S/ 60,000 para no perder la venta",
      "Mostrar el costo total: la diferencia de S/ 20,000 se recupera en 2 años de ahorro",
      "Afirmar que la otra marca es mala y se malogra siempre",
      "Mostrar el costo total: la diferencia de S/ 20,000 se recupera en 5 años de ahorro",
    ],
    answer: 1,
    explain: "La diferencia de precio es S/ 20,000 y el ahorro es S/ 10,000 al año, así que se recupera en 2 años. En 10 años el ahorro suma S/ 100,000. En B2B se vende costo total, no precio de lista.",
  },
  {
    id: "tq-ventas-24",
    topic: "ventas",
    level: 3,
    q: "Una vendedora de software de Lima tiene 50 prospectos y tiempo para solo 10 reuniones. Conoce el presupuesto, la necesidad, quién decide y el plazo de compra de cada uno. ¿Cómo debe elegir?",
    options: [
      "Priorizar a quienes tienen necesidad, presupuesto, poder de decisión y plazo cercano",
      "Atender por orden de llegada, para ser justa con todos",
      "Priorizar a las empresas más grandes, aunque no tengan necesidad",
      "Visitar primero a las empresas más cercanas a su oficina",
    ],
    answer: 0,
    explain: "Calificar prospectos es priorizar a los que tienen mayor probabilidad de comprar: necesidad, presupuesto, autoridad para decidir y plazo definido.",
  },
  {
    id: "tq-ventas-25",
    topic: "ventas",
    level: 3,
    q: "Una distribuidora de Trujillo paga comisión sobre ventas y sus vendedores dan el descuento máximo para vender más. Las ventas suben 20 %, pero la utilidad bruta cae. ¿Qué cambio en los incentivos ataca la causa?",
    options: [
      "Subir el porcentaje de comisión sobre la venta",
      "Elevar la cuota de ventas de cada vendedor",
      "Pagar la comisión sobre el margen bruto y no sobre la venta",
      "Pagar un bono por cantidad de unidades vendidas",
    ],
    answer: 2,
    explain: "Si la comisión depende solo de la venta, el vendedor sacrifica precio para vender más. Al pagar sobre el margen, su interés se alinea con la utilidad de la empresa.",
  },
  {
    id: "tq-ventas-26",
    topic: "ventas",
    level: 3,
    q: "En una inmobiliaria de Lima, Ana hace 100 llamadas, logra 20 visitas y cierra 2 ventas. Luis hace 50 llamadas, logra 10 visitas y cierra 4 ventas. ¿Qué debe mejorar Ana?",
    options: [
      "La prospección: hace menos llamadas que Luis",
      "El paso de llamada a visita: convierte menos que Luis",
      "Nada: hace más llamadas y por eso rinde más que Luis",
      "El cierre: convierte 10 % de sus visitas frente a 40 % de Luis",
    ],
    answer: 3,
    explain: "Ambos convierten 20 % de llamadas en visitas. Pero Ana cierra 2 de 20 visitas (10 %) y Luis 4 de 10 (40 %). El problema de Ana está en el cierre.",
  },
  {
    id: "tq-ventas-27",
    topic: "ventas",
    level: 3,
    q: "Una empresa de internet de Chiclayo gasta S/ 200 en captar cada cliente nuevo y pierde 100 clientes al mes por mala atención. Retener a cada uno le costaría S/ 40 en mejor soporte. ¿Qué conviene priorizar?",
    options: [
      "Mejorar la posventa: retener cuesta S/ 40 y captar un reemplazo cuesta S/ 200",
      "Duplicar la publicidad para reemplazar a los clientes que se van",
      "Bajar el precio solo a los clientes nuevos",
      "No hacer nada, porque perder 100 clientes al mes es normal",
    ],
    answer: 0,
    explain: "Retener cuesta S/ 40 frente a S/ 200 de captar un reemplazo, cinco veces menos. Si no se corrige la atención, la empresa gasta en llenar un balde con huecos.",
  },
  {
    id: "tq-ventas-28",
    topic: "ventas",
    level: 3,
    q: "Un vendedor B2B de Lima cumple su cuota de S/ 100,000, pero S/ 80,000 vienen de un solo cliente cuyo contrato vence en tres meses. ¿Cuál es la lectura correcta?",
    options: [
      "No hay riesgo, porque el vendedor cumplió su cuota",
      "Hay riesgo de concentración: debe prospectar para diversificar su cartera",
      "Debe dejar de atender al cliente grande para equilibrar su cartera",
      "Debe pedir que le reduzcan la cuota del próximo trimestre",
    ],
    answer: 1,
    explain: "80,000 / 100,000 = 80 % de su venta depende de un cliente. Si ese contrato no se renueva, la cuota cae de golpe. Debe cuidar al cliente y a la vez prospectar nuevos.",
  },
  {
    id: "tq-ventas-29",
    topic: "ventas",
    level: 3,
    q: "Una tienda de Gamarra vende 100 polos al mes a S/ 50, con un costo de S/ 30 cada uno. Un vendedor propone bajar el precio a S/ 40 y asegura que venderá 150. ¿Qué pasa con la utilidad bruta mensual?",
    options: [
      "Sube de S/ 5,000 a S/ 6,000",
      "Se mantiene en S/ 2,000",
      "Baja de S/ 2,000 a S/ 1,500, aunque la venta suba",
      "Sube de S/ 2,000 a S/ 3,000",
    ],
    answer: 2,
    explain: "Antes: 100 x (50 - 30) = S/ 2,000. Después: 150 x (40 - 30) = S/ 1,500. La venta sube de S/ 5,000 a S/ 6,000, pero la utilidad bruta baja S/ 500.",
  },
  {
    id: "tq-ventas-30",
    topic: "ventas",
    level: 3,
    q: "En una reunión, el gerente de una clínica de Piura pregunta a la vendedora de un software: «¿En cuánto tiempo lo instalan y cómo sería la capacitación?». ¿Qué debe hacer la vendedora?",
    options: [
      "Volver a explicar todas las funciones del sistema desde el inicio",
      "Ofrecer de inmediato un descuento que el cliente no pidió",
      "Terminar la reunión y enviar después un catálogo por correo",
      "Reconocer la señal de compra, responder y proponer el siguiente paso del cierre",
    ],
    answer: 3,
    explain: "Preguntar por instalación y capacitación es una señal de compra: el cliente ya se imagina usando el producto. Toca responder y avanzar al cierre.",
  },
  // emprendimiento
  {
    id: "tq-emprendimiento-01",
    topic: "emprendimiento",
    level: 1,
    q: "Una emprendedora de Lima quiere probar su idea de loncheras saludables. Antes de alquilar un local, vende 20 loncheras por WhatsApp a padres de un colegio. Esa primera versión es un:",
    options: [
      "Plan de negocio",
      "Producto mínimo viable",
      "Pitch",
      "Punto de equilibrio",
    ],
    answer: 1,
    explain: "El producto mínimo viable es la versión más simple que permite vender y aprender de clientes reales con poca inversión.",
  },
  {
    id: "tq-emprendimiento-02",
    topic: "emprendimiento",
    level: 1,
    q: "En el lienzo Canvas de una cafetería de Cusco, «productores de café de Quillabamba que nos abastecen» va en el bloque de:",
    options: [
      "Socios clave",
      "Segmentos de clientes",
      "Canales",
      "Fuentes de ingresos",
    ],
    answer: 0,
    explain: "Los socios clave son los proveedores y aliados sin los cuales el modelo de negocio no funciona.",
  },
  {
    id: "tq-emprendimiento-03",
    topic: "emprendimiento",
    level: 1,
    q: "Un emprendimiento de Lima se presenta así: «Almuerzos caseros en tu oficina en 30 minutos, sin pedido mínimo». En su modelo de negocio, esa frase describe su:",
    options: [
      "Estructura de costos",
      "Fuente de ingresos",
      "Relación con proveedores",
      "Propuesta de valor",
    ],
    answer: 3,
    explain: "La propuesta de valor explica qué problema resuelves y por qué el cliente te elegiría a ti.",
  },
  {
    id: "tq-emprendimiento-04",
    topic: "emprendimiento",
    level: 1,
    q: "Una app de Bogotá nació para reservar canchas de fútbol, pero descubre que los dueños la usan sobre todo para cobrar. Cambia su modelo y se convierte en un sistema de cobros. Eso es:",
    options: [
      "Escalar",
      "Formalizarse",
      "Pivotar",
      "Franquiciar",
    ],
    answer: 2,
    explain: "Pivotar es cambiar una parte importante del modelo de negocio a partir de lo aprendido con los clientes, sin abandonar el emprendimiento.",
  },
  {
    id: "tq-emprendimiento-05",
    topic: "emprendimiento",
    level: 1,
    q: "Para emitir boletas y facturas en Perú, una emprendedora de Huancayo primero necesita obtener en la SUNAT su:",
    options: [
      "Licencia de funcionamiento",
      "Registro de marca",
      "Registro sanitario",
      "RUC",
    ],
    answer: 3,
    explain: "El RUC es el registro ante la SUNAT que identifica al contribuyente y le permite emitir comprobantes de pago. La licencia de funcionamiento la otorga la municipalidad.",
  },
  {
    id: "tq-emprendimiento-06",
    topic: "emprendimiento",
    level: 1,
    q: "Un emprendedor de Trujillo tiene 3 minutos frente a inversionistas para explicar el problema, su solución, el mercado y lo que pide. Esa presentación breve es un:",
    options: [
      "Pitch",
      "Plan operativo",
      "Estudio de mercado",
      "Contrato de inversión",
    ],
    answer: 0,
    explain: "El pitch es una presentación corta y persuasiva para despertar el interés de inversionistas, clientes o jurados.",
  },
  {
    id: "tq-emprendimiento-07",
    topic: "emprendimiento",
    level: 1,
    q: "Antes de invertir sus ahorros, un emprendedor de Piura entrevista a 30 posibles clientes y consigue 10 pedidos pagados por adelantado. ¿Qué está haciendo?",
    options: [
      "Escalando el negocio",
      "Pivotando el modelo",
      "Validando su idea con clientes reales",
      "Formalizando la empresa",
    ],
    answer: 2,
    explain: "Validar es comprobar con clientes reales, y mejor si pagan, que el problema existe y que tu solución interesa, antes de invertir fuerte.",
  },
  {
    id: "tq-emprendimiento-08",
    topic: "emprendimiento",
    level: 1,
    q: "Una plataforma de cursos en línea de Lima puede pasar de 100 a 10,000 alumnos sin que sus costos crezcan en la misma proporción. Eso significa que el negocio es:",
    options: [
      "Informal",
      "Escalable",
      "Estacional",
      "Intensivo en mano de obra",
    ],
    answer: 1,
    explain: "Un negocio es escalable cuando sus ingresos pueden crecer mucho más rápido que sus costos.",
  },
  {
    id: "tq-emprendimiento-09",
    topic: "emprendimiento",
    level: 1,
    q: "Una emprendedora de Arequipa quiere proteger el nombre y el logo de su marca de chocolates para que nadie más los use. ¿Ante qué entidad los registra en Perú?",
    options: [
      "Indecopi",
      "SUNAT",
      "SUNAFIL",
      "SBS",
    ],
    answer: 0,
    explain: "En Perú las marcas se registran ante Indecopi, lo que da el derecho exclusivo de uso en las clases registradas.",
  },
  {
    id: "tq-emprendimiento-10",
    topic: "emprendimiento",
    level: 1,
    q: "Dos amigos de Chiclayo inician su negocio solo con sus ahorros y reinvirtiendo las primeras ventas, sin préstamos ni inversionistas. Esa forma de financiarse se llama:",
    options: [
      "Capital de riesgo",
      "Crédito hipotecario",
      "Factoring",
      "Financiamiento propio (bootstrapping)",
    ],
    answer: 3,
    explain: "Financiarse con recursos propios y con las ventas del negocio se conoce como bootstrapping. Se crece más lento, pero sin deudas ni ceder propiedad.",
  },
  {
    id: "tq-emprendimiento-11",
    topic: "emprendimiento",
    level: 2,
    q: "Una emprendedora de Lima vende tortas a S/ 50, su costo variable es S/ 30 por torta y sus costos fijos son S/ 2,000 al mes. ¿Cuántas tortas debe vender al mes para no ganar ni perder?",
    options: [
      "40",
      "100",
      "67",
      "25",
    ],
    answer: 1,
    explain: "Margen por torta: 50 - 30 = S/ 20. Punto de equilibrio: 2,000 / 20 = 100 tortas al mes.",
  },
  {
    id: "tq-emprendimiento-12",
    topic: "emprendimiento",
    level: 2,
    q: "Un inversionista ángel aporta S/ 50,000 a cambio del 20 % de una startup de Lima. ¿En cuánto queda valorizada la empresa después de la inversión?",
    options: [
      "S/ 250,000",
      "S/ 200,000",
      "S/ 100,000",
      "S/ 1,000,000",
    ],
    answer: 0,
    explain: "Si S/ 50,000 equivalen a 20 %, el 100 % vale 50,000 / 0.20 = S/ 250,000. Esa es la valorización después de la inversión. Antes de ella era S/ 200,000.",
  },
  {
    id: "tq-emprendimiento-13",
    topic: "emprendimiento",
    level: 2,
    q: "Una startup de Medellín tiene 60,000 dólares en caja y cada mes gasta 10,000 dólares más de lo que ingresa. ¿Cuántos meses puede operar sin nuevo financiamiento?",
    options: [
      "10 meses",
      "3 meses",
      "6 meses",
      "12 meses",
    ],
    answer: 2,
    explain: "Meses de caja = caja disponible entre el déficit mensual: 60,000 / 10,000 = 6 meses.",
  },
  {
    id: "tq-emprendimiento-14",
    topic: "emprendimiento",
    level: 2,
    q: "Un emprendedor de Tarapoto vende chocolates a S/ 12 la unidad. Cada uno le cuesta S/ 5 en insumos y S/ 1 en empaque. ¿Cuál es su margen de contribución por unidad?",
    options: [
      "S/ 7",
      "S/ 11",
      "S/ 18",
      "S/ 6",
    ],
    answer: 3,
    explain: "Costo variable: 5 + 1 = S/ 6. Margen de contribución: 12 - 6 = S/ 6 por unidad.",
  },
  {
    id: "tq-emprendimiento-15",
    topic: "emprendimiento",
    level: 2,
    q: "Un emprendedor de Arequipa muestra su prototipo a 50 personas de su público objetivo y 10 pagan una preventa. ¿Qué porcentaje validó con pago?",
    options: [
      "20 %",
      "5 %",
      "10 %",
      "40 %",
    ],
    answer: 0,
    explain: "10 / 50 = 0.20, es decir 20 %. Una preventa pagada es una señal mucho más fuerte que un «me gusta».",
  },
  {
    id: "tq-emprendimiento-16",
    topic: "emprendimiento",
    level: 2,
    q: "Una juguería de Piura requiere una inversión de S/ 24,000 y se espera que deje S/ 2,000 de utilidad neta al mes. Sin considerar intereses, ¿en cuánto tiempo se recupera la inversión?",
    options: [
      "24 meses",
      "12 meses",
      "8 meses",
      "6 meses",
    ],
    answer: 1,
    explain: "Periodo de recuperación = inversión entre utilidad mensual: 24,000 / 2,000 = 12 meses.",
  },
  {
    id: "tq-emprendimiento-17",
    topic: "emprendimiento",
    level: 2,
    q: "Dos fundadoras de Lima tienen 50 % de su empresa cada una. Entra un inversionista que recibe 20 % mediante acciones nuevas. ¿Con qué porcentaje queda cada fundadora?",
    options: [
      "30 %",
      "50 %",
      "40 %",
      "45 %",
    ],
    answer: 2,
    explain: "Las fundadoras se reparten el 80 % restante en partes iguales: 80 / 2 = 40 % cada una. Eso se llama dilución.",
  },
  {
    id: "tq-emprendimiento-18",
    topic: "emprendimiento",
    level: 2,
    q: "Un emprendimiento de polos de Gamarra tiene costos fijos de S/ 3,000 al mes y un costo variable de S/ 20 por polo. Si produce 200 polos, ¿cuál es su costo total del mes?",
    options: [
      "S/ 4,000",
      "S/ 3,020",
      "S/ 6,000",
      "S/ 7,000",
    ],
    answer: 3,
    explain: "Costo variable total: 200 x 20 = S/ 4,000. Costo total: 3,000 + 4,000 = S/ 7,000.",
  },
  {
    id: "tq-emprendimiento-19",
    topic: "emprendimiento",
    level: 2,
    q: "Un emprendedor de Cusco vende a S/ 40 un producto con costo variable de S/ 25 y tiene costos fijos de S/ 3,000 al mes. Si vende 300 unidades, ¿cuál es su utilidad operativa mensual?",
    options: [
      "S/ 1,500",
      "S/ 4,500",
      "S/ 9,000",
      "S/ 12,000",
    ],
    answer: 0,
    explain: "Margen de contribución: 300 x (40 - 25) = S/ 4,500. Utilidad: 4,500 - 3,000 = S/ 1,500.",
  },
  {
    id: "tq-emprendimiento-20",
    topic: "emprendimiento",
    level: 2,
    q: "Una caja municipal presta S/ 10,000 a una emprendedora de Huancayo con una tasa de 2 % mensual. ¿Cuánto interés se genera el primer mes?",
    options: [
      "S/ 20",
      "S/ 200",
      "S/ 2,000",
      "S/ 2,400",
    ],
    answer: 1,
    explain: "Interés del primer mes = 2 % de 10,000 = 0.02 x 10,000 = S/ 200.",
  },
  {
    id: "tq-emprendimiento-21",
    topic: "emprendimiento",
    level: 2,
    q: "Una app de Santiago de Chile tiene 500 suscriptores que pagan el equivalente a S/ 30 al mes. ¿Cuál es su ingreso recurrente mensual?",
    options: [
      "S/ 1,500",
      "S/ 150,000",
      "S/ 15,000",
      "S/ 180,000",
    ],
    answer: 2,
    explain: "Ingreso recurrente mensual = suscriptores por precio: 500 x 30 = S/ 15,000.",
  },
  {
    id: "tq-emprendimiento-22",
    topic: "emprendimiento",
    level: 2,
    q: "Un emprendimiento de Lima vendió S/ 8,000 en marzo y S/ 10,000 en abril. ¿Cuánto crecieron sus ventas de un mes a otro?",
    options: [
      "20 %",
      "2 %",
      "80 %",
      "25 %",
    ],
    answer: 3,
    explain: "Crecimiento = (10,000 - 8,000) / 8,000 = 2,000 / 8,000 = 25 %. Se divide entre el mes inicial.",
  },
  {
    id: "tq-emprendimiento-23",
    topic: "emprendimiento",
    level: 3,
    q: "Una emprendedora de Lima tiene S/ 30,000 y una idea de app para lavanderías. Opción A: gastar S/ 28,000 en desarrollar la app completa. Opción B: probar un mes tomando pedidos por WhatsApp con S/ 2,000. ¿Qué recomienda el enfoque de validación?",
    options: [
      "La opción A: sin la app completa no se puede saber si hay clientes",
      "La opción B: comprobar si hay demanda con poco dinero antes de construir la app",
      "La opción A: gastar más demuestra compromiso ante los inversionistas",
      "Ninguna: primero debe conseguir un inversionista que pague la app",
    ],
    answer: 1,
    explain: "Validar primero con S/ 2,000 permite saber si las lavanderías usan y pagan el servicio. Si la idea falla, conserva S/ 28,000 para ajustar o probar otra.",
  },
  {
    id: "tq-emprendimiento-24",
    topic: "emprendimiento",
    level: 3,
    q: "Una startup de Lima ofrece un software de reservas a restaurantes. Tras 6 meses, solo pagan 5 de 200 restaurantes contactados, pero 40 peluquerías lo pidieron sin que nadie les vendiera. ¿Qué decisión tiene más sustento?",
    options: [
      "Pivotar de segmento hacia las peluquerías, donde hay demanda espontánea",
      "Perseverar con los restaurantes y duplicar la publicidad",
      "Cerrar la empresa, porque el producto fracasó",
      "Rechazar a las peluquerías, porque no son el segmento del plan",
    ],
    answer: 0,
    explain: "5 de 200 es 2.5 % de conversión con esfuerzo de venta, mientras que 40 peluquerías llegaron solas. La demanda espontánea es la mejor señal de a quién servir.",
  },
  {
    id: "tq-emprendimiento-25",
    topic: "emprendimiento",
    level: 3,
    q: "Negocio A: una consultoría donde cada cliente nuevo exige contratar a otro consultor. Negocio B: un curso grabado que se vende en línea sin costo extra por alumno. Ambos venden S/ 20,000 al mes. ¿Cuál es más escalable?",
    options: [
      "A, porque el servicio personalizado se cobra a mejor precio",
      "Ambos por igual, porque hoy venden lo mismo",
      "B, porque sus ventas pueden crecer sin que sus costos crezcan al mismo ritmo",
      "A, porque contratar más personal es señal de crecimiento",
    ],
    answer: 2,
    explain: "En A cada venta adicional exige más planilla, así que el costo crece con el ingreso. En B atender a un alumno más casi no cuesta, por eso escala.",
  },
  {
    id: "tq-emprendimiento-26",
    topic: "emprendimiento",
    level: 3,
    q: "Un taller de confecciones de Gamarra vende sin RUC. Una cadena de tiendas le ofrece un pedido grande, pero exige factura. El dueño teme pagar impuestos. ¿Cuál es el análisis correcto?",
    options: [
      "Seguir informal, porque emitir factura nunca trae beneficios",
      "Pedir a otro negocio que facture por él para no formalizarse",
      "Rechazar el pedido, porque vender a cadenas no conviene a un taller",
      "Formalizarse le abre clientes grandes y crédito que hoy no puede obtener",
    ],
    answer: 3,
    explain: "La informalidad ahorra impuestos hoy, pero cierra el acceso a clientes que exigen factura, al crédito formal y a las compras del Estado.",
  },
  {
    id: "tq-emprendimiento-27",
    topic: "emprendimiento",
    level: 3,
    q: "Una cafetería rentable de Arequipa, con flujo estable, necesita S/ 40,000 para equiparse. Un inversionista pide 40 % de la empresa por ese monto y una caja municipal le ofrece un préstamo. ¿Qué criterio es más sólido?",
    options: [
      "Preferir el préstamo si la cuota cabe en su flujo, porque no cede propiedad",
      "Aceptar al inversionista, porque el capital de un socio no cuesta nada",
      "Rechazar ambos, porque un negocio no debe crecer con dinero ajeno",
      "Aceptar al inversionista, porque así no tendrá que compartir utilidades",
    ],
    answer: 0,
    explain: "Ceder 40 % de una empresa rentable por S/ 40,000 es caro si el negocio puede pagar una deuda. El préstamo se termina de pagar, la participación se entrega para siempre.",
  },
  {
    id: "tq-emprendimiento-28",
    topic: "emprendimiento",
    level: 3,
    q: "Una app de delivery de Lima cobra S/ 5 de comisión por pedido, pero paga S/ 6 al repartidor y S/ 1 a la pasarela de pago. Planea «ganar por volumen» multiplicando sus pedidos por 10. ¿Qué ocurrirá?",
    options: [
      "Gana S/ 5 por pedido, así que más volumen multiplica la ganancia",
      "Pierde S/ 2 por pedido, así que más volumen multiplica la pérdida",
      "Pierde S/ 1 por pedido, pero el volumen lo compensa",
      "Queda en equilibrio, porque el volumen diluye el costo por pedido",
    ],
    answer: 1,
    explain: "Ingreso de S/ 5 menos costos de S/ 7 (6 + 1) deja una pérdida de S/ 2 por pedido. Con 10 veces más pedidos la pérdida también se multiplica por 10.",
  },
  {
    id: "tq-emprendimiento-29",
    topic: "emprendimiento",
    level: 3,
    q: "Un emprendedor de Trujillo vende jugos «para todos» con el mismo mensaje y vende poco. Al entrevistar a sus clientes, nota que 70 % son deportistas que compran después de entrenar. ¿Qué ajuste conviene?",
    options: [
      "Ampliar aún más el público para no perder a nadie",
      "Bajar el precio a la mitad para todos los segmentos",
      "Enfocar la propuesta de valor en deportistas y vender cerca de gimnasios",
      "Cambiar de producto, porque los jugos no tienen mercado",
    ],
    answer: 2,
    explain: "Venderle a todos suele significar no convencer a nadie. Los datos muestran un segmento claro: conviene enfocar mensaje, producto y ubicación en los deportistas.",
  },
  {
    id: "tq-emprendimiento-30",
    topic: "emprendimiento",
    level: 3,
    q: "En su pitch, una emprendedora de Cusco dedica 4 de sus 5 minutos a explicar la tecnología y termina sin decir cuánto dinero pide ni para qué. ¿Cuál es la falla más grave para un inversionista?",
    options: [
      "Dedicó muy poco tiempo a explicar la tecnología",
      "No mostró el organigrama completo de la empresa",
      "No leyó el plan de negocio completo durante el pitch",
      "No presenta el pedido de inversión ni el uso que dará a los fondos",
    ],
    answer: 3,
    explain: "El inversionista necesita saber cuánto pides, para qué y qué lograrás con ese dinero. Un pitch equilibra problema, solución, mercado, equipo y pedido.",
  },
];

export default data;
