import type { TriviaQ } from "../types";

/**
 * Banco A de trivia: 150 preguntas, 30 por tema (finanzas, contabilidad,
 * tributos, operaciones y personas). Por tema: 10 de nivel 1, 12 de nivel 2
 * y 8 de nivel 3.
 */
const data: TriviaQ[] = [
  // ==================== FINANZAS ====================
  {
    id: "tq-finanzas-01",
    topic: "finanzas",
    level: 1,
    q: "Una bodega de Chiclayo tiene S/ 5,000 en caja y esta semana debe pagar S/ 8,000 a sus proveedores. ¿Qué problema financiero enfrenta?",
    options: [
      "De rentabilidad",
      "De liquidez",
      "De apalancamiento operativo",
      "De depreciación",
    ],
    answer: 1,
    explain: "La liquidez es la capacidad de pagar las obligaciones de corto plazo con el efectivo disponible. La bodega puede ser rentable, pero hoy su caja no cubre los pagos inmediatos.",
  },
  {
    id: "tq-finanzas-02",
    topic: "finanzas",
    level: 1,
    q: "Una pastelería de Arequipa evalúa comprar un horno nuevo y el VAN del proyecto sale positivo. ¿Qué significa ese resultado?",
    options: [
      "Que el proyecto crea valor por encima del rendimiento mínimo exigido",
      "Que recupera la inversión en menos de un año",
      "Que la utilidad contable será positiva todos los años",
      "Que la empresa ya no necesitará financiamiento",
    ],
    answer: 0,
    explain: "El VAN trae los flujos futuros a valor de hoy con la tasa exigida y les resta la inversión. Si es positivo, el proyecto rinde más que esa tasa mínima y crea valor.",
  },
  {
    id: "tq-finanzas-03",
    topic: "finanzas",
    level: 1,
    q: "Un instituto de Trujillo evalúa abrir una sede. La TIR del proyecto es 18 % y su costo de capital es 12 %. ¿Qué conviene concluir?",
    options: [
      "Rechazarlo, porque una TIR alta significa que el proyecto es caro",
      "Es indiferente, porque la TIR no se compara con ninguna tasa",
      "Aceptarlo, porque la TIR supera al costo de capital",
      "Aceptarlo solo si el VAN resulta negativo",
    ],
    answer: 2,
    explain: "La TIR es el rendimiento anual que genera el proyecto. Como 18 % supera el 12 % que cuesta financiarlo, el proyecto rinde más de lo que cuesta y conviene aceptarlo.",
  },
  {
    id: "tq-finanzas-04",
    topic: "finanzas",
    level: 1,
    q: "El dueño de un minimarket de Piura quiere conocer su capital de trabajo neto. ¿Cómo se calcula?",
    options: [
      "Activo total menos pasivo total",
      "Ventas menos costo de ventas",
      "Caja más cuentas por cobrar",
      "Activo corriente menos pasivo corriente",
    ],
    answer: 3,
    explain: "El capital de trabajo neto muestra cuánto del activo de corto plazo queda después de cubrir las deudas de corto plazo. Activo total menos pasivo total es el patrimonio, no el capital de trabajo.",
  },
  {
    id: "tq-finanzas-05",
    topic: "finanzas",
    level: 1,
    q: "Un taller de confecciones de Gamarra vende mucho al crédito y tiene utilidad, pero no le alcanza el efectivo para pagar la planilla. ¿Qué herramienta le habría advertido del problema a tiempo?",
    options: [
      "El flujo de caja proyectado",
      "El organigrama de la empresa",
      "El estado de cambios en el patrimonio",
      "El registro de compras",
    ],
    answer: 0,
    explain: "El flujo de caja proyectado muestra cuándo entra y cuándo sale el efectivo. Vender al crédito genera utilidad, pero el dinero llega después y la planilla se paga en efectivo.",
  },
  {
    id: "tq-finanzas-06",
    topic: "finanzas",
    level: 1,
    q: "Depositas tus ahorros a plazo fijo en una caja municipal de Arequipa. ¿Qué distingue al interés compuesto del interés simple?",
    options: [
      "El compuesto se calcula siempre sobre el capital inicial",
      "En el compuesto, los intereses ganados se suman al capital y también generan intereses",
      "El simple paga más que el compuesto en plazos largos",
      "El compuesto solo existe en los préstamos, no en los depósitos",
    ],
    answer: 1,
    explain: "Con interés compuesto los intereses se capitalizan, es decir, pasan a formar parte del capital. Por eso el saldo crece más rápido que con interés simple, que siempre se calcula sobre el capital inicial.",
  },
  {
    id: "tq-finanzas-07",
    topic: "finanzas",
    level: 1,
    q: "Dos entidades te ofrecen un préstamo para tu negocio: una informa su tasa mensual y la otra su tasa trimestral. ¿Qué indicador te permite comparar ambas ofertas en la misma base?",
    options: [
      "El monto de la cuota inicial",
      "El plazo de gracia",
      "La tasa efectiva anual (TEA)",
      "El monto total del préstamo",
    ],
    answer: 2,
    explain: "La TEA expresa el costo del dinero en un año considerando la capitalización de los intereses. Al llevar todas las tasas a TEA puedes compararlas sin confundirte por el periodo.",
  },
  {
    id: "tq-finanzas-08",
    topic: "finanzas",
    level: 1,
    q: "¿Cuándo alcanza su punto de equilibrio una pollería de Huancayo?",
    options: [
      "Cuando vende más que su principal competidor",
      "Cuando termina de pagar todas sus deudas",
      "Cuando sus costos fijos llegan a cero",
      "Cuando sus ventas cubren exactamente sus costos totales, sin ganar ni perder",
    ],
    answer: 3,
    explain: "En el punto de equilibrio los ingresos igualan a los costos fijos más los variables, por lo que la utilidad es cero. Cada venta por encima de ese nivel deja ganancia.",
  },
  {
    id: "tq-finanzas-09",
    topic: "finanzas",
    level: 1,
    q: "El gerente de una empresa de courier de Lima quiere medir el resultado de la operación antes de intereses, impuestos, depreciación y amortización. ¿Qué indicador debe usar?",
    options: [
      "Utilidad neta",
      "EBITDA",
      "Capital de trabajo",
      "Razón corriente",
    ],
    answer: 1,
    explain: "El EBITDA es la utilidad antes de intereses, impuestos, depreciación y amortización. Permite ver cuánto genera la operación sin el efecto de la deuda, los tributos ni los cargos que no son salida de efectivo.",
  },
  {
    id: "tq-finanzas-10",
    topic: "finanzas",
    level: 1,
    q: "Una agencia de turismo de Cusco compra una van con un préstamo bancario en lugar de usar solo el dinero de los socios. ¿Cómo se llama el uso de deuda para financiar activos?",
    options: [
      "Depreciación acelerada",
      "Capitalización de utilidades",
      "Apalancamiento financiero",
      "Liquidez corriente",
    ],
    answer: 2,
    explain: "Apalancarse es usar deuda para financiar activos. Si el activo rinde más que el costo de la deuda, mejora la rentabilidad de los socios, pero también aumenta el riesgo por las cuotas fijas.",
  },
  {
    id: "tq-finanzas-11",
    topic: "finanzas",
    level: 2,
    q: "Le prestas S/ 10,000 a un socio a interés simple de 2 % mensual durante 6 meses. ¿Cuánto interés ganas en total?",
    options: [
      "S/ 1,200",
      "S/ 200",
      "S/ 1,262",
      "S/ 12,000",
    ],
    answer: 0,
    explain: "Interés simple = capital x tasa x tiempo: 10,000 x 0.02 x 6 = S/ 1,200. No hay capitalización, por eso cada mes se gana lo mismo (S/ 200).",
  },
  {
    id: "tq-finanzas-12",
    topic: "finanzas",
    level: 2,
    q: "Depositas S/ 1,000 en una cooperativa de Cusco a 10 % anual con capitalización anual. ¿Cuánto tendrás al final del segundo año?",
    options: [
      "S/ 1,200",
      "S/ 1,210",
      "S/ 1,100",
      "S/ 1,020",
    ],
    answer: 1,
    explain: "Año 1: 1,000 x 1.10 = 1,100. Año 2: 1,100 x 1.10 = S/ 1,210. Los S/ 10 adicionales frente al interés simple son los intereses ganados sobre los intereses del primer año.",
  },
  {
    id: "tq-finanzas-13",
    topic: "finanzas",
    level: 2,
    q: "Una cafetería de Cusco tiene costos fijos de S/ 12,000 al mes. Vende cada café a S/ 10 y su costo variable es S/ 4. ¿Cuántos cafés debe vender al mes para llegar al punto de equilibrio?",
    options: [
      "1,200 cafés",
      "3,000 cafés",
      "2,000 cafés",
      "857 cafés",
    ],
    answer: 2,
    explain: "Cada café deja un margen de contribución de 10 menos 4 = S/ 6. Punto de equilibrio = 12,000 / 6 = 2,000 cafés. El error típico es dividir entre el precio o entre el costo variable.",
  },
  {
    id: "tq-finanzas-14",
    topic: "finanzas",
    level: 2,
    q: "Una botica de Tacna tiene activo corriente de S/ 60,000 y pasivo corriente de S/ 40,000. ¿Cuál es su razón corriente?",
    options: [
      "0.67",
      "1.5",
      "2.5",
      "S/ 20,000",
    ],
    answer: 1,
    explain: "Razón corriente = activo corriente / pasivo corriente = 60,000 / 40,000 = 1.5. Tiene S/ 1.50 de activo corriente por cada sol de deuda de corto plazo. Los S/ 20,000 son el capital de trabajo, no la razón.",
  },
  {
    id: "tq-finanzas-15",
    topic: "finanzas",
    level: 2,
    q: "Una ferretería de Piura tiene caja por S/ 8,000, cuentas por cobrar por S/ 12,000, inventarios por S/ 20,000 y deudas de corto plazo por S/ 25,000. ¿Cuál es su capital de trabajo neto?",
    options: [
      "S/ 15,000",
      "S/ 40,000",
      "S/ 65,000",
      "S/ 20,000",
    ],
    answer: 0,
    explain: "Activo corriente = 8,000 + 12,000 + 20,000 = 40,000. Capital de trabajo neto = 40,000 menos 25,000 = S/ 15,000. Los inventarios también forman parte del activo corriente.",
  },
  {
    id: "tq-finanzas-16",
    topic: "finanzas",
    level: 2,
    q: "Una empresa de limpieza de Lima tiene una utilidad operativa de S/ 50,000, calculada después de restar S/ 10,000 de depreciación y S/ 5,000 de amortización. ¿Cuál es su EBITDA?",
    options: [
      "S/ 35,000",
      "S/ 50,000",
      "S/ 60,000",
      "S/ 65,000",
    ],
    answer: 3,
    explain: "EBITDA = utilidad operativa + depreciación + amortización = 50,000 + 10,000 + 5,000 = S/ 65,000. Se suman porque son gastos que no implican salida de efectivo.",
  },
  {
    id: "tq-finanzas-17",
    topic: "finanzas",
    level: 2,
    q: "Una empresa del régimen general paga 10 % anual por un préstamo. Los intereses son gasto deducible y su tasa de impuesto a la renta es 29.5 %. ¿Cuál es el costo de la deuda después de impuestos?",
    options: [
      "7.05 %",
      "2.95 %",
      "12.95 %",
      "10 %",
    ],
    answer: 0,
    explain: "Costo después de impuestos = 10 % x (1 menos 0.295) = 10 % x 0.705 = 7.05 %. El ahorro tributario por deducir los intereses (2.95 %) reduce el costo real de la deuda.",
  },
  {
    id: "tq-finanzas-18",
    topic: "finanzas",
    level: 2,
    q: "Inviertes S/ 1,000 hoy en un negocio de temporada y recibes S/ 1,320 dentro de un año. Con una tasa de descuento de 10 % anual, ¿cuál es el VAN?",
    options: [
      "S/ 320",
      "S/ 200",
      "S/ 1,200",
      "S/ 120",
    ],
    answer: 1,
    explain: "Valor presente del cobro = 1,320 / 1.10 = 1,200. VAN = 1,200 menos 1,000 = S/ 200. Restar sin descontar (S/ 320) ignora el valor del dinero en el tiempo.",
  },
  {
    id: "tq-finanzas-19",
    topic: "finanzas",
    level: 2,
    q: "Un gimnasio de Chiclayo invierte S/ 60,000 en máquinas que generan un flujo neto de S/ 15,000 por año. Sin descontar los flujos, ¿en cuánto tiempo recupera la inversión?",
    options: [
      "3 años",
      "5 años",
      "2.5 años",
      "4 años",
    ],
    answer: 3,
    explain: "Periodo de recuperación = inversión / flujo anual = 60,000 / 15,000 = 4 años. Es un indicador simple de riesgo, pero no mide el valor creado como sí lo hace el VAN.",
  },
  {
    id: "tq-finanzas-20",
    topic: "finanzas",
    level: 2,
    q: "Un prestamista informal de un mercado de Lima cobra 10 % mensual y capitaliza los intereses cada mes. ¿A cuánto equivale esa tasa en términos efectivos anuales?",
    options: [
      "Exactamente 120 %",
      "Exactamente 10 %",
      "Cerca de 214 %",
      "Cerca de 100 %",
    ],
    answer: 2,
    explain: "TEA = 1.10 elevado a la 12, menos 1 = 3.14 menos 1, es decir, cerca de 214 %. Multiplicar 10 % por 12 da 120 %, pero eso ignora la capitalización mensual de los intereses.",
  },
  {
    id: "tq-finanzas-21",
    topic: "finanzas",
    level: 2,
    q: "Una tienda en línea de Lima tiene costos fijos de S/ 20,000 al mes y un margen de contribución de 40 % sobre sus ventas. ¿Cuánto debe vender al mes para no perder?",
    options: [
      "S/ 8,000",
      "S/ 28,000",
      "S/ 50,000",
      "S/ 33,333",
    ],
    answer: 2,
    explain: "Ventas de equilibrio = costos fijos / margen de contribución = 20,000 / 0.40 = S/ 50,000. Con esa venta, el 40 % que queda (S/ 20,000) cubre exactamente los costos fijos.",
  },
  {
    id: "tq-finanzas-22",
    topic: "finanzas",
    level: 2,
    q: "Una empresa de Huancayo tiene activos por S/ 200,000, financiados con S/ 80,000 de deuda y el resto con aportes de los socios. ¿Cuál es su razón de endeudamiento (deuda sobre activos)?",
    options: [
      "40 %",
      "60 %",
      "67 %",
      "250 %",
    ],
    answer: 0,
    explain: "Razón de endeudamiento = deuda / activos = 80,000 / 200,000 = 40 %. El 60 % restante lo financia el patrimonio. El 67 % resulta de dividir la deuda entre el patrimonio, que es otro ratio.",
  },
  {
    id: "tq-finanzas-23",
    topic: "finanzas",
    level: 3,
    q: "Una agroexportadora de Ica compara dos proyectos excluyentes, con la misma inversión y un costo de capital de 12 %. El proyecto A tiene TIR de 25 % y VAN de S/ 40,000. El B tiene TIR de 18 % y VAN de S/ 90,000. ¿Cuál conviene elegir?",
    options: [
      "El A, porque tiene la TIR más alta",
      "Cualquiera, porque ambos superan el 12 %",
      "Ninguno, porque TIR y VAN se contradicen",
      "El B, porque crea más valor en soles (mayor VAN)",
    ],
    answer: 3,
    explain: "Cuando los proyectos son excluyentes y los criterios discrepan, manda el VAN, porque mide cuánto valor en soles se crea. La TIR es un porcentaje y no refleja el tamaño ni el momento de los flujos.",
  },
  {
    id: "tq-finanzas-24",
    topic: "finanzas",
    level: 3,
    q: "Una pastelería de Lima necesita S/ 30,000 por tres meses para la campaña navideña. Puede usar un sobregiro con TEA de 60 % o un préstamo de capital de trabajo con TEA de 25 %, ambos disponibles a tiempo. ¿Qué le conviene?",
    options: [
      "El sobregiro, porque al no requerir trámite resulta más barato",
      "El préstamo de capital de trabajo, porque cuesta menos por el mismo monto y plazo",
      "El sobregiro, porque una TEA más alta refleja un mejor crédito",
      "Ninguno, mejor atrasar el pago a proveedores y a la planilla",
    ],
    answer: 1,
    explain: "A igual monto y plazo conviene la menor TEA: 25 % frente a 60 %. El sobregiro es una salida de emergencia muy cara, y atrasar pagos daña la relación con proveedores y trabajadores.",
  },
  {
    id: "tq-finanzas-25",
    topic: "finanzas",
    level: 3,
    q: "Una distribuidora de Trujillo duplica sus ventas, todas al crédito a 90 días, mientras paga a sus proveedores a 30 días. Tiene utilidad, pero la caja se agota. ¿Cuál es la causa principal?",
    options: [
      "El crecimiento elevó su necesidad de capital de trabajo: paga mucho antes de cobrar",
      "La depreciación de sus activos consume el efectivo cada mes",
      "Vende por debajo del costo, por eso pierde en cada venta",
      "El impuesto a la renta supera el monto de sus ventas",
    ],
    answer: 0,
    explain: "Si cobras a 90 días y pagas a 30, financias 60 días de operación con tu propia caja. Al duplicar ventas, ese descalce también se duplica. Crecer sin financiar el capital de trabajo puede quebrar a una empresa rentable.",
  },
  {
    id: "tq-finanzas-26",
    topic: "finanzas",
    level: 3,
    q: "Una empresa de Arequipa obtiene un rendimiento de 15 % sobre sus activos y puede endeudarse a 10 % anual. Si toma deuda para crecer y mantiene ese rendimiento, ¿qué pasa con la rentabilidad de los socios?",
    options: [
      "Baja, porque toda deuda reduce la rentabilidad del patrimonio",
      "No cambia, porque la deuda no afecta a los socios",
      "Sube, porque los activos rinden más de lo que cuesta la deuda",
      "Sube solo si la tasa de la deuda supera el 15 %",
    ],
    answer: 2,
    explain: "El apalancamiento es favorable cuando el rendimiento del activo (15 %) supera el costo de la deuda (10 %): la diferencia queda para los socios. Si el rendimiento cae por debajo del costo, el efecto se invierte.",
  },
  {
    id: "tq-finanzas-27",
    topic: "finanzas",
    level: 3,
    q: "Un restaurante de Arequipa tiene costos fijos de S/ 18,000 al mes, vende el menú a S/ 15 y su costo variable es S/ 9. Si sube el precio a S/ 18 sin cambiar sus costos, ¿qué pasa con su punto de equilibrio?",
    options: [
      "Baja de 3,000 a 2,000 menús",
      "Sube de 2,000 a 3,000 menús",
      "Se mantiene en 3,000 menús",
      "Baja de 3,000 a 1,000 menús",
    ],
    answer: 0,
    explain: "Antes: 18,000 / (15 menos 9) = 3,000 menús. Después: 18,000 / (18 menos 9) = 2,000 menús. Al subir el margen por unidad se necesitan menos ventas, siempre que la demanda no caiga demasiado.",
  },
  {
    id: "tq-finanzas-28",
    topic: "finanzas",
    level: 3,
    q: "Un proyecto requiere invertir S/ 18,000 hoy y devuelve S/ 11,000 al final del año 1 y S/ 12,100 al final del año 2. Con una tasa de descuento de 10 % anual, ¿cuál es el VAN?",
    options: [
      "S/ 5,100",
      "S/ 2,000",
      "S/ 3,000",
      "S/ 1,000",
    ],
    answer: 1,
    explain: "Valor presente: 11,000 / 1.10 = 10,000 y 12,100 / 1.21 = 10,000, en total 20,000. VAN = 20,000 menos 18,000 = S/ 2,000. Sumar los flujos sin descontar daría S/ 5,100, que sobrestima el proyecto.",
  },
  {
    id: "tq-finanzas-29",
    topic: "finanzas",
    level: 3,
    q: "Una tienda de ropa de Gamarra tiene activo corriente de S/ 90,000, de los cuales S/ 60,000 son inventarios de la temporada pasada, y pasivo corriente de S/ 50,000. ¿Qué lectura de su liquidez es correcta?",
    options: [
      "Tiene liquidez de sobra, porque la razón corriente de 1.8 basta",
      "La prueba ácida es 1.8 y la razón corriente es 0.6",
      "Es insolvente, porque su pasivo corriente supera a su activo corriente",
      "Razón corriente de 1.8, pero prueba ácida de 0.6: depende de vender un inventario lento",
    ],
    answer: 3,
    explain: "Razón corriente = 90,000 / 50,000 = 1.8. Prueba ácida = (90,000 menos 60,000) / 50,000 = 0.6. Sin el inventario, que es de temporada pasada y difícil de vender, solo cubre 60 céntimos por cada sol de deuda.",
  },
  {
    id: "tq-finanzas-30",
    topic: "finanzas",
    level: 3,
    q: "Una empresa de software de Lima tiene S/ 100,000 en caja sin uso previsto y una deuda que le cuesta 18 % anual. Un depósito a plazo le pagaría 4 % anual. ¿Qué uso del dinero le conviene más?",
    options: [
      "Depositar a plazo, porque ganar intereses siempre supera a pagar deuda",
      "Dejarlo en cuenta corriente, porque mantener liquidez no tiene costo",
      "Depositar a plazo y tomar otro préstamo para pagar el primero",
      "Amortizar la deuda: se ahorra 18 %, mucho más que el 4 % del depósito",
    ],
    answer: 3,
    explain: "Cada sol usado en amortizar evita pagar 18 % al año, mientras que el depósito solo rinde 4 %. Tener efectivo ocioso tiene un costo de oportunidad cuando existe deuda más cara.",
  },
  // ==================== CONTABILIDAD ====================
  {
    id: "tq-contabilidad-01",
    topic: "contabilidad",
    level: 1,
    q: "Una panadería de Ayacucho compra un horno industrial que usará varios años. ¿Cómo se clasifica en el estado de situación financiera?",
    options: [
      "Activo corriente",
      "Pasivo corriente",
      "Activo no corriente (propiedad, planta y equipo)",
      "Patrimonio",
    ],
    answer: 2,
    explain: "El horno es un bien que la empresa controla y usará por más de un año para generar ingresos. Por eso es activo no corriente y su costo se reparte en el tiempo mediante la depreciación.",
  },
  {
    id: "tq-contabilidad-02",
    topic: "contabilidad",
    level: 1,
    q: "El contador de una bodega de Iquitos revisa que el estado de situación financiera cuadre. ¿Qué igualdad debe cumplirse siempre?",
    options: [
      "Activo = Pasivo + Patrimonio",
      "Patrimonio = Activo + Pasivo",
      "Pasivo = Activo + Patrimonio",
      "Activo + Pasivo = Ventas",
    ],
    answer: 0,
    explain: "Todo lo que la empresa tiene (activo) se financió con deudas a terceros (pasivo) o con recursos de los dueños (patrimonio). Por eso ambos lados siempre suman lo mismo.",
  },
  {
    id: "tq-contabilidad-03",
    topic: "contabilidad",
    level: 1,
    q: "Una consultora de Lima entrega un servicio en diciembre y el cliente le paga en enero. Según el principio del devengado, ¿cuándo se registra el ingreso?",
    options: [
      "En enero, cuando se cobra",
      "Mitad en diciembre y mitad en enero",
      "Cuando el dinero se deposita en el banco",
      "En diciembre, cuando se prestó el servicio",
    ],
    answer: 3,
    explain: "Por el devengado, los ingresos y gastos se registran cuando ocurren, no cuando se cobran o pagan. En diciembre se registra el ingreso junto con una cuenta por cobrar.",
  },
  {
    id: "tq-contabilidad-04",
    topic: "contabilidad",
    level: 1,
    q: "Una pollería de Chiclayo compra pollo a su proveedor con crédito a 30 días. ¿Qué cuenta aumenta por esa deuda?",
    options: [
      "Cuentas por cobrar (activo)",
      "Cuentas por pagar (pasivo)",
      "Capital social (patrimonio)",
      "Ventas (ingreso)",
    ],
    answer: 1,
    explain: "Comprar al crédito crea una obligación con el proveedor, que es un pasivo. Las cuentas por cobrar son lo contrario: lo que los clientes le deben a la empresa.",
  },
  {
    id: "tq-contabilidad-05",
    topic: "contabilidad",
    level: 1,
    q: "El dueño de un minimarket de Tarapoto quiere saber si ganó o perdió dinero durante el trimestre. ¿Qué estado financiero debe revisar?",
    options: [
      "Estado de situación financiera",
      "Estado de flujos de efectivo",
      "Estado de resultados",
      "Estado de cambios en el patrimonio",
    ],
    answer: 2,
    explain: "El estado de resultados compara los ingresos con los costos y gastos de un periodo y muestra la utilidad o pérdida. El estado de situación financiera es una foto de activos, pasivos y patrimonio a una fecha.",
  },
  {
    id: "tq-contabilidad-06",
    topic: "contabilidad",
    level: 1,
    q: "Una empresa de courier de Lima registra cada mes la depreciación de sus motos. ¿Qué representa ese registro?",
    options: [
      "Una salida de efectivo para pagar al proveedor de las motos",
      "El aumento del valor de mercado de las motos",
      "Un fondo de dinero guardado en el banco para comprar motos nuevas",
      "El desgaste del activo, repartido como gasto durante su vida útil",
    ],
    answer: 3,
    explain: "La depreciación distribuye el costo del activo entre los periodos en que se usa. Es un gasto contable que no implica salida de efectivo ni crea ningún fondo de dinero.",
  },
  {
    id: "tq-contabilidad-07",
    topic: "contabilidad",
    level: 1,
    q: "Una tienda de Gamarra compra polos y los revende. ¿Cuál de estos conceptos forma parte de su costo de ventas?",
    options: [
      "El costo de los polos que vendió",
      "El sueldo del contador",
      "La publicidad en redes sociales",
      "Los intereses del préstamo bancario",
    ],
    answer: 0,
    explain: "El costo de ventas es lo que costó la mercadería vendida. El sueldo del contador es gasto administrativo, la publicidad es gasto de ventas y los intereses son gasto financiero.",
  },
  {
    id: "tq-contabilidad-08",
    topic: "contabilidad",
    level: 1,
    q: "Los socios de una cafetería de Cusco aportan S/ 50,000 para iniciar el negocio. ¿Dónde se registra ese aporte?",
    options: [
      "En el pasivo, como deuda con el banco",
      "En el patrimonio, como capital",
      "En el estado de resultados, como ingreso por ventas",
      "En el estado de resultados, como gasto operativo",
    ],
    answer: 1,
    explain: "Los aportes de los socios son capital y forman parte del patrimonio. No son un ingreso porque no provienen de vender, ni un pasivo porque no son una deuda con terceros.",
  },
  {
    id: "tq-contabilidad-09",
    topic: "contabilidad",
    level: 1,
    q: "Una empresa de maquinaria de Arequipa vende un equipo con crédito a 60 días. ¿En qué cuenta registra su derecho a cobrar?",
    options: [
      "Cuentas por pagar comerciales",
      "Inventarios",
      "Capital social",
      "Cuentas por cobrar comerciales",
    ],
    answer: 3,
    explain: "Una venta al crédito genera un derecho de cobro al cliente, que es un activo llamado cuentas por cobrar comerciales. Cuando el cliente paga, esa cuenta baja y sube el efectivo.",
  },
  {
    id: "tq-contabilidad-10",
    topic: "contabilidad",
    level: 1,
    q: "En el estado de resultados de una botica de Piura, ¿cómo se obtiene la utilidad bruta?",
    options: [
      "Ventas menos todos los gastos e impuestos",
      "Activo menos pasivo",
      "Ventas menos costo de ventas",
      "Utilidad operativa menos gastos financieros",
    ],
    answer: 2,
    explain: "La utilidad bruta es lo que queda de las ventas después de restar el costo de lo vendido. De ella se restan luego los gastos operativos, los financieros y el impuesto para llegar a la utilidad neta.",
  },
  {
    id: "tq-contabilidad-11",
    topic: "contabilidad",
    level: 2,
    q: "Una lavandería de Lima compra una máquina en S/ 24,000, con vida útil de 4 años y sin valor residual. Con el método de línea recta, ¿cuánto es la depreciación mensual?",
    options: [
      "S/ 6,000",
      "S/ 500",
      "S/ 2,000",
      "S/ 1,000",
    ],
    answer: 1,
    explain: "Depreciación anual = 24,000 / 4 = 6,000. Depreciación mensual = 6,000 / 12 = S/ 500. El error común es responder con el monto anual.",
  },
  {
    id: "tq-contabilidad-12",
    topic: "contabilidad",
    level: 2,
    q: "Una librería de Huancayo inicia el mes con un inventario de S/ 10,000, compra mercadería por S/ 30,000 y termina con un inventario de S/ 8,000. ¿Cuál fue su costo de ventas?",
    options: [
      "S/ 48,000",
      "S/ 28,000",
      "S/ 30,000",
      "S/ 32,000",
    ],
    answer: 3,
    explain: "Costo de ventas = inventario inicial + compras menos inventario final = 10,000 + 30,000 menos 8,000 = S/ 32,000. Las compras del mes no son el costo de ventas, porque parte queda en almacén.",
  },
  {
    id: "tq-contabilidad-13",
    topic: "contabilidad",
    level: 2,
    q: "Una juguería de Trujillo vende S/ 80,000 en el trimestre, con un costo de ventas de S/ 48,000. ¿Cuál es su margen bruto?",
    options: [
      "60 %",
      "67 %",
      "40 %",
      "32 %",
    ],
    answer: 2,
    explain: "Utilidad bruta = 80,000 menos 48,000 = 32,000. Margen bruto = 32,000 / 80,000 = 40 %. El margen se calcula sobre las ventas, no sobre el costo.",
  },
  {
    id: "tq-contabilidad-14",
    topic: "contabilidad",
    level: 2,
    q: "Una empresa de Tacna tiene activos por S/ 150,000 y pasivos por S/ 90,000. ¿A cuánto asciende su patrimonio?",
    options: [
      "S/ 60,000",
      "S/ 240,000",
      "S/ 90,000",
      "S/ 150,000",
    ],
    answer: 0,
    explain: "De la ecuación contable, patrimonio = activo menos pasivo = 150,000 menos 90,000 = S/ 60,000. Es la parte de los activos que pertenece a los dueños.",
  },
  {
    id: "tq-contabilidad-15",
    topic: "contabilidad",
    level: 2,
    q: "Una academia de Arequipa tiene ventas por S/ 100,000, costo de ventas de S/ 55,000 y gastos de administración y de ventas por S/ 25,000. ¿Cuál es su utilidad operativa?",
    options: [
      "S/ 45,000",
      "S/ 75,000",
      "S/ 20,000",
      "S/ 30,000",
    ],
    answer: 2,
    explain: "Utilidad bruta = 100,000 menos 55,000 = 45,000. Utilidad operativa = 45,000 menos 25,000 = S/ 20,000. Los S/ 45,000 son la utilidad bruta, antes de los gastos operativos.",
  },
  {
    id: "tq-contabilidad-16",
    topic: "contabilidad",
    level: 2,
    q: "Una bodega de Pucallpa tiene un costo de ventas anual de S/ 360,000 y un inventario promedio de S/ 30,000. ¿Cuántas veces rota su inventario al año?",
    options: [
      "12 veces",
      "10 veces",
      "30 veces",
      "0.08 veces",
    ],
    answer: 0,
    explain: "Rotación de inventarios = costo de ventas / inventario promedio = 360,000 / 30,000 = 12 veces al año, es decir, renueva su inventario cada mes aproximadamente.",
  },
  {
    id: "tq-contabilidad-17",
    topic: "contabilidad",
    level: 2,
    q: "Una empresa de Lima vende S/ 720,000 al año, todo al crédito, y sus cuentas por cobrar promedio son S/ 120,000. Con un año de 360 días, ¿cada cuántos días cobra en promedio?",
    options: [
      "30 días",
      "60 días",
      "6 días",
      "90 días",
    ],
    answer: 1,
    explain: "Periodo promedio de cobro = cuentas por cobrar / ventas x 360 = 120,000 / 720,000 x 360 = 60 días. El 6 es la rotación de cuentas por cobrar (veces al año), no los días.",
  },
  {
    id: "tq-contabilidad-18",
    topic: "contabilidad",
    level: 2,
    q: "Una empresa de Chiclayo paga en enero S/ 12,000 por un seguro que cubre los 12 meses del año. Según el devengado, ¿cuánto gasto por seguro reconoce en enero?",
    options: [
      "S/ 12,000",
      "S/ 0",
      "S/ 6,000",
      "S/ 1,000",
    ],
    answer: 3,
    explain: "El seguro cubre 12 meses, así que el gasto mensual es 12,000 / 12 = S/ 1,000. Los S/ 11,000 restantes quedan como activo (gasto pagado por adelantado) y se consumen mes a mes.",
  },
  {
    id: "tq-contabilidad-19",
    topic: "contabilidad",
    level: 2,
    q: "Una tienda de Cusco vende mercadería con un valor de venta de S/ 1,000 más IGV y cobra S/ 1,180. ¿Cuánto registra como ingreso por ventas?",
    options: [
      "S/ 1,000",
      "S/ 1,180",
      "S/ 820",
      "S/ 180",
    ],
    answer: 0,
    explain: "El ingreso es el valor de venta, S/ 1,000. Los S/ 180 de IGV no son ingreso de la empresa: se registran como un pasivo porque se deben entregar a SUNAT.",
  },
  {
    id: "tq-contabilidad-20",
    topic: "contabilidad",
    level: 2,
    q: "Una distribuidora de Piura tiene una camioneta que costó S/ 80,000 y acumula una depreciación de S/ 32,000. ¿Cuál es su valor en libros?",
    options: [
      "S/ 112,000",
      "S/ 80,000",
      "S/ 48,000",
      "S/ 32,000",
    ],
    answer: 2,
    explain: "Valor en libros = costo menos depreciación acumulada = 80,000 menos 32,000 = S/ 48,000. No es necesariamente el precio al que se podría vender en el mercado.",
  },
  {
    id: "tq-contabilidad-21",
    topic: "contabilidad",
    level: 2,
    q: "Una empresa de Chiclayo obtuvo una utilidad neta de S/ 30,000, con ventas de S/ 300,000 y un patrimonio de S/ 150,000. ¿Cuál es su rentabilidad sobre el patrimonio (ROE)?",
    options: [
      "10 %",
      "20 %",
      "50 %",
      "5 %",
    ],
    answer: 1,
    explain: "ROE = utilidad neta / patrimonio = 30,000 / 150,000 = 20 %. El 10 % es el margen neto (utilidad entre ventas), que es otro indicador.",
  },
  {
    id: "tq-contabilidad-22",
    topic: "contabilidad",
    level: 2,
    q: "Una ferretería de Ayacucho compra 10 bolsas de cemento a S/ 20 y luego otras 10 a S/ 30. Después vende 10 bolsas. Con el método PEPS (primeras entradas, primeras salidas), ¿cuál es el costo de ventas?",
    options: [
      "S/ 300",
      "S/ 250",
      "S/ 500",
      "S/ 200",
    ],
    answer: 3,
    explain: "Con PEPS salen primero las unidades más antiguas: 10 bolsas x S/ 20 = S/ 200. Las bolsas de S/ 30 quedan en el inventario final. Los S/ 250 corresponden al método del promedio.",
  },
  {
    id: "tq-contabilidad-23",
    topic: "contabilidad",
    level: 3,
    q: "Una empresa de Lima reporta una utilidad neta de S/ 40,000, pero su caja disminuyó durante el año. En ese periodo vendió más al crédito y aumentó su inventario. ¿Cómo se explica?",
    options: [
      "La utilidad se mide por devengado y el efectivo quedó en cuentas por cobrar e inventarios",
      "El estado de resultados tiene un error, porque utilidad y caja siempre coinciden",
      "La depreciación del año redujo el efectivo disponible",
      "El patrimonio disminuye cada vez que la empresa tiene utilidad",
    ],
    answer: 0,
    explain: "La utilidad registra ventas aunque no se hayan cobrado. Si crecen las cuentas por cobrar y los inventarios, el efectivo queda invertido en ellos. Por eso se analiza también el flujo de efectivo.",
  },
  {
    id: "tq-contabilidad-24",
    topic: "contabilidad",
    level: 3,
    q: "Una imprenta de Arequipa tiene una utilidad neta de S/ 20,000, después de restar S/ 8,000 de depreciación. No hubo cambios en capital de trabajo, inversiones ni deudas. ¿Cuánto efectivo generó la operación?",
    options: [
      "S/ 12,000",
      "S/ 20,000",
      "S/ 28,000",
      "S/ 8,000",
    ],
    answer: 2,
    explain: "La depreciación redujo la utilidad, pero no fue una salida de efectivo, así que se suma de vuelta: 20,000 + 8,000 = S/ 28,000. Es la lógica del método indirecto del flujo de efectivo.",
  },
  {
    id: "tq-contabilidad-25",
    topic: "contabilidad",
    level: 3,
    q: "Al cierre del año, el almacenero de una distribuidora de Trujillo contó de más el inventario final por S/ 5,000. ¿Qué efecto tiene ese error en los resultados del año?",
    options: [
      "El costo de ventas queda sobrevaluado y la utilidad bruta subvaluada en S/ 5,000",
      "El costo de ventas queda subvaluado y la utilidad bruta sobrevaluada en S/ 5,000",
      "No afecta los resultados, solo el estado de situación financiera",
      "Las ventas quedan sobrevaluadas en S/ 5,000",
    ],
    answer: 1,
    explain: "Costo de ventas = inventario inicial + compras menos inventario final. Si el inventario final está inflado, el costo de ventas sale menor y la utilidad aparece más alta de lo real.",
  },
  {
    id: "tq-contabilidad-26",
    topic: "contabilidad",
    level: 3,
    q: "Una clínica dental de Cusco compra un equipo de rayos X por S/ 60,000, con vida útil de 5 años, y el asistente lo registra completo como gasto del mes. ¿Qué consecuencia tiene ese registro?",
    options: [
      "Ninguna, porque el efectivo salió ese mes",
      "La utilidad del mes queda sobrevaluada",
      "El pasivo queda sobrevaluado en S/ 60,000",
      "La utilidad del mes y el activo quedan subvaluados: debió activarse y depreciarse",
    ],
    answer: 3,
    explain: "Un bien que se usará cinco años es un activo y su costo se reparte con la depreciación (S/ 12,000 por año). Cargarlo todo a un mes hunde la utilidad de ese mes e infla la de los siguientes.",
  },
  {
    id: "tq-contabilidad-27",
    topic: "contabilidad",
    level: 3,
    q: "Una pastelería de Lima mantiene sus ventas en S/ 200,000, pero su margen bruto bajó de 45 % a 35 % en un año. Sus gastos operativos no cambiaron. ¿Dónde debes buscar la causa?",
    options: [
      "En los gastos de publicidad",
      "En el costo de ventas: insumos más caros o mayores mermas",
      "En los intereses de los préstamos",
      "En el impuesto a la renta",
    ],
    answer: 1,
    explain: "El margen bruto solo depende de las ventas y del costo de ventas. Si las ventas no cambiaron, el costo de ventas subió de S/ 110,000 a S/ 130,000, por precios de insumos, mermas o desperdicios.",
  },
  {
    id: "tq-contabilidad-28",
    topic: "contabilidad",
    level: 3,
    q: "Un gimnasio de Lima cobra en diciembre S/ 1,200 por una membresía anual que empieza en enero. ¿Cómo debe registrar ese cobro en diciembre?",
    options: [
      "Como ingreso de diciembre, porque ya cobró",
      "Como cuenta por cobrar al cliente",
      "Como pasivo (ingreso diferido), porque todavía debe prestar el servicio",
      "Como capital aportado por el cliente",
    ],
    answer: 2,
    explain: "El gimnasio recibió el dinero, pero aún no presta el servicio, así que tiene una obligación con el cliente. Desde enero reconocerá S/ 100 de ingreso cada mes conforme brinde el servicio.",
  },
  {
    id: "tq-contabilidad-29",
    topic: "contabilidad",
    level: 3,
    q: "Dos bodegas de Piura ganan lo mismo: S/ 20,000 de utilidad neta al año. La bodega A tiene un patrimonio de S/ 100,000 y la bodega B de S/ 200,000. ¿Cuál aprovecha mejor el dinero de sus dueños?",
    options: [
      "La B, porque tiene más patrimonio",
      "Las dos por igual, porque ganan lo mismo",
      "La B, con un ROE de 20 % frente a 10 % de la A",
      "La A, con un ROE de 20 % frente a 10 % de la B",
    ],
    answer: 3,
    explain: "ROE de A = 20,000 / 100,000 = 20 %. ROE de B = 20,000 / 200,000 = 10 %. Con la mitad del dinero de los dueños, la bodega A genera la misma utilidad.",
  },
  {
    id: "tq-contabilidad-30",
    topic: "contabilidad",
    level: 3,
    q: "Una empresa de Huancayo paga la cuota mensual de un préstamo por S/ 10,000: S/ 8,000 son amortización del capital y S/ 2,000 son intereses. ¿Qué parte afecta al estado de resultados?",
    options: [
      "Solo los S/ 2,000 de intereses, como gasto financiero",
      "Los S/ 10,000 completos, como gasto del mes",
      "Solo los S/ 8,000 de capital, como gasto del mes",
      "Ninguna, porque toda la cuota es una operación de financiamiento",
    ],
    answer: 0,
    explain: "Los intereses son el costo de usar el dinero y van al estado de resultados. La amortización del capital solo reduce el pasivo y la caja: devolver lo prestado no es un gasto.",
  },
  // ==================== TRIBUTOS ====================
  {
    id: "tq-tributos-01",
    topic: "tributos",
    level: 1,
    q: "Una tienda de electrodomésticos de Piura vende una licuadora con un valor de venta de S/ 100. ¿Qué tasa de IGV debe aplicar?",
    options: [
      "19 %",
      "18 %",
      "9 %",
      "29.5 %",
    ],
    answer: 1,
    explain: "La tasa general del IGV en el Perú es 18 %. El precio final de la licuadora será S/ 118. El 29.5 % corresponde al impuesto a la renta del régimen general y el 9 % al aporte a EsSalud.",
  },
  {
    id: "tq-tributos-02",
    topic: "tributos",
    level: 1,
    q: "El dueño de una ferretería de Huancayo compra mercadería para su negocio y quiere usar el IGV de esa compra como crédito fiscal. ¿Qué comprobante debe pedir?",
    options: [
      "Factura",
      "Boleta de venta",
      "Guía de remisión",
      "Proforma",
    ],
    answer: 0,
    explain: "La factura, emitida con el RUC del comprador, permite sustentar el crédito fiscal y el gasto. La boleta de venta está pensada para consumidores finales y no da derecho a crédito fiscal.",
  },
  {
    id: "tq-tributos-03",
    topic: "tributos",
    level: 1,
    q: "Una emprendedora de Tarapoto decide formalizar su juguería. ¿Ante qué entidad debe inscribirse en el RUC y declarar sus impuestos?",
    options: [
      "Indecopi",
      "SUNAFIL",
      "SBS",
      "SUNAT",
    ],
    answer: 3,
    explain: "SUNAT administra el RUC y recauda tributos como el IGV y el impuesto a la renta. Indecopi protege al consumidor y la competencia, SUNAFIL fiscaliza lo laboral y la SBS supervisa bancos, seguros y AFP.",
  },
  {
    id: "tq-tributos-04",
    topic: "tributos",
    level: 1,
    q: "Una distribuidora de Lima está en el régimen general y obtiene renta neta en el año. ¿Qué tasa de impuesto a la renta le corresponde?",
    options: [
      "18 %",
      "10 %",
      "29.5 %",
      "9 %",
    ],
    answer: 2,
    explain: "En el régimen general, el impuesto a la renta empresarial es 29.5 % de la renta neta. El 18 % es la tasa del IGV y el 10 % aplica al primer tramo del Régimen MYPE Tributario.",
  },
  {
    id: "tq-tributos-05",
    topic: "tributos",
    level: 1,
    q: "Una empresa de limpieza de Lima tiene 20 operarios en planilla del régimen laboral general. ¿En qué meses debe pagarles las gratificaciones?",
    options: [
      "Julio y diciembre",
      "Mayo y noviembre",
      "Enero y julio",
      "Marzo y diciembre",
    ],
    answer: 0,
    explain: "Las gratificaciones legales se pagan en julio (Fiestas Patrias) y en diciembre (Navidad). Mayo y noviembre son los meses del depósito de la CTS.",
  },
  {
    id: "tq-tributos-06",
    topic: "tributos",
    level: 1,
    q: "Una empresa de Trujillo tiene trabajadores en planilla del régimen laboral general. ¿En qué meses debe depositar la CTS?",
    options: [
      "Julio y diciembre",
      "Enero y junio",
      "Mayo y noviembre",
      "Abril y octubre",
    ],
    answer: 2,
    explain: "La compensación por tiempo de servicios se deposita dos veces al año, en mayo y en noviembre, en la entidad financiera que elige el trabajador. Julio y diciembre son los meses de las gratificaciones.",
  },
  {
    id: "tq-tributos-07",
    topic: "tributos",
    level: 1,
    q: "Una cafetería de Arequipa contrata a un barista en planilla. ¿Quién asume el aporte a EsSalud y de cuánto es?",
    options: [
      "El trabajador, con 9 % que se le descuenta del sueldo",
      "El empleador, con 9 % de la remuneración",
      "El empleador, con 18 % de la remuneración",
      "El empleador y el trabajador, por mitades",
    ],
    answer: 1,
    explain: "El aporte a EsSalud es de 9 % de la remuneración y lo paga el empleador, sin descontarlo al trabajador. Lo que sí se descuenta al trabajador es su aporte al sistema de pensiones.",
  },
  {
    id: "tq-tributos-08",
    topic: "tributos",
    level: 1,
    q: "Una juguería de un mercado de Iquitos está en el Nuevo RUS. Un cliente que tiene empresa le pide factura. ¿Qué debe saber la dueña?",
    options: [
      "Que puede emitir facturas si el monto de la venta es alto",
      "Que puede emitir facturas, pero sin IGV",
      "Que debe emitir un recibo por honorarios",
      "Que en el Nuevo RUS no puede emitir facturas, solo boletas de venta o tickets",
    ],
    answer: 3,
    explain: "El Nuevo RUS está pensado para pequeños negocios que venden a consumidores finales y solo permite emitir boletas de venta o tickets. Si necesita emitir facturas, debe pasar a otro régimen.",
  },
  {
    id: "tq-tributos-09",
    topic: "tributos",
    level: 1,
    q: "Compras una gaseosa en un minimarket de Chiclayo y pagas el precio con IGV. ¿Quién soporta económicamente ese impuesto?",
    options: [
      "El minimarket, que lo paga de su utilidad",
      "El fabricante de la gaseosa",
      "El consumidor final",
      "La municipalidad del distrito",
    ],
    answer: 2,
    explain: "El IGV es un impuesto al consumo: lo paga el consumidor final dentro del precio. Las empresas lo cobran en sus ventas, descuentan el IGV de sus compras y entregan la diferencia a SUNAT.",
  },
  {
    id: "tq-tributos-10",
    topic: "tributos",
    level: 1,
    q: "Un diseñador gráfico de Cusco trabaja de forma independiente, como persona natural, y cobra a una empresa por un logotipo. ¿Qué comprobante emite por su servicio?",
    options: [
      "Recibo por honorarios",
      "Boleta de pago",
      "Guía de remisión",
      "Nota de crédito",
    ],
    answer: 0,
    explain: "Los profesionales independientes emiten recibos por honorarios por sus servicios (rentas de cuarta categoría). La boleta de pago es el documento que el empleador entrega a sus trabajadores en planilla.",
  },
  {
    id: "tq-tributos-11",
    topic: "tributos",
    level: 2,
    q: "Una tienda de Trujillo vende un televisor con un valor de venta de S/ 2,000. ¿Cuál es el precio de venta con IGV?",
    options: [
      "S/ 2,180",
      "S/ 2,018",
      "S/ 2,360",
      "S/ 2,590",
    ],
    answer: 2,
    explain: "IGV = 2,000 x 18 % = 360. Precio de venta = 2,000 + 360 = S/ 2,360. También puedes multiplicar el valor de venta por 1.18.",
  },
  {
    id: "tq-tributos-12",
    topic: "tributos",
    level: 2,
    q: "Una zapatería de Lima cobra S/ 236 por un par de zapatos, precio que ya incluye IGV. ¿Cuánto de ese precio corresponde al IGV?",
    options: [
      "S/ 36",
      "S/ 42.48",
      "S/ 18",
      "S/ 200",
    ],
    answer: 0,
    explain: "Valor de venta = 236 / 1.18 = 200. IGV = 236 menos 200 = S/ 36. El error típico es sacar 18 % del precio final (S/ 42.48), pero el IGV se calcula sobre el valor sin impuesto.",
  },
  {
    id: "tq-tributos-13",
    topic: "tributos",
    level: 2,
    q: "En el mes, una distribuidora de Chiclayo tuvo ventas gravadas por S/ 50,000 y compras con factura por S/ 30,000, ambos valores sin IGV. ¿Cuánto IGV debe pagar a SUNAT?",
    options: [
      "S/ 9,000",
      "S/ 3,600",
      "S/ 5,400",
      "S/ 20,000",
    ],
    answer: 1,
    explain: "IGV de ventas = 50,000 x 18 % = 9,000. Crédito fiscal = 30,000 x 18 % = 5,400. IGV por pagar = 9,000 menos 5,400 = S/ 3,600.",
  },
  {
    id: "tq-tributos-14",
    topic: "tributos",
    level: 2,
    q: "Una tienda de Tacna se abastece para la campaña navideña. En noviembre, el IGV de sus ventas es S/ 4,000 y el IGV de sus compras con factura es S/ 7,000. ¿Qué ocurre ese mes?",
    options: [
      "Paga S/ 3,000 de IGV a SUNAT",
      "Paga S/ 4,000 de IGV y pierde el crédito fiscal",
      "Paga S/ 11,000, la suma de ambos montos",
      "No paga IGV y arrastra S/ 3,000 de saldo a favor para los meses siguientes",
    ],
    answer: 3,
    explain: "Cuando el crédito fiscal (7,000) supera al IGV de las ventas (4,000), no hay pago y la diferencia de S/ 3,000 queda como saldo a favor que se aplica contra el IGV de los meses siguientes.",
  },
  {
    id: "tq-tributos-15",
    topic: "tributos",
    level: 2,
    q: "Una empresa del régimen general tiene una renta neta imponible de S/ 200,000 en el año. ¿Cuánto es su impuesto a la renta anual?",
    options: [
      "S/ 59,000",
      "S/ 36,000",
      "S/ 20,000",
      "S/ 60,000",
    ],
    answer: 0,
    explain: "Impuesto a la renta = 200,000 x 29.5 % = S/ 59,000. Los S/ 36,000 resultan de aplicar por error la tasa del IGV (18 %), que es un impuesto distinto.",
  },
  {
    id: "tq-tributos-16",
    topic: "tributos",
    level: 2,
    q: "Una empresa del Régimen MYPE Tributario obtiene una renta neta anual de S/ 40,000, monto que está por debajo de 15 UIT. ¿Cuánto paga de impuesto a la renta?",
    options: [
      "S/ 11,800",
      "S/ 4,000",
      "S/ 7,200",
      "S/ 400",
    ],
    answer: 1,
    explain: "En el Régimen MYPE Tributario, la renta neta hasta 15 UIT paga 10 %: 40,000 x 10 % = S/ 4,000. Con la tasa de 29.5 % del régimen general habría pagado S/ 11,800.",
  },
  {
    id: "tq-tributos-17",
    topic: "tributos",
    level: 2,
    q: "Una empresa de Arequipa paga a una asistente una remuneración mensual de S/ 2,000. ¿Cuánto aporta la empresa a EsSalud por ella cada mes?",
    options: [
      "S/ 360",
      "S/ 90",
      "S/ 590",
      "S/ 180",
    ],
    answer: 3,
    explain: "Aporte a EsSalud = 2,000 x 9 % = S/ 180. Lo paga la empresa además de la remuneración, no se descuenta del sueldo de la trabajadora.",
  },
  {
    id: "tq-tributos-18",
    topic: "tributos",
    level: 2,
    q: "Un vendedor del régimen laboral general gana S/ 3,000 al mes y trabajó completo el semestre de enero a junio. Sin contar la bonificación extraordinaria, ¿cuánto recibe de gratificación en julio?",
    options: [
      "S/ 1,500",
      "S/ 6,000",
      "S/ 3,000",
      "S/ 500",
    ],
    answer: 2,
    explain: "Por cada semestre completo trabajado, la gratificación equivale a una remuneración mensual: S/ 3,000. Si hubiera trabajado menos meses, recibiría la parte proporcional.",
  },
  {
    id: "tq-tributos-19",
    topic: "tributos",
    level: 2,
    q: "Un trabajador del régimen laboral general gana S/ 2,000 al mes. Contando solo sus 12 remuneraciones y sus 2 gratificaciones completas, ¿cuánto recibe en el año?",
    options: [
      "S/ 24,000",
      "S/ 26,000",
      "S/ 28,000",
      "S/ 30,000",
    ],
    answer: 2,
    explain: "Son 14 pagos de S/ 2,000: 12 remuneraciones más las gratificaciones de julio y diciembre. 14 x 2,000 = S/ 28,000. A eso se suman otros beneficios, como la CTS.",
  },
  {
    id: "tq-tributos-20",
    topic: "tributos",
    level: 2,
    q: "Una pastelería de Lima compró insumos por S/ 1,180, incluido IGV, y recibió una boleta de venta en lugar de una factura. ¿Cuánto crédito fiscal puede usar por esa compra?",
    options: [
      "S/ 180",
      "S/ 0",
      "S/ 212.40",
      "S/ 1,180",
    ],
    answer: 1,
    explain: "La boleta de venta no da derecho a crédito fiscal, así que los S/ 180 de IGV se pierden como crédito. Por eso las compras del negocio deben pedirse con factura a nombre de la empresa.",
  },
  {
    id: "tq-tributos-21",
    topic: "tributos",
    level: 2,
    q: "Una empresa del Régimen MYPE Tributario tuvo un buen año y su renta neta superó las 15 UIT. ¿Qué tasa de impuesto a la renta se aplica al tramo que excede las 15 UIT?",
    options: [
      "10 %",
      "18 %",
      "9 %",
      "29.5 %",
    ],
    answer: 3,
    explain: "El Régimen MYPE Tributario tiene una escala: 10 % por la renta neta hasta 15 UIT y 29.5 % por el exceso. La tasa mayor solo se aplica al tramo que supera las 15 UIT, no a toda la renta.",
  },
  {
    id: "tq-tributos-22",
    topic: "tributos",
    level: 2,
    q: "Una empresa del régimen general tiene una utilidad antes de impuestos de S/ 100,000, igual a su renta neta imponible, y no reparte participación de utilidades. ¿Cuánto le queda de utilidad neta?",
    options: [
      "S/ 70,500",
      "S/ 82,000",
      "S/ 29,500",
      "S/ 90,000",
    ],
    answer: 0,
    explain: "Impuesto a la renta = 100,000 x 29.5 % = 29,500. Utilidad neta = 100,000 menos 29,500 = S/ 70,500. Los S/ 29,500 son el impuesto, no lo que le queda a la empresa.",
  },
  {
    id: "tq-tributos-23",
    topic: "tributos",
    level: 3,
    q: "Una bodega de Lima vende S/ 30,000 al mes, pero solo declara S/ 10,000 para pagar menos impuestos. Sus compras con factura suman S/ 22,000 mensuales. ¿Qué señal puede detectar SUNAT?",
    options: [
      "Ninguna, porque SUNAT solo revisa a las grandes empresas",
      "Que tiene derecho a una devolución por su exceso de crédito fiscal",
      "Que debe pasar de forma automática al Nuevo RUS",
      "Que compra mucho más de lo que declara vender, una inconsistencia típica de ventas omitidas",
    ],
    answer: 3,
    explain: "Las compras con factura quedan registradas por los proveedores. Si un negocio compra más de lo que declara vender mes tras mes, la inconsistencia es visible y puede terminar en fiscalización, multas e intereses.",
  },
  {
    id: "tq-tributos-24",
    topic: "tributos",
    level: 3,
    q: "El dueño de una consultora de Lima carga a la empresa las compras del supermercado de su casa y las vacaciones de su familia, con factura a nombre de la empresa. ¿Qué tratamiento tributario corresponde?",
    options: [
      "Son deducibles, porque tienen factura a nombre de la empresa",
      "No son gasto deducible ni dan crédito fiscal, porque no se vinculan con el negocio",
      "Son deducibles hasta la mitad de su valor",
      "Dan crédito fiscal, aunque no sean gasto deducible",
    ],
    answer: 1,
    explain: "Para deducir un gasto debe cumplirse el principio de causalidad: ser necesario para generar renta o mantener el negocio. Tener factura no basta, y los gastos personales del dueño se reparan en una fiscalización.",
  },
  {
    id: "tq-tributos-25",
    topic: "tributos",
    level: 3,
    q: "Una empresa de transporte de carga de Arequipa factura a una minera un servicio sujeto a detracción. La minera le transfiere menos del total facturado. ¿Qué pasó con la diferencia?",
    options: [
      "La minera la depositó en la cuenta de detracciones del transportista en el Banco de la Nación",
      "La minera se la quedó como descuento por pronto pago",
      "SUNAT la cobró como multa al transportista",
      "Es el impuesto a la renta que paga la minera",
    ],
    answer: 0,
    explain: "En la detracción, el cliente separa un porcentaje del precio y lo deposita en una cuenta del proveedor en el Banco de la Nación. Ese dinero es del proveedor, pero solo sirve para pagar sus tributos.",
  },
  {
    id: "tq-tributos-26",
    topic: "tributos",
    level: 3,
    q: "Dos empresas tienen cada una renta neta anual de S/ 50,000, monto por debajo de 15 UIT. Una está en el régimen general y la otra en el Régimen MYPE Tributario. ¿Cuánto menos paga de impuesto a la renta la segunda?",
    options: [
      "S/ 14,750",
      "S/ 5,000",
      "S/ 9,750",
      "S/ 4,750",
    ],
    answer: 2,
    explain: "Régimen general: 50,000 x 29.5 % = 14,750. Régimen MYPE Tributario: 50,000 x 10 % = 5,000. Diferencia = 14,750 menos 5,000 = S/ 9,750. Elegir bien el régimen es una decisión financiera.",
  },
  {
    id: "tq-tributos-27",
    topic: "tributos",
    level: 3,
    q: "Una tienda en línea de Lima fija su precio final al público en S/ 118, incluido IGV. El producto le cuesta S/ 70 sin IGV. ¿Cuál es su margen bruto real por unidad?",
    options: [
      "S/ 48",
      "S/ 30",
      "S/ 18",
      "S/ 40",
    ],
    answer: 1,
    explain: "Valor de venta = 118 / 1.18 = 100. Margen = 100 menos 70 = S/ 30. Los S/ 18 de IGV no son ingreso de la tienda, por eso calcular 118 menos 70 = 48 infla el margen.",
  },
  {
    id: "tq-tributos-28",
    topic: "tributos",
    level: 3,
    q: "Una empresa de Trujillo paga con recibos por honorarios a 10 personas que cumplen horario, reciben órdenes de un jefe y trabajan solo para ella. ¿Qué riesgo asume?",
    options: [
      "Que SUNAFIL reconozca la relación laboral y exija planilla, beneficios y multas",
      "Ninguno, el recibo por honorarios es válido para cualquier tipo de trabajo",
      "Solo perder el crédito fiscal de esos recibos",
      "Que Indecopi le cierre el local por competencia desleal",
    ],
    answer: 0,
    explain: "Si hay subordinación, horario y remuneración, existe una relación laboral aunque se pague con recibos. La empresa se expone a multas y al pago de gratificaciones, CTS, vacaciones y aportes no realizados.",
  },
  {
    id: "tq-tributos-29",
    topic: "tributos",
    level: 3,
    q: "Una agroexportadora de Piura vende toda su palta al exterior. Compra insumos y servicios locales que sí pagan IGV. ¿Qué ocurre con ese IGV de sus compras?",
    options: [
      "Lo pierde, porque no tiene ventas gravadas dentro del país",
      "Debe cobrarlo a su cliente del exterior con la tasa de 18 %",
      "Puede recuperarlo como saldo a favor del exportador, porque la exportación no paga IGV",
      "Lo paga dos veces, en la compra y en la exportación",
    ],
    answer: 2,
    explain: "La exportación no está gravada con IGV, para no exportar impuestos. El IGV pagado en las compras se convierte en saldo a favor del exportador, que puede compensarse o pedirse en devolución.",
  },
  {
    id: "tq-tributos-30",
    topic: "tributos",
    level: 3,
    q: "Una empresa de Lima contrata a un analista en el régimen laboral general, con una remuneración de S/ 4,000. El gerente presupuesta como costo anual solo 12 sueldos. ¿Qué está omitiendo?",
    options: [
      "Nada, el costo anual es exactamente 12 sueldos",
      "Solo el IGV que grava la remuneración",
      "Solo el impuesto a la renta de 29.5 % sobre el sueldo",
      "Las gratificaciones de julio y diciembre, la CTS y el aporte de 9 % a EsSalud",
    ],
    answer: 3,
    explain: "El costo laboral es mayor que el sueldo: incluye dos gratificaciones, la CTS y el aporte a EsSalud a cargo del empleador. Las remuneraciones no pagan IGV, y el 29.5 % grava la renta de la empresa.",
  },
  // ==================== OPERACIONES ====================
  {
    id: "tq-operaciones-01",
    topic: "operaciones",
    level: 1,
    q: "En una pollería de Huancayo, ¿cuál de estos conceptos es un costo fijo?",
    options: [
      "El pollo que se compra cada día",
      "Las papas para freír",
      "Los envases para delivery",
      "El alquiler del local",
    ],
    answer: 3,
    explain: "El alquiler se paga igual se vendan 100 o 1,000 pollos, por eso es fijo. El pollo, las papas y los envases aumentan con cada venta, así que son costos variables.",
  },
  {
    id: "tq-operaciones-02",
    topic: "operaciones",
    level: 1,
    q: "En un taller de confecciones de Gamarra, ¿cuál de estos conceptos es un costo variable?",
    options: [
      "El alquiler mensual del taller",
      "La tela usada en cada prenda",
      "El sueldo fijo del administrador",
      "La licencia de funcionamiento",
    ],
    answer: 1,
    explain: "La tela se consume en proporción a las prendas producidas: a más prendas, más tela. El alquiler, el sueldo fijo y la licencia no cambian con el volumen de producción.",
  },
  {
    id: "tq-operaciones-03",
    topic: "operaciones",
    level: 1,
    q: "En una panadería de Cusco, amasar toma poco tiempo, pero el único horno no se da abasto y las bandejas hacen cola para entrar. ¿Cómo se llama la etapa que limita toda la producción?",
    options: [
      "Cuello de botella",
      "Punto de equilibrio",
      "Lote económico",
      "Inventario de seguridad",
    ],
    answer: 0,
    explain: "El cuello de botella es la etapa con menor capacidad de un proceso y define cuánto puede producir todo el sistema. Aquí, por más rápido que se amase, la producción depende del horno.",
  },
  {
    id: "tq-operaciones-04",
    topic: "operaciones",
    level: 1,
    q: "Un gimnasio de Lima puede atender como máximo a 80 personas por hora con sus máquinas y su espacio. ¿Qué concepto describe ese límite?",
    options: [
      "Productividad",
      "Demanda",
      "Capacidad instalada",
      "Rotación de inventarios",
    ],
    answer: 2,
    explain: "La capacidad instalada es el máximo que una operación puede producir o atender en un periodo con sus recursos actuales. La demanda es lo que los clientes piden, que puede ser mayor o menor.",
  },
  {
    id: "tq-operaciones-05",
    topic: "operaciones",
    level: 1,
    q: "Una botica de Pucallpa guarda unidades extra de un medicamento por si la demanda sube o el proveedor se atrasa. ¿Cómo se llama ese inventario?",
    options: [
      "Inventario en tránsito",
      "Inventario de seguridad",
      "Merma",
      "Inventario obsoleto",
    ],
    answer: 1,
    explain: "El inventario de seguridad es un colchón contra la incertidumbre de la demanda y de los tiempos de entrega. Evita quedarse sin stock, aunque mantenerlo tiene un costo.",
  },
  {
    id: "tq-operaciones-06",
    topic: "operaciones",
    level: 1,
    q: "El dueño de un taller de calzado de Trujillo quiere medir la productividad de su equipo. ¿Cómo se calcula?",
    options: [
      "Sumando todos los pares producidos en el año",
      "Restando los costos de las ventas",
      "Contando el número de trabajadores contratados",
      "Dividiendo lo producido entre los recursos usados, por ejemplo pares por hora trabajada",
    ],
    answer: 3,
    explain: "La productividad relaciona el resultado con los recursos empleados para lograrlo. Producir más no siempre es ser más productivo: importa cuánto se obtiene por cada hora, sol o insumo usado.",
  },
  {
    id: "tq-operaciones-07",
    topic: "operaciones",
    level: 1,
    q: "Una planta de bebidas de Arequipa revisa muestras de botellas durante el proceso para detectar fallas antes de que lleguen al cliente. ¿Qué actividad realiza?",
    options: [
      "Control de calidad",
      "Benchmarking",
      "Tercerización",
      "Pronóstico de demanda",
    ],
    answer: 0,
    explain: "El control de calidad verifica que el producto cumpla las especificaciones y detecta fallas a tiempo. Encontrar un defecto en planta cuesta mucho menos que atender un reclamo o un retiro del mercado.",
  },
  {
    id: "tq-operaciones-08",
    topic: "operaciones",
    level: 1,
    q: "Una exportadora de café de Jaén coordina a caficultores, acopiadores, transportistas, el puerto y el comprador del exterior. ¿Qué está gestionando?",
    options: [
      "Su organigrama",
      "Su estructura de capital",
      "Su cadena de suministro",
      "Su mezcla de marketing",
    ],
    answer: 2,
    explain: "La cadena de suministro abarca todos los actores y flujos (producto, información y dinero) desde el origen de los insumos hasta el cliente final. Coordinarla bien reduce costos y tiempos.",
  },
  {
    id: "tq-operaciones-09",
    topic: "operaciones",
    level: 1,
    q: "En una juguería de Piura, parte de la fruta se malogra antes de usarse y debe botarse. ¿Cómo se llama esa pérdida?",
    options: [
      "Depreciación",
      "Margen de contribución",
      "Detracción",
      "Merma",
    ],
    answer: 3,
    explain: "La merma es la pérdida física de insumos o productos por deterioro, vencimiento o manipulación. Controlarla con compras más frecuentes y buena conservación mejora directamente el margen.",
  },
  {
    id: "tq-operaciones-10",
    topic: "operaciones",
    level: 1,
    q: "Un minimarket de Chiclayo coloca adelante en la góndola los yogures que vencen antes, para que se vendan primero. ¿Qué criterio de rotación aplica?",
    options: [
      "Último en entrar, primero en salir",
      "Primero en vencer, primero en salir",
      "Lote económico de compra",
      "Justo a tiempo",
    ],
    answer: 1,
    explain: "En productos perecibles se despacha primero lo que vence antes, para reducir mermas por vencimiento. Es un criterio básico de almacén en alimentos y medicamentos.",
  },
  {
    id: "tq-operaciones-11",
    topic: "operaciones",
    level: 2,
    q: "Una fábrica de helados de Lima tiene costos fijos de S/ 20,000 al mes y un costo variable de S/ 3 por litro. Si produce 10,000 litros en el mes, ¿cuál es el costo total por litro?",
    options: [
      "S/ 3",
      "S/ 5",
      "S/ 2",
      "S/ 23",
    ],
    answer: 1,
    explain: "Costo fijo por litro = 20,000 / 10,000 = S/ 2. Costo total por litro = 2 + 3 = S/ 5. Si produjera más litros, el costo fijo por litro bajaría.",
  },
  {
    id: "tq-operaciones-12",
    topic: "operaciones",
    level: 2,
    q: "Una planta de Arequipa puede producir 1,000 cajas al día y actualmente produce 750. ¿Cuál es su utilización de capacidad?",
    options: [
      "75 %",
      "25 %",
      "133 %",
      "7.5 %",
    ],
    answer: 0,
    explain: "Utilización = producción real / capacidad = 750 / 1,000 = 75 %. El 25 % restante es capacidad ociosa, que igual genera costos fijos.",
  },
  {
    id: "tq-operaciones-13",
    topic: "operaciones",
    level: 2,
    q: "Una lavandería de Lima tiene tres etapas en serie: lavado (40 kg por hora), secado (20 kg por hora) y planchado (36 kg por hora). ¿Cuánto puede procesar como máximo todo el sistema por hora?",
    options: [
      "96 kg",
      "40 kg",
      "20 kg",
      "32 kg",
    ],
    answer: 2,
    explain: "En un proceso en serie, la capacidad del sistema es la de su etapa más lenta: el secado, con 20 kg por hora. No se suman las capacidades ni se promedian.",
  },
  {
    id: "tq-operaciones-14",
    topic: "operaciones",
    level: 2,
    q: "Un taller de Gamarra produce 480 polos en una jornada de 8 horas con 6 operarios. ¿Cuál es su productividad por hora hombre?",
    options: [
      "60 polos",
      "80 polos",
      "48 polos",
      "10 polos",
    ],
    answer: 3,
    explain: "Horas hombre = 6 operarios x 8 horas = 48. Productividad = 480 / 48 = 10 polos por hora hombre. Dividir solo entre las horas (60) o solo entre los operarios (80) mide otra cosa.",
  },
  {
    id: "tq-operaciones-15",
    topic: "operaciones",
    level: 2,
    q: "Una bodega mayorista de Tacna vende 20 sacos de arroz por día y su proveedor demora 5 días en entregar. Sin inventario de seguridad, ¿con cuántos sacos en stock debe hacer el pedido?",
    options: [
      "100 sacos",
      "25 sacos",
      "4 sacos",
      "20 sacos",
    ],
    answer: 0,
    explain: "Punto de reorden = demanda diaria x días de entrega = 20 x 5 = 100 sacos. Si pide cuando le quedan 100, el nuevo lote llega justo cuando el stock se termina.",
  },
  {
    id: "tq-operaciones-16",
    topic: "operaciones",
    level: 2,
    q: "Una ferretería de Ayacucho tiene 600 bolsas de cemento en almacén y vende 40 bolsas por día. ¿Para cuántos días le alcanza el inventario?",
    options: [
      "12 días",
      "20 días",
      "15 días",
      "24 días",
    ],
    answer: 2,
    explain: "Días de cobertura = inventario / venta diaria = 600 / 40 = 15 días. Este dato se compara con el tiempo de entrega del proveedor para decidir cuándo reponer.",
  },
  {
    id: "tq-operaciones-17",
    topic: "operaciones",
    level: 2,
    q: "Una fábrica de Trujillo produce 2,000 pares de zapatos en el mes y 60 salen defectuosos. ¿Cuál es su tasa de defectos?",
    options: [
      "0.3 %",
      "3 %",
      "30 %",
      "6 %",
    ],
    answer: 1,
    explain: "Tasa de defectos = defectuosos / producidos = 60 / 2,000 = 0.03, es decir, 3 %. De cada 100 pares, 3 no cumplen el estándar.",
  },
  {
    id: "tq-operaciones-18",
    topic: "operaciones",
    level: 2,
    q: "Una empresa de Chiclayo vende 5,000 unidades al mes a S/ 20 cada una. Su costo variable es S/ 12 por unidad y sus costos fijos son S/ 30,000. ¿Cuál es su utilidad operativa mensual?",
    options: [
      "S/ 40,000",
      "S/ 70,000",
      "S/ 100,000",
      "S/ 10,000",
    ],
    answer: 3,
    explain: "Margen de contribución = 5,000 x (20 menos 12) = 40,000. Utilidad operativa = 40,000 menos 30,000 de costos fijos = S/ 10,000.",
  },
  {
    id: "tq-operaciones-19",
    topic: "operaciones",
    level: 2,
    q: "En la caja de una cafetería de Lima, atender cada pedido toma 3 minutos. ¿Cuántos pedidos puede atender como máximo esa caja en una hora?",
    options: [
      "30 pedidos",
      "180 pedidos",
      "20 pedidos",
      "18 pedidos",
    ],
    answer: 2,
    explain: "Capacidad por hora = 60 minutos / 3 minutos por pedido = 20 pedidos. Si en hora punta llegan más de 20 clientes, se forma cola y hace falta otra caja o un proceso más rápido.",
  },
  {
    id: "tq-operaciones-20",
    topic: "operaciones",
    level: 2,
    q: "Una distribuidora de Lima tiene una demanda anual de 10,000 unidades, un costo de S/ 50 por cada pedido y un costo de mantener inventario de S/ 1 por unidad al año. ¿Cuál es su lote económico de compra?",
    options: [
      "1,000 unidades",
      "500,000 unidades",
      "707 unidades",
      "100 unidades",
    ],
    answer: 0,
    explain: "Lote económico = raíz cuadrada de (2 x demanda x costo de pedir / costo de mantener) = raíz de (2 x 10,000 x 50 / 1) = raíz de 1,000,000 = 1,000 unidades.",
  },
  {
    id: "tq-operaciones-21",
    topic: "operaciones",
    level: 2,
    q: "Una tienda de Huancayo compra lotes de 1,000 unidades, los vende a ritmo constante y repone justo cuando el stock llega a cero. ¿Cuál es su inventario promedio?",
    options: [
      "1,000 unidades",
      "250 unidades",
      "0 unidades",
      "500 unidades",
    ],
    answer: 3,
    explain: "Si el stock baja de forma pareja de 1,000 a 0, el promedio es la mitad del lote: 1,000 / 2 = 500 unidades. Sobre ese promedio se calcula el costo de mantener inventario.",
  },
  {
    id: "tq-operaciones-22",
    topic: "operaciones",
    level: 2,
    q: "Una imprenta de Huancayo tiene costos fijos de S/ 12,000 al mes. Si pasa de producir 4,000 a 6,000 agendas mensuales, ¿qué ocurre con el costo fijo por unidad?",
    options: [
      "No cambia, porque el costo fijo es fijo",
      "Baja S/ 1, de S/ 3 a S/ 2",
      "Sube S/ 1, de S/ 2 a S/ 3",
      "Baja S/ 2, de S/ 3 a S/ 1",
    ],
    answer: 1,
    explain: "Antes: 12,000 / 4,000 = S/ 3 por agenda. Después: 12,000 / 6,000 = S/ 2. El costo fijo total no cambia, pero se reparte entre más unidades. Esa es la base de las economías de escala.",
  },
  {
    id: "tq-operaciones-23",
    topic: "operaciones",
    level: 3,
    q: "Una fábrica de mermeladas de Tarapoto tiene tres etapas en serie: cocción (100 frascos por hora), envasado (60) y etiquetado (90). El gerente quiere comprar otra olla de cocción para producir más. ¿Qué opinas?",
    options: [
      "Es correcto, porque la cocción es la etapa más importante",
      "No sirve: el límite es el envasado, con 60 frascos por hora, y ahí debe invertir",
      "Es correcto, la producción subirá a 200 frascos por hora",
      "Debe invertir en etiquetado, porque es la última etapa",
    ],
    answer: 1,
    explain: "La planta produce 60 frascos por hora porque el envasado es el cuello de botella. Ampliar la cocción solo acumularía producto en espera. Toda mejora debe empezar por la etapa que limita al sistema.",
  },
  {
    id: "tq-operaciones-24",
    topic: "operaciones",
    level: 3,
    q: "Una empresa de Lima puede fabricar una pieza con un costo variable de S/ 8 y un costo fijo adicional de S/ 20,000 al año, o comprarla a un proveedor a S/ 12. Necesita 3,000 piezas al año. ¿Qué le conviene?",
    options: [
      "Fabricarla, porque S/ 8 es menor que S/ 12",
      "Fabricarla: cuesta S/ 24,000 frente a S/ 36,000 de comprarla",
      "Es indiferente, porque ambas opciones cuestan S/ 36,000",
      "Comprarla: cuesta S/ 36,000 frente a S/ 44,000 de fabricarla",
    ],
    answer: 3,
    explain: "Fabricar: 3,000 x 8 + 20,000 = S/ 44,000. Comprar: 3,000 x 12 = S/ 36,000. Con ese volumen conviene comprar. Recién a partir de 5,000 piezas al año fabricar resulta más barato.",
  },
  {
    id: "tq-operaciones-25",
    topic: "operaciones",
    level: 3,
    q: "Una tienda de ropa de Gamarra compra el doble de su stock habitual para obtener 5 % de descuento del proveedor. La mitad no se vende y pasa de moda. ¿Qué lección deja el caso?",
    options: [
      "El descuento por volumen no compensa si el costo de mantener y la obsolescencia son mayores",
      "Siempre conviene comprar más para bajar el costo unitario",
      "El inventario no tiene costo mientras esté en el almacén",
      "El error estuvo en el precio de venta, no en la compra",
    ],
    answer: 0,
    explain: "El inventario inmoviliza dinero, ocupa espacio y puede volverse obsoleto. Un descuento de 5 % se pierde si la mitad de la compra debe rematarse. La decisión de compra debe mirar el costo total, no solo el precio.",
  },
  {
    id: "tq-operaciones-26",
    topic: "operaciones",
    level: 3,
    q: "Una fábrica de Arequipa tiene capacidad ociosa. Su costo variable unitario es S/ 10 y su costo fijo unitario es S/ 6. Un cliente nuevo ofrece comprar 1,000 unidades a S/ 13, sin afectar las ventas normales. ¿Conviene aceptar?",
    options: [
      "No, porque S/ 13 es menor que el costo total unitario de S/ 16",
      "Solo si el cliente acepta pagar S/ 16 o más por unidad",
      "Sí: cada unidad aporta S/ 3 sobre el costo variable y los costos fijos no cambian",
      "No, porque el pedido aumenta los costos fijos en S/ 6,000",
    ],
    answer: 2,
    explain: "Con capacidad ociosa, los costos fijos ya están comprometidos y no cambian. El pedido aporta 1,000 x (13 menos 10) = S/ 3,000 de utilidad adicional. La comparación correcta es contra el costo variable.",
  },
  {
    id: "tq-operaciones-27",
    topic: "operaciones",
    level: 3,
    q: "Una planta de conservas de Chimbote gasta poco en prevención y mucho en reprocesos, devoluciones y reclamos de clientes. ¿Qué enfoque reduce más su costo total de calidad?",
    options: [
      "Inspeccionar solo al final y descartar lo defectuoso",
      "Bajar el precio para compensar los reclamos",
      "Eliminar el control de calidad para ahorrar costos",
      "Invertir en prevención: capacitación, mantenimiento y control durante el proceso",
    ],
    answer: 3,
    explain: "Prevenir una falla cuesta menos que corregirla, y corregirla en planta cuesta menos que atenderla cuando ya llegó al cliente. Invertir en prevención reduce reprocesos, devoluciones y daño a la marca.",
  },
  {
    id: "tq-operaciones-28",
    topic: "operaciones",
    level: 3,
    q: "El taller A produce 600 prendas con 10 operarios en 8 horas. El taller B produce 576 prendas con 8 operarios en 8 horas. ¿Cuál es más productivo por hora hombre?",
    options: [
      "El A, porque produce más prendas en total",
      "El B, con 9 prendas por hora hombre frente a 7.5 del A",
      "El A, con 9 prendas por hora hombre frente a 7.5 del B",
      "Son iguales, porque trabajan las mismas horas",
    ],
    answer: 1,
    explain: "Taller A: 600 / (10 x 8) = 7.5 prendas por hora hombre. Taller B: 576 / (8 x 8) = 9. El B produce menos en total, pero aprovecha mejor cada hora de trabajo.",
  },
  {
    id: "tq-operaciones-29",
    topic: "operaciones",
    level: 3,
    q: "Una pastelería de Cusco compra toda su harina a un solo proveedor de Lima. Un bloqueo de carreteras detiene los envíos por dos semanas y debe parar la producción. ¿Qué medida reduce mejor este riesgo a futuro?",
    options: [
      "Exigir al mismo proveedor un precio más bajo",
      "Eliminar inventarios para trabajar justo a tiempo",
      "Tener un proveedor alterno en la región y un inventario de seguridad de insumos críticos",
      "Subir los precios al cliente durante todo el año",
    ],
    answer: 2,
    explain: "Depender de un solo proveedor lejano concentra el riesgo. Diversificar proveedores y mantener un colchón de insumos críticos cuesta algo más, pero protege la continuidad de la operación.",
  },
  {
    id: "tq-operaciones-30",
    topic: "operaciones",
    level: 3,
    q: "Una botica de Iquitos vende 30 cajas diarias de un producto. El proveedor demora 6 días en entregar, pero a veces se atrasa 2 días por el transporte fluvial. ¿Qué punto de reorden la protege de ese atraso?",
    options: [
      "240 cajas",
      "180 cajas",
      "60 cajas",
      "30 cajas",
    ],
    answer: 0,
    explain: "Demanda durante la entrega = 30 x 6 = 180 cajas. Inventario de seguridad por 2 días de atraso = 30 x 2 = 60. Punto de reorden = 180 + 60 = 240 cajas.",
  },
  // ==================== PERSONAS ====================
  {
    id: "tq-personas-01",
    topic: "personas",
    level: 1,
    q: "En un call center de Lima, muchos trabajadores renuncian y deben ser reemplazados cada pocos meses. ¿Qué indicador mide este fenómeno?",
    options: [
      "Rotación de personal",
      "Ausentismo",
      "Clima laboral",
      "Productividad",
    ],
    answer: 0,
    explain: "La rotación mide cuántas personas salen de la empresa y deben ser reemplazadas en un periodo. El ausentismo mide las faltas de quienes siguen trabajando, que es un problema distinto.",
  },
  {
    id: "tq-personas-02",
    topic: "personas",
    level: 1,
    q: "Una empresa de Trujillo aplica una encuesta anónima para saber cómo perciben sus trabajadores el ambiente, el trato de los jefes y la comunicación. ¿Qué está midiendo?",
    options: [
      "La rotación de personal",
      "El desempeño individual",
      "El clima laboral",
      "La capacidad instalada",
    ],
    answer: 2,
    explain: "El clima laboral es la percepción que tienen los trabajadores sobre su ambiente de trabajo. Se mide con encuestas anónimas y sirve para anticipar problemas de rotación y productividad.",
  },
  {
    id: "tq-personas-03",
    topic: "personas",
    level: 1,
    q: "Una cadena de boticas de Arequipa publica una vacante en una bolsa de trabajo para atraer candidatos. ¿En qué etapa del proceso está?",
    options: [
      "Inducción",
      "Reclutamiento",
      "Evaluación de desempeño",
      "Desvinculación",
    ],
    answer: 1,
    explain: "El reclutamiento consiste en atraer candidatos para una vacante. Después viene la selección, donde se evalúa y se elige, y luego la inducción del nuevo trabajador.",
  },
  {
    id: "tq-personas-04",
    topic: "personas",
    level: 1,
    q: "Un nuevo cajero ingresa a un minimarket de Piura y en su primera semana le explican las normas, las funciones de su puesto y a quién reporta. ¿Cómo se llama este proceso?",
    options: [
      "Reclutamiento",
      "Selección",
      "Compensación",
      "Inducción",
    ],
    answer: 3,
    explain: "La inducción integra al nuevo trabajador a la empresa y a su puesto. Una buena inducción acorta el tiempo que tarda en rendir y reduce las renuncias de los primeros meses.",
  },
  {
    id: "tq-personas-05",
    topic: "personas",
    level: 1,
    q: "¿Cuál de estos conceptos es un beneficio social que recibe un trabajador en planilla del régimen laboral general en el Perú?",
    options: [
      "El crédito fiscal del IGV",
      "Las gratificaciones de julio y diciembre",
      "El recibo por honorarios",
      "La detracción",
    ],
    answer: 1,
    explain: "Las gratificaciones de Fiestas Patrias y Navidad son un beneficio social del trabajador en planilla. El crédito fiscal y la detracción son conceptos tributarios, y el recibo por honorarios es un comprobante.",
  },
  {
    id: "tq-personas-06",
    topic: "personas",
    level: 1,
    q: "Una trabajadora de una tienda de Chiclayo recibe depósitos de CTS en su cuenta. ¿Para qué sirve principalmente este beneficio?",
    options: [
      "Como protección económica cuando el trabajador se queda sin empleo",
      "Para pagar el impuesto a la renta del trabajador",
      "Para financiar la capacitación que da la empresa",
      "Para cubrir su atención médica en EsSalud",
    ],
    answer: 0,
    explain: "La compensación por tiempo de servicios funciona como un respaldo frente al cese laboral. La empresa la deposita en mayo y noviembre en la cuenta que elige el trabajador.",
  },
  {
    id: "tq-personas-07",
    topic: "personas",
    level: 1,
    q: "Una empresa de software de Lima enseña a su equipo de soporte a usar un nuevo sistema para atender mejor a los clientes. ¿Qué práctica de gestión de personas aplica?",
    options: [
      "Reclutamiento",
      "Tercerización",
      "Desvinculación",
      "Capacitación",
    ],
    answer: 3,
    explain: "La capacitación desarrolla conocimientos y habilidades que el trabajador necesita en su puesto. Es una inversión que mejora la productividad y la calidad del servicio.",
  },
  {
    id: "tq-personas-08",
    topic: "personas",
    level: 1,
    q: "El jefe de un taller de Huancayo decide todo solo, no consulta a su equipo y se limita a dar órdenes. ¿Qué estilo de liderazgo aplica?",
    options: [
      "Democrático o participativo",
      "Dejar hacer (laissez faire)",
      "Autocrático",
      "Transformacional",
    ],
    answer: 2,
    explain: "El líder autocrático concentra las decisiones y espera obediencia. Puede servir en emergencias, pero usado siempre desmotiva al equipo y frena la iniciativa.",
  },
  {
    id: "tq-personas-09",
    topic: "personas",
    level: 1,
    q: "Una financiera de Chiclayo compara cada semestre los resultados de cada asesor con sus metas y le da retroalimentación. ¿Cómo se llama este proceso?",
    options: [
      "Evaluación de desempeño",
      "Análisis de puestos",
      "Reclutamiento interno",
      "Encuesta de clima laboral",
    ],
    answer: 0,
    explain: "La evaluación de desempeño mide el aporte de cada persona frente a sus objetivos y permite dar retroalimentación, reconocer logros y definir necesidades de capacitación.",
  },
  {
    id: "tq-personas-10",
    topic: "personas",
    level: 1,
    q: "Una concesionaria de autos de Lima paga a sus vendedores un sueldo fijo más un monto por cada auto vendido. ¿Cómo se llama esa parte adicional?",
    options: [
      "Gratificación",
      "Comisión (remuneración variable)",
      "CTS",
      "Asignación familiar",
    ],
    answer: 1,
    explain: "La comisión es una remuneración variable ligada a resultados, en este caso a las ventas. Alinea el esfuerzo del vendedor con los objetivos comerciales de la empresa.",
  },
  {
    id: "tq-personas-11",
    topic: "personas",
    level: 2,
    q: "Una empresa de Lima tuvo en promedio 200 trabajadores durante el año y 30 dejaron la empresa en ese periodo. ¿Cuál es su tasa de rotación anual?",
    options: [
      "30 %",
      "6.7 %",
      "1.5 %",
      "15 %",
    ],
    answer: 3,
    explain: "Tasa de rotación = salidas / promedio de trabajadores = 30 / 200 = 15 %. El 6.7 resulta de dividir al revés (200 / 30), un error frecuente.",
  },
  {
    id: "tq-personas-12",
    topic: "personas",
    level: 2,
    q: "En un mes de 20 días laborables, un equipo de 10 personas de una empresa de Arequipa acumuló 10 días de faltas. ¿Cuál fue la tasa de ausentismo?",
    options: [
      "10 %",
      "5 %",
      "50 %",
      "2 %",
    ],
    answer: 1,
    explain: "Días programados = 10 personas x 20 días = 200. Tasa de ausentismo = 10 / 200 = 5 %. El error típico es dividir las faltas solo entre el número de días o de personas.",
  },
  {
    id: "tq-personas-13",
    topic: "personas",
    level: 2,
    q: "Reemplazar a un vendedor le cuesta a una tienda de Trujillo S/ 3,000 entre convocatoria, selección y capacitación. Si en el año renuncian 8 vendedores, ¿cuánto le cuesta la rotación?",
    options: [
      "S/ 24,000",
      "S/ 3,000",
      "S/ 11,000",
      "S/ 2,400",
    ],
    answer: 0,
    explain: "Costo de rotación = 8 renuncias x S/ 3,000 = S/ 24,000. A esto se suman costos menos visibles, como las ventas perdidas mientras el puesto está vacío.",
  },
  {
    id: "tq-personas-14",
    topic: "personas",
    level: 2,
    q: "Una vendedora de Gamarra gana un sueldo fijo de S/ 1,500 más 5 % de comisión sobre sus ventas. Si en el mes vende S/ 20,000, ¿cuánto recibe en total?",
    options: [
      "S/ 1,000",
      "S/ 2,575",
      "S/ 2,500",
      "S/ 11,500",
    ],
    answer: 2,
    explain: "Comisión = 20,000 x 5 % = 1,000. Total = 1,500 + 1,000 = S/ 2,500. La comisión se calcula sobre las ventas, no sobre la suma del sueldo y las ventas.",
  },
  {
    id: "tq-personas-15",
    topic: "personas",
    level: 2,
    q: "Una empresa de Piura tiene una planilla mensual de remuneraciones de S/ 80,000 y otorga un aumento general de 5 %. ¿En cuánto sube la planilla mensual?",
    options: [
      "S/ 400",
      "S/ 4,000",
      "S/ 8,000",
      "S/ 84,000",
    ],
    answer: 1,
    explain: "Aumento = 80,000 x 5 % = S/ 4,000. La nueva planilla será de S/ 84,000, pero la pregunta es por el incremento. Sobre ese aumento también suben los aportes y beneficios.",
  },
  {
    id: "tq-personas-16",
    topic: "personas",
    level: 2,
    q: "Una empresa de Arequipa invierte S/ 10,000 en capacitar a sus vendedores y obtiene beneficios adicionales por S/ 15,000, antes de restar el costo del curso. ¿Cuál es el retorno sobre la inversión (ROI)?",
    options: [
      "150 %",
      "15 %",
      "67 %",
      "50 %",
    ],
    answer: 3,
    explain: "ROI = (beneficio menos costo) / costo = (15,000 menos 10,000) / 10,000 = 50 %. Por cada sol invertido en capacitación se recuperó el sol y se ganaron 50 céntimos más.",
  },
  {
    id: "tq-personas-17",
    topic: "personas",
    level: 2,
    q: "Un trabajador del régimen laboral general gana S/ 1,800 al mes y solo trabajó 3 meses completos del semestre de enero a junio. Sin contar la bonificación extraordinaria, ¿cuánto recibe de gratificación en julio?",
    options: [
      "S/ 1,800",
      "S/ 300",
      "S/ 900",
      "S/ 600",
    ],
    answer: 2,
    explain: "La gratificación es proporcional a los meses completos trabajados en el semestre: 1,800 x 3 / 6 = S/ 900. Solo recibe una remuneración completa quien trabajó los seis meses.",
  },
  {
    id: "tq-personas-18",
    topic: "personas",
    level: 2,
    q: "Una agencia de marketing digital de Lima factura S/ 600,000 al año con 12 colaboradores. ¿Cuál es su venta anual por colaborador?",
    options: [
      "S/ 50,000",
      "S/ 5,000",
      "S/ 72,000",
      "S/ 60,000",
    ],
    answer: 0,
    explain: "Venta por colaborador = 600,000 / 12 = S/ 50,000 al año. Es un indicador simple de productividad que permite compararse con otras agencias del sector.",
  },
  {
    id: "tq-personas-19",
    topic: "personas",
    level: 2,
    q: "Para una vacante en una empresa de Tacna postulan 120 personas, 12 pasan a entrevista y se contrata a 1. ¿Qué porcentaje de los postulantes llegó a la entrevista?",
    options: [
      "10 %",
      "1 %",
      "12 %",
      "8.3 %",
    ],
    answer: 0,
    explain: "Postulantes que llegaron a entrevista = 12 / 120 = 10 %. Este indicador del embudo de selección muestra si la convocatoria atrae a candidatos con el perfil buscado.",
  },
  {
    id: "tq-personas-20",
    topic: "personas",
    level: 2,
    q: "Una empresa de Cusco con 50 trabajadores dictó en total 1,000 horas de capacitación durante el año. ¿Cuántas horas recibió en promedio cada trabajador?",
    options: [
      "50 horas",
      "200 horas",
      "20 horas",
      "2 horas",
    ],
    answer: 2,
    explain: "Horas promedio = 1,000 / 50 = 20 horas por trabajador al año. Conviene revisar también cómo se repartieron, porque un promedio puede ocultar áreas que no recibieron nada.",
  },
  {
    id: "tq-personas-21",
    topic: "personas",
    level: 2,
    q: "El mercado paga S/ 2,500 por el puesto de asistente contable en Trujillo y tu empresa paga S/ 2,000. ¿Qué porcentaje del sueldo de mercado representa la diferencia?",
    options: [
      "25 %",
      "80 %",
      "5 %",
      "20 %",
    ],
    answer: 3,
    explain: "Diferencia = 2,500 menos 2,000 = 500. Sobre el sueldo de mercado: 500 / 2,500 = 20 %. El 25 % resulta de dividir entre el sueldo de tu empresa, que no es la base pedida.",
  },
  {
    id: "tq-personas-22",
    topic: "personas",
    level: 2,
    q: "Un asesor de créditos de una caja municipal de Cusco tenía la meta de colocar S/ 200,000 en el mes y colocó S/ 170,000. ¿Cuál fue su cumplimiento de meta?",
    options: [
      "15 %",
      "85 %",
      "118 %",
      "70 %",
    ],
    answer: 1,
    explain: "Cumplimiento = logrado / meta = 170,000 / 200,000 = 85 %. El 15 % es lo que le faltó para llegar, no lo que cumplió.",
  },
  {
    id: "tq-personas-23",
    topic: "personas",
    level: 3,
    q: "Una cadena de cafeterías de Lima tiene alta rotación de baristas. Las entrevistas de salida muestran que el sueldo está en el promedio del mercado, pero casi todos mencionan maltrato del supervisor. ¿Qué acción ataca la causa?",
    options: [
      "Subir 20 % el sueldo a todos los baristas",
      "Contratar más rápido para cubrir las renuncias",
      "Trabajar el liderazgo del supervisor con retroalimentación y formación, y cambiarlo si no mejora",
      "Eliminar las entrevistas de salida para evitar quejas",
    ],
    answer: 2,
    explain: "Los datos indican que el problema es el trato del jefe directo, no el sueldo. Subir sueldos eleva el costo sin resolver la causa. Muchas personas renuncian a su jefe, no a la empresa.",
  },
  {
    id: "tq-personas-24",
    topic: "personas",
    level: 3,
    q: "Para ahorrar, una empresa de Piura fija sus sueldos de ingreso muy por debajo del mercado. Al cabo de un año, la rotación se duplica y la calidad del servicio cae. ¿Qué error de análisis cometió?",
    options: [
      "Miró solo el costo de planilla y no el costo de rotar, volver a capacitar y perder calidad",
      "Ninguno, el ahorro en planilla siempre mejora la utilidad",
      "Debió bajar también los sueldos del personal antiguo",
      "Debió eliminar la capacitación para ahorrar todavía más",
    ],
    answer: 0,
    explain: "Pagar por debajo del mercado reduce la planilla, pero aumenta los costos ocultos: reclutamiento, capacitación repetida, errores y clientes insatisfechos. La compensación debe evaluarse por su efecto total.",
  },
  {
    id: "tq-personas-25",
    topic: "personas",
    level: 3,
    q: "Una distribuidora de Chiclayo asciende a jefe de ventas a su mejor vendedor. Como jefe no delega, no forma a su equipo y las ventas del área caen. ¿Qué enseña el caso?",
    options: [
      "Que nunca se debe ascender a personal interno",
      "Que los equipos de ventas no necesitan jefe",
      "Que el problema se resuelve subiendo las comisiones",
      "Que vender bien no garantiza liderar bien: para ascender hay que evaluar y formar liderazgo",
    ],
    answer: 3,
    explain: "El puesto de jefe exige competencias distintas a las del vendedor: delegar, formar y coordinar. Un ascenso debe considerar esas competencias y acompañarse con formación en liderazgo.",
  },
  {
    id: "tq-personas-26",
    topic: "personas",
    level: 3,
    q: "Una financiera de Huancayo paga comisión a sus asesores solo por el número de créditos colocados. Los asesores colocan mucho, pero la morosidad sube. ¿Cómo conviene rediseñar el incentivo?",
    options: [
      "Duplicar la comisión por cada crédito colocado",
      "Pagar por colocación y también por calidad de cartera, es decir, créditos que se pagan a tiempo",
      "Eliminar toda la remuneración variable",
      "Pagar la comisión antes de desembolsar el crédito",
    ],
    answer: 1,
    explain: "Las personas responden a lo que se les mide y se les paga. Si solo se premia el volumen, se descuida la calidad. Un buen incentivo equilibra cantidad con calidad del resultado.",
  },
  {
    id: "tq-personas-27",
    topic: "personas",
    level: 3,
    q: "El gerente de una empresa de Arequipa se niega a capacitar a su personal porque, según él, luego se van a la competencia. ¿Qué riesgo mayor está ignorando?",
    options: [
      "Que el personal se quede sin capacitarse y la empresa pierda calidad y productividad",
      "Que la capacitación aumente el IGV por pagar",
      "Que los trabajadores capacitados rindan menos",
      "Que la capacitación reduzca la capacidad instalada",
    ],
    answer: 0,
    explain: "No capacitar también tiene un costo: errores, baja productividad y clientes insatisfechos. Además, las oportunidades de desarrollo suelen ser una razón para quedarse en la empresa, no para irse.",
  },
  {
    id: "tq-personas-28",
    topic: "personas",
    level: 3,
    q: "Una tienda en línea de Lima contrata personal para el Cyber Wow sin tomar pruebas ni verificar referencias, por el apuro. Dos contratados no saben usar el sistema y generan errores en los pedidos. ¿Qué parte del proceso falló?",
    options: [
      "El reclutamiento, porque postularon demasiadas personas",
      "La selección, porque no evaluó las competencias del puesto antes de contratar",
      "La compensación, porque el sueldo ofrecido era muy alto",
      "La desvinculación, porque debió despedir antes",
    ],
    answer: 1,
    explain: "La selección existe para comprobar que el candidato tiene las competencias del puesto. Saltarse pruebas y referencias ahorra días, pero una mala contratación cuesta más en errores y reemplazos.",
  },
  {
    id: "tq-personas-29",
    topic: "personas",
    level: 3,
    q: "Tras una fusión, el clima laboral de una empresa de Lima baja de 75 a 55 puntos. Circulan rumores y nadie sabe qué pasará con su puesto. ¿Qué acción es prioritaria?",
    options: [
      "Guardar silencio hasta tener todas las decisiones tomadas",
      "Organizar una fiesta de integración y no tocar el tema",
      "Suspender las vacaciones para mantener la operación",
      "Comunicar con claridad y frecuencia los cambios y escuchar las dudas del personal",
    ],
    answer: 3,
    explain: "En procesos de cambio, la incertidumbre es lo que más daña el clima. Informar con transparencia, aunque no todo esté decidido, reduce los rumores y la salida de los mejores talentos.",
  },
  {
    id: "tq-personas-30",
    topic: "personas",
    level: 3,
    q: "En una empresa de Trujillo, dos analistas con el mismo puesto, la misma experiencia y el mismo desempeño ganan S/ 2,500 y S/ 3,500, y se enteran. ¿Qué principio de compensaciones se vulnera?",
    options: [
      "La competitividad externa frente al mercado",
      "La remuneración variable por resultados",
      "La equidad interna: igual remuneración por trabajo de igual valor",
      "El principio del devengado",
    ],
    answer: 2,
    explain: "La equidad interna exige que puestos de igual valor y desempeño reciban una paga similar. Las diferencias sin sustento dañan el clima laboral y exponen a la empresa a reclamos.",
  },
];

export default data;
